export const initialTasks = [
  {
    id: 'FLW-142',
    title: 'Hoàn thiện luồng tạo công việc',
    project: 'Flow · Trải nghiệm sản phẩm',
    status: 'progress',
    priority: 'high',
    assignee: 'Minh Anh',
    due: '24 Th9',
  },
  {
    id: 'FLW-143',
    title: 'Thiết kế trạng thái trống cho dự án',
    project: 'Flow · Trải nghiệm sản phẩm',
    status: 'review',
    priority: 'normal',
    assignee: 'Thu Hà',
    due: '24 Th9',
  },
  {
    id: 'FLW-144',
    title: 'Bổ sung thao tác nhanh trên bảng',
    project: 'Flow · Trải nghiệm sản phẩm',
    status: 'progress',
    priority: 'urgent',
    assignee: 'Quang Huy',
    due: '25 Th9',
  },
  {
    id: 'FLW-145',
    title: 'Rà soát nội dung thông báo',
    project: 'Flow · Trải nghiệm sản phẩm',
    status: 'todo',
    priority: 'normal',
    assignee: 'Minh Anh',
    due: '26 Th9',
  },
  {
    id: 'FLW-146',
    title: 'Chuẩn hóa màu trạng thái',
    project: 'Flow · Trải nghiệm sản phẩm',
    status: 'done',
    priority: 'normal',
    assignee: 'Thu Hà',
    due: '23 Th9',
  },
  {
    id: 'FLW-147',
    title: 'Kiểm tra quyền truy cập dự án',
    project: 'Flow · Trải nghiệm sản phẩm',
    status: 'review',
    priority: 'high',
    assignee: 'Quang Huy',
    due: '25 Th9',
  },
  {
    id: 'FLW-148',
    title: 'Thêm bộ lọc theo người phụ trách',
    project: 'Flow · Trải nghiệm sản phẩm',
    status: 'todo',
    priority: 'normal',
    assignee: 'Minh Anh',
    due: '27 Th9',
  },
  {
    id: 'FLW-149',
    title: 'Hoàn thiện thư viện biểu tượng',
    project: 'Flow · Trải nghiệm sản phẩm',
    status: 'done',
    priority: 'normal',
    assignee: 'Thu Hà',
    due: '23 Th9',
  },
]
