import { defineModule } from '@ketvietlab/ketjs'
import { functions } from './functions.ts'
import { jobs } from './jobs.ts'
import { models } from './models.ts'
import { sections } from './sections.ts'
import { routes } from './routes.ts'

export default defineModule({
  name: 'website_form',
  version: '0.1.0',
  depends: ['website'],
  title: 'Biểu mẫu website',
  summary: 'Biểu mẫu có cấu trúc, chống spam và lưu submission theo từng website.',
  category: 'Website',
  messages: {
    vi: {
      'app.title': 'Biểu mẫu website',
      'app.summary': 'Biểu mẫu có cấu trúc, chống spam và lưu submission theo từng website.',
      'app.category': 'Website',
      'section.form': 'Biểu mẫu',
      'error.fieldsRequired': 'Biểu mẫu cần ít nhất một trường.',
      'error.invalidSchema': 'Cấu trúc schema biểu mẫu không hợp lệ.',
      'error.schemaTooLarge': 'Schema biểu mẫu vượt quá giới hạn cho phép.',
      'error.invalidFieldName': 'Tên trường không hợp lệ.',
      'error.duplicateField': 'Tên trường bị trùng.',
      'error.invalidFieldType': 'Loại trường không được hỗ trợ.',
      'error.payloadTooLarge': 'Dữ liệu gửi lên vượt quá giới hạn.',
      'error.unknownField': 'Trường không có trong schema.',
      'error.required': 'Thông tin bắt buộc.',
      'error.invalidEmail': 'Địa chỉ email không hợp lệ.',
      'error.invalidNumber': 'Giá trị số không hợp lệ.',
      'error.invalidCheckbox': 'Giá trị checkbox không hợp lệ.',
      'error.valueTooLong': 'Giá trị quá dài.',
      'error.siteNotFound': 'Không tìm thấy website.',
      'error.invalidName': 'Tên biểu mẫu không hợp lệ hoặc quá dài.',
      'error.duplicateName': 'Tên biểu mẫu đã được sử dụng trên website.',
      'error.invalidMessage': 'Thông báo thành công không hợp lệ hoặc quá dài.',
      'error.unavailable': 'Biểu mẫu hiện không khả dụng.',
      'error.rateLimit': 'Bạn đã gửi quá nhiều lần. Vui lòng thử lại sau.',
      'error.staleForm': 'Biểu mẫu đã được cập nhật. Hãy tải lại trang trước khi gửi.',
      'error.saveConflict': 'Biểu mẫu vừa được người khác lưu. Hãy tải lại rồi lưu lại.',
      'error.consentRequired': 'Bạn cần đồng ý với thông báo trước khi gửi.',
      'error.consentVersionRequired':
        'Hãy tải lại trang trước khi gửi, để ghi nhận đúng thông báo bạn đã đồng ý.',
      'error.invalidSummaryFields': 'Danh sách trường xem trước không hợp lệ.',
      'error.unknownSummaryField': 'Trường xem trước không có trong biểu mẫu.',
      'error.invalidRetention': 'Thời hạn lưu phải là số ngày từ 1 đến 3650.',
      'error.noRetention': 'Biểu mẫu này chưa đặt thời hạn lưu.',
      'error.exportFieldsRequired': 'Hãy chọn ít nhất một trường để xuất.',
      'error.submissionNotFound': 'Không tìm thấy lượt gửi.',
      'error.submissionPurged': 'Lượt gửi đã được xóa nội dung, không thể giữ lại.',
      'error.formNotFound': 'Không tìm thấy biểu mẫu.',
      'error.archived': 'Biểu mẫu đã được lưu trữ, không thể sửa.',
      'error.unknownDestination': 'Nơi nhận phản hồi này không có trong hệ thống.',
      'error.destinationNeedsContact':
        'Biểu mẫu chuyển phản hồi sang nơi khác cần có ô email hoặc số điện thoại để liên hệ lại khách.',
      'error.notRetryable': 'Chỉ gửi lại được phản hồi chuyển không thành công.',
    },
    en: {
      'app.title': 'Website forms',
      'app.summary': 'Structured forms with spam protection and per-site submissions.',
      'app.category': 'Website',
      'section.form': 'Form',
      'error.fieldsRequired': 'A form needs at least one field.',
      'error.invalidSchema': 'The form schema structure is invalid.',
      'error.schemaTooLarge': 'The form schema exceeds the allowed size.',
      'error.invalidFieldName': 'The field name is invalid.',
      'error.duplicateField': 'The field name is duplicated.',
      'error.invalidFieldType': 'The field type is not supported.',
      'error.payloadTooLarge': 'The submitted payload exceeds the allowed size.',
      'error.unknownField': 'The field is not declared in the schema.',
      'error.required': 'This field is required.',
      'error.invalidEmail': 'The email address is invalid.',
      'error.invalidNumber': 'The numeric value is invalid.',
      'error.invalidCheckbox': 'The checkbox value is invalid.',
      'error.valueTooLong': 'The value is too long.',
      'error.siteNotFound': 'The site was not found.',
      'error.invalidName': 'The form name is invalid or too long.',
      'error.duplicateName': 'The form name is already in use on this site.',
      'error.invalidMessage': 'The success message is invalid or too long.',
      'error.unavailable': 'The form is not available.',
      'error.rateLimit': 'Too many submissions. Please try again later.',
      'error.staleForm': 'This form has been updated. Reload the page before submitting.',
      'error.saveConflict': 'Someone else saved this form. Reload and save again.',
      'error.consentRequired': 'You must agree to the notice before submitting.',
      'error.consentVersionRequired':
        'Reload the page before submitting, so the notice you agreed to is recorded correctly.',
      'error.invalidSummaryFields': 'The preview field list is invalid.',
      'error.unknownSummaryField': 'The preview field is not declared in the form.',
      'error.invalidRetention': 'Retention must be a whole number of days between 1 and 3650.',
      'error.noRetention': 'This form has no retention period set.',
      'error.exportFieldsRequired': 'Choose at least one field to export.',
      'error.submissionNotFound': 'The submission was not found.',
      'error.submissionPurged': 'This submission has been erased and cannot be held.',
      'error.formNotFound': 'The form was not found.',
      'error.archived': 'This form has been archived and cannot be edited.',
      'error.unknownDestination': 'This destination is not available here.',
      'error.destinationNeedsContact':
        'A form that hands its submissions on needs an email or phone field, so the person can be reached.',
      'error.notRetryable': 'Only a failed hand-off can be retried.',
    },
  },
  models,
  functions,
  jobs,
  sections,
  routes,
})
