import assert from 'node:assert/strict'
import test from 'node:test'
import {
  createSerializedRunner,
  isFrameworkBuildInput,
  isGeneratedBuildOutput,
} from '../tools/watch-build.ts'

const until = async (condition: () => boolean) => {
  const deadline = Date.now() + 1_000
  while (!condition()) {
    if (Date.now() >= deadline) throw new Error('timed out waiting for build runner')
    await new Promise((resolve) => setTimeout(resolve, 5))
  }
}

test('framework build watcher discovers generated output from its banner', () => {
  const generated =
    '// @ts-nocheck Generated by tools/build-new-client.mjs — do not edit.\nconst client = true'
  assert.equal(isGeneratedBuildOutput(generated), true)
  assert.equal(isFrameworkBuildInput('packages/ketjs/src/cli.ts'), true)
  assert.equal(isFrameworkBuildInput('tools/build.mjs'), true)
  assert.equal(isFrameworkBuildInput('package-lock.json'), true)
  assert.equal(isFrameworkBuildInput('packages/ketjs/dist/cli.js'), false)
  assert.equal(isFrameworkBuildInput('packages/ketjs/dist/index.d.ts'), false)
  assert.equal(isFrameworkBuildInput('packages/ketsuite/dist/ui/client/app.css'), false)
  assert.equal(isFrameworkBuildInput('packages/ketsuite/src/ui/client/new-client.mjs', generated), false)
  assert.equal(isFrameworkBuildInput('packages/ketsuite/src/ui/client/authored-client.mjs'), true)
  assert.equal(isFrameworkBuildInput('.build/packages/ketjs/src/cli.js'), false)
})

test('framework build watcher coalesces changes and serializes rebuilds', async () => {
  let calls = 0
  const releases: Array<() => void> = []
  const runner = createSerializedRunner(
    async () => {
      calls++
      await new Promise<void>((resolve) => releases.push(resolve))
    },
    { debounceMs: 5 },
  )

  runner.trigger()
  runner.trigger()
  await until(() => calls === 1)

  runner.trigger()
  runner.trigger()
  releases.shift()?.()
  await until(() => calls === 2)
  releases.shift()?.()
  await runner.idle()

  assert.equal(calls, 2)
  await runner.close()
})
