import { defineModule } from '@ketvietlab/ketjs'
import { routes } from './routes.ts'
import { searchFilterFunctions } from './search-functions.ts'

export default defineModule({
  name: 'manufacturing_backend',
  version: '0.1.0',
  depends: ['manufacturing', 'backend'],
  title: 'Sản xuất trong quản trị',
  summary: 'Điều hành định mức và lệnh sản xuất.',
  category: 'Sản xuất',
  routes,
  functions: searchFilterFunctions,
  menus: {
    manufacturing: {
      label: 'menu.app',
      icon: 'factory',
      path: '/admin/manufacturing',
      sequence: 35,
      needs: 'manufacturing.listProductions',
    },
    'manufacturing.boms': {
      parent: 'manufacturing',
      label: 'menu.boms',
      path: '/admin/manufacturing/boms',
      sequence: 10,
      needs: 'manufacturing.listBoms',
    },
    'manufacturing.workCenters': {
      parent: 'manufacturing',
      label: 'menu.workCenters',
      path: '/admin/manufacturing/work-centers',
      sequence: 20,
      needs: 'manufacturing.listWorkCenters',
    },
  },
  messages: {
    vi: {
      'app.title': 'Sản xuất trong quản trị',
      'app.summary': 'Điều hành định mức và lệnh sản xuất.',
      'app.category': 'Sản xuất',
      'menu.app': 'Sản xuất',
      'menu.boms': 'Định mức nguyên liệu',
      'menu.workCenters': 'Trung tâm sản xuất',
      'orders.title': 'Lệnh sản xuất',
      'orders.create': 'Tạo lệnh sản xuất',
      'orders.detail': 'Chi tiết lệnh sản xuất',
      'boms.title': 'Định mức nguyên liệu',
      'boms.create': 'Tạo định mức cơ bản',
      'workCenters.title': 'Trung tâm sản xuất',
      'workCenters.create': 'Thêm trung tâm',
      'workCenters.edit': 'Chỉnh sửa trung tâm',
      'field.name': 'Tên',
      'field.code': 'Mã',
      'field.bom': 'Định mức',
      'field.product': 'Thành phẩm',
      'field.component': 'Nguyên liệu',
      'field.quantity': 'Số lượng',
      'field.uom': 'Đơn vị',
      'field.source': 'Kho nguyên liệu',
      'field.production': 'Vị trí sản xuất',
      'field.destination': 'Kho thành phẩm',
      'field.scheduledStart': 'Bắt đầu dự kiến',
      'field.state': 'Trạng thái',
      'field.capacity': 'Công suất',
      'field.efficiency': 'Hiệu suất (%)',
      'field.cost': 'Chi phí/giờ',
      'field.operation': 'Công đoạn',
      'field.workCenter': 'Trung tâm',
      'field.duration': 'Phút dự kiến',
      'field.actions': 'Thao tác',
      'action.create': 'Tạo',
      'action.save': 'Lưu',
      'action.archive': 'Lưu trữ',
      'action.restore': 'Khôi phục',
      'action.confirm': 'Xác nhận',
      'action.start': 'Bắt đầu',
      'action.pause': 'Tạm dừng',
      'action.finish': 'Hoàn tất công đoạn',
      'action.complete': 'Hoàn tất sản xuất',
      'action.cancel': 'Hủy',
      'state.draft': 'Nháp',
      'state.confirmed': 'Đã xác nhận',
      'state.in_progress': 'Đang sản xuất',
      'state.to_close': 'Chờ chốt',
      'state.done': 'Hoàn tất',
      'state.cancelled': 'Đã hủy',
      'state.active': 'Đang hoạt động',
      'state.archived': 'Đã lưu trữ',
      'empty.orders': 'Chưa có lệnh sản xuất',
      'empty.ordersHint': 'Tạo định mức rồi lập lệnh sản xuất đầu tiên.',
      'empty.boms': 'Chưa có định mức',
      'empty.bomsHint': 'Tạo định mức nguyên liệu đầu tiên.',
      'empty.workCenters': 'Chưa có trung tâm sản xuất',
      'empty.workCentersHint': 'Thêm trung tâm để cấu hình công đoạn.',
      'error.invalid': 'Không thể lưu dữ liệu sản xuất.',
    },
    en: {
      'app.title': 'Manufacturing in admin',
      'app.summary': 'Operate bills of materials and production orders.',
      'app.category': 'Manufacturing',
      'menu.app': 'Manufacturing',
      'menu.boms': 'Bills of materials',
      'menu.workCenters': 'Work centers',
      'orders.title': 'Production orders',
      'orders.create': 'Create production order',
      'orders.detail': 'Production order detail',
      'boms.title': 'Bills of materials',
      'boms.create': 'Create a basic BOM',
      'workCenters.title': 'Work centers',
      'workCenters.create': 'Add work center',
      'workCenters.edit': 'Edit work center',
      'field.name': 'Name',
      'field.code': 'Code',
      'field.bom': 'Bill of materials',
      'field.product': 'Finished product',
      'field.component': 'Component',
      'field.quantity': 'Quantity',
      'field.uom': 'Unit',
      'field.source': 'Component location',
      'field.production': 'Production location',
      'field.destination': 'Finished-goods location',
      'field.scheduledStart': 'Scheduled start',
      'field.state': 'Status',
      'field.capacity': 'Capacity',
      'field.efficiency': 'Efficiency (%)',
      'field.cost': 'Cost/hour',
      'field.operation': 'Operation',
      'field.workCenter': 'Work center',
      'field.duration': 'Expected minutes',
      'field.actions': 'Actions',
      'action.create': 'Create',
      'action.save': 'Save',
      'action.archive': 'Archive',
      'action.restore': 'Restore',
      'action.confirm': 'Confirm',
      'action.start': 'Start',
      'action.pause': 'Pause',
      'action.finish': 'Finish operation',
      'action.complete': 'Complete production',
      'action.cancel': 'Cancel',
      'state.draft': 'Draft',
      'state.confirmed': 'Confirmed',
      'state.in_progress': 'In progress',
      'state.to_close': 'To close',
      'state.done': 'Done',
      'state.cancelled': 'Cancelled',
      'state.active': 'Active',
      'state.archived': 'Archived',
      'empty.orders': 'No production orders',
      'empty.ordersHint': 'Create a BOM, then create the first production order.',
      'empty.boms': 'No bills of materials',
      'empty.bomsHint': 'Create the first bill of materials.',
      'empty.workCenters': 'No work centers',
      'empty.workCentersHint': 'Add a work center before configuring operations.',
      'error.invalid': 'The manufacturing data could not be saved.',
    },
  },
})

export {
  bomCreateModal,
  bomCreateScreen,
  bomListColumns,
  bomsListScreen,
  orderCreateScreen,
  orderScreen,
  ordersListScreen,
  workCenterFields,
  workCenterFormModal,
  workCenterFormScreen,
  workCenterListColumns,
  workCentersListScreen,
} from './screens/index.ts'
export type {
  BomCreateScreenOptions,
  BomListRow,
  BomsListScreenOptions,
  ManufacturingOrderCreateScreenOptions,
  ManufacturingOrderExecutionRow,
  ManufacturingOrderListRow,
  OrdersListScreenOptions,
  WorkCenterFormScreenOptions,
  WorkCenterFormValues,
  WorkCenterListRow,
  WorkCentersListScreenOptions,
} from './screens/index.ts'
