import type { ModelDef } from '@ketvietlab/ketjs'

export const models: Record<string, ModelDef> = {
  Program: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      programType: 'text',
      active: 'bool',
      designVersion: 'int?',
      configVersion: 'int?',
      usageCount: 'int?',
      phase: 'text?',
      startDate: 'text?',
      endDate: 'text?',
      voucherValidityDays: 'int?',
      sequence: 'int',
      currency: 'text',
      dateFrom: 'datetime?',
      dateTo: 'datetime?',
      limitUsage: 'bool',
      maxUsage: 'int?',
      appliesOn: 'text',
      trigger: 'text',
      portalVisible: 'bool',
      pointName: 'text',
      availableSale: 'bool',
      availablePos: 'bool',
      createdAt: 'datetime',
      updatedAt: 'datetime',
    },
    indexes: { active_sequence: { fields: ['companyId', 'active', 'sequence'] } },
  },
  ProgramPricelist: {
    scope: 'company',
    fields: { id: 'id', programId: 'ref:loyalty.Program', pricelistId: 'ref:pricing.Pricelist' },
    indexes: { program_pricelist: { fields: ['companyId', 'programId', 'pricelistId'], unique: true } },
  },
  Tag: {
    scope: 'shared',
    fields: { id: 'id', code: 'text', name: 'text', active: 'bool' },
    indexes: { code: { fields: ['code'], unique: true } },
  },
  ProductTag: {
    scope: 'shared',
    fields: { id: 'id', productId: 'ref:product.Product', tagId: 'ref:loyalty.Tag' },
    indexes: { product_tag: { fields: ['productId', 'tagId'], unique: true } },
  },
  Rule: {
    scope: 'company',
    fields: {
      id: 'id',
      programId: 'ref:loyalty.Program',
      active: 'bool',
      priority: 'int',
      productId: 'ref:product.Product?',
      categoryId: 'ref:product.Category?',
      tagId: 'ref:loyalty.Tag?',
      pointAmount: 'decimal',
      pointMode: 'text',
      pointSplit: 'bool',
      minimumQuantity: 'decimal',
      minimumAmount: 'decimal',
      taxMode: 'text',
      mode: 'text',
      code: 'text?',
      normalizedCode: 'text?',
    },
    indexes: {
      program_priority: { fields: ['companyId', 'programId', 'priority'] },
      active_code: { fields: ['companyId', 'normalizedCode'], unique: true },
    },
  },
  RuleProduct: {
    scope: 'company',
    fields: { id: 'id', ruleId: 'ref:loyalty.Rule', productId: 'ref:product.Product' },
    indexes: { rule_product: { fields: ['companyId', 'ruleId', 'productId'], unique: true } },
  },
  Reward: {
    scope: 'company',
    fields: {
      id: 'id',
      programId: 'ref:loyalty.Program',
      active: 'bool',
      description: 'text',
      rewardType: 'text',
      discount: 'decimal',
      discountMode: 'text',
      discountApplicability: 'text',
      discountMaximum: 'decimal?',
      discountProductId: 'ref:product.Product?',
      discountCategoryId: 'ref:product.Category?',
      discountTagId: 'ref:loyalty.Tag?',
      rewardProductId: 'ref:product.Product?',
      lineProductId: 'ref:product.Product',
      rewardProductQuantity: 'decimal',
      requiredPoints: 'decimal',
      clearWallet: 'bool',
    },
    indexes: { program_active: { fields: ['companyId', 'programId', 'active'] } },
  },
  RewardProduct: {
    scope: 'company',
    fields: { id: 'id', rewardId: 'ref:loyalty.Reward', productId: 'ref:product.Product' },
    indexes: { reward_product: { fields: ['companyId', 'rewardId', 'productId'], unique: true } },
  },
  Wallet: {
    scope: 'company',
    fields: {
      id: 'id',
      programId: 'ref:loyalty.Program',
      partnerId: 'ref:partner.Partner?',
      code: 'text',
      normalizedCode: 'text',
      unit: 'text',
      balance: 'decimal',
      reserved: 'decimal',
      expiresAt: 'datetime?',
      active: 'bool',
      version: 'int',
      createdAt: 'datetime',
    },
    indexes: {
      code: { fields: ['companyId', 'normalizedCode'], unique: true },
      partner_program: { fields: ['companyId', 'partnerId', 'programId'] },
    },
  },
  LedgerEntry: {
    scope: 'company',
    fields: {
      id: 'id',
      walletId: 'ref:loyalty.Wallet',
      operation: 'text',
      amount: 'decimal',
      balanceDelta: 'decimal',
      sourceType: 'text',
      sourceId: 'text',
      sourceOperation: 'text',
      sourceKey: 'text',
      descriptionCode: 'text',
      reversedEntryId: 'ref:loyalty.LedgerEntry?',
      metadata: 'json?',
      createdAt: 'datetime',
    },
    indexes: {
      source: { fields: ['companyId', 'sourceKey'], unique: true },
      wallet_created: { fields: ['companyId', 'walletId', 'createdAt'] },
    },
  },
  Reservation: {
    scope: 'company',
    fields: {
      id: 'id',
      walletId: 'ref:loyalty.Wallet',
      orderType: 'text',
      orderId: 'text',
      rewardId: 'ref:loyalty.Reward',
      amount: 'decimal',
      state: 'text',
      expiresAt: 'datetime?',
      createdAt: 'datetime',
      updatedAt: 'datetime',
    },
    indexes: { order_reward: { fields: ['companyId', 'orderType', 'orderId', 'rewardId'], unique: true } },
  },
  /** A money reservation is separate from a reward so stored value never becomes a discount. */
  StoredValueReservation: {
    scope: 'company',
    fields: {
      id: 'id',
      walletId: 'ref:loyalty.Wallet',
      sourceType: 'text',
      sourceId: 'text',
      sourceKey: 'text',
      amount: 'decimal',
      state: 'text',
      expiresAt: 'datetime?',
      createdAt: 'datetime',
      updatedAt: 'datetime',
    },
    indexes: {
      source: { fields: ['companyId', 'sourceKey'], unique: true },
      wallet_state: { fields: ['companyId', 'walletId', 'state', 'expiresAt'] },
    },
  },
  Application: {
    scope: 'company',
    fields: {
      id: 'id',
      orderType: 'text',
      orderId: 'text',
      partnerId: 'ref:partner.Partner?',
      programId: 'ref:loyalty.Program',
      walletId: 'ref:loyalty.Wallet?',
      rewardId: 'ref:loyalty.Reward?',
      code: 'text?',
      pointsEarned: 'decimal',
      pointsSpent: 'decimal',
      discountAmount: 'decimal',
      rewardPayload: 'json?',
      currency: 'text',
      state: 'text',
      createdAt: 'datetime',
      updatedAt: 'datetime',
    },
    indexes: { order_program: { fields: ['companyId', 'orderType', 'orderId', 'programId'], unique: true } },
  },
  Tier: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      code: 'text',
      sequence: 'int',
      minimumSpend: 'decimal',
      windowMonths: 'int?',
      redeemPercent: 'decimal',
      active: 'bool',
    },
    indexes: { code: { fields: ['companyId', 'code'], unique: true } },
  },
  EarnGroup: {
    scope: 'company',
    fields: {
      id: 'id',
      programId: 'ref:loyalty.Program',
      name: 'text',
      code: 'text',
      priority: 'int',
      earnsPoints: 'bool',
      currencyPerPoint: 'decimal',
      productId: 'ref:product.Product?',
      categoryId: 'ref:product.Category?',
      tagId: 'ref:loyalty.Tag?',
      active: 'bool',
    },
    indexes: {
      code: { fields: ['companyId', 'code'], unique: true },
      priority: { fields: ['companyId', 'active', 'priority'] },
    },
  },
  MembershipConfig: {
    scope: 'company',
    fields: {
      id: 'id',
      programId: 'ref:loyalty.Program',
      windowMonths: 'int',
      pointValue: 'decimal',
      minimumRedeemStep: 'decimal',
      fallbackCurrencyPerPoint: 'decimal',
      fallbackEnabled: 'bool',
      updatedAt: 'datetime',
    },
    indexes: { program: { fields: ['companyId', 'programId'], unique: true } },
  },
  // Retained as a storage-compatible legacy shape; tier evaluation reads Tier.windowMonths.
  MembershipPolicy: {
    scope: 'company',
    fields: {
      id: 'id',
      windowMonths: 'int',
      updatedAt: 'datetime',
    },
  },
  Membership: {
    scope: 'company',
    fields: {
      id: 'id',
      partnerId: 'ref:partner.Partner',
      tierId: 'ref:loyalty.Tier?',
      rollingSpend: 'decimal',
      points: 'decimal',
      windowMonths: 'int',
      refreshedAt: 'datetime',
      version: 'int',
    },
    indexes: { partner: { fields: ['companyId', 'partnerId'], unique: true } },
  },
  SpendEntry: {
    scope: 'company',
    fields: {
      id: 'id',
      partnerId: 'ref:partner.Partner',
      sourceType: 'text',
      sourceId: 'text',
      amount: 'decimal',
      currency: 'text',
      occurredAt: 'datetime',
      reversedAt: 'datetime?',
    },
    indexes: {
      source: { fields: ['companyId', 'sourceType', 'sourceId'], unique: true },
      partner_date: { fields: ['companyId', 'partnerId', 'occurredAt'] },
    },
  },
}
