import { defineModule } from '@ketvietlab/ketjs'
import { routes } from './routes.ts'
import { searchFilterFunctions } from './search-functions.ts'

export default defineModule({
  name: 'address_backend',
  version: '0.1.0',
  depends: ['address', 'backend'],
  title: 'Dữ liệu địa chỉ',
  summary: 'Cài đặt và kiểm tra catalog địa giới theo quốc gia.',
  category: 'Danh bạ',
  routes,
  functions: searchFilterFunctions,
  menus: {
    'admin.addresses': {
      parent: 'admin.config',
      label: 'menu.addresses',
      path: '/admin/addresses',
      needs: 'address.catalogStatus',
      sequence: 40,
    },
  },
  messages: {
    vi: {
      'app.title': 'Dữ liệu địa chỉ',
      'app.summary': 'Cài đặt và kiểm tra catalog địa giới theo quốc gia.',
      'app.category': 'Danh bạ',
      'menu.addresses': 'Dữ liệu địa chỉ',
      title: 'Dữ liệu địa chỉ',
      empty: 'Chưa có gói dữ liệu địa chỉ',
      emptyHint: 'Bổ sung quốc gia vào thư mục data của module address.',
      'country.VN': 'Việt Nam',
      'field.country': 'Quốc gia',
      'field.version': 'Phiên bản',
      'field.status': 'Trạng thái',
      'field.records': 'Số đơn vị',
      'field.actions': 'Thao tác',
      'field.codeSystem': 'Hệ mã',
      'field.name': 'Tên chính thức',
      'field.code': 'Mã catalog',
      'field.kind': 'Loại',
      'state.available': 'Sẵn sàng cài',
      'state.installed': 'Đang hoạt động',
      'error.title': 'Không thể hoàn tất',
      'action.install': 'Cài catalog',
      'action.open': 'Xem địa giới',
      'action.back': 'Quay lại',
      notInstalled: 'Catalog chưa được cài',
      notInstalledHint: 'Cài catalog để sử dụng tỉnh/thành và xã/phường trên địa chỉ đối tác.',
      'divisions.rootHint': 'Danh sách tỉnh và thành phố trực thuộc trung ương.',
      'divisions.childrenHint': 'Danh sách xã, phường và đặc khu trực thuộc.',
      'divisions.empty': 'Không có đơn vị con',
      'divisions.emptyHint': 'Đơn vị này là nút cuối trong catalog.',
    },
    en: {
      'app.title': 'Address data',
      'app.summary': 'Install and inspect country administrative catalogs.',
      'app.category': 'Contacts',
      'menu.addresses': 'Address data',
      title: 'Address data',
      empty: 'No address data packs',
      emptyHint: 'Add a country to the address module data directory.',
      'country.VN': 'Vietnam',
      'field.country': 'Country',
      'field.version': 'Version',
      'field.status': 'Status',
      'field.records': 'Divisions',
      'field.actions': 'Actions',
      'field.codeSystem': 'Code system',
      'field.name': 'Official name',
      'field.code': 'Catalog code',
      'field.kind': 'Kind',
      'state.available': 'Ready to install',
      'state.installed': 'Active',
      'error.title': 'Unable to complete',
      'action.install': 'Install catalog',
      'action.open': 'Browse divisions',
      'action.back': 'Back',
      notInstalled: 'Catalog is not installed',
      notInstalledHint: 'Install it to select provinces and wards on partner addresses.',
      'divisions.rootHint': 'Provinces and centrally governed municipalities.',
      'divisions.childrenHint': 'Child communes, wards, and special zones.',
      'divisions.empty': 'No child divisions',
      'divisions.emptyHint': 'This is a leaf in the active catalog.',
    },
  },
})

export { catalogsScreen, countryScreen } from './screens/index.ts'
