import { defineModule } from '@ketvietlab/ketjs'
import { functions } from './functions.ts'
import { islands } from './islands.ts'
import { routes } from './routes.ts'

export default defineModule({
  name: 'stock_backend',
  version: '0.1.0',
  depends: ['stock', 'backend'],
  assets: new URL('./client/', import.meta.url),
  islands,
  functions,
  behaviors: {
    'stock.editor': {
      client: 'stock.mjs',
      export: 'editorBehavior',
      when: 'form[data-scope="stock-transfer"], form[data-scope="stock-lot"]',
    },
  },
  title: 'Kho trong quản trị',
  summary: 'Warehouse, tồn kho, dịch chuyển và routes.',
  category: 'Hệ thống',
  routes,
  joints: {
    'picking.collaboration': {
      props: { resModel: 'text', resId: 'id', lang: 'text' },
      multiple: true,
    },
    'picking.editor': { props: { identity: 'text', pickingId: 'id', lang: 'text?' } },
    'lot.collaboration': {
      props: { resModel: 'text', resId: 'id', lang: 'text' },
      multiple: true,
    },
    'lot.editor': { props: { identity: 'text', lotId: 'id', lang: 'text?' } },
  },
  menus: {
    stock: { label: 'menu.app', icon: 'warehouse', sequence: 25 },
    'stock.overview': {
      parent: 'stock',
      label: 'overview.title',
      path: '/admin/stock',
      needs: 'stock.listPickings',
      sequence: 1000,
    },
    'stock.transfers': {
      parent: 'stock',
      label: 'menu.transfers',
      path: '/admin/stock/transfers',
      needs: 'stock.listPickings',
      sequence: 1010,
    },
    'stock.inventory': {
      parent: 'stock',
      label: 'menu.inventory',
      path: '/admin/stock/inventory',
      needs: 'stock.listQuants',
      sequence: 1020,
    },
    'stock.forecast': {
      parent: 'stock',
      label: 'menu.forecast',
      path: '/admin/stock/forecast',
      needs: 'stock.forecast',
      sequence: 1030,
    },
    'stock.replenishment': {
      parent: 'stock',
      label: 'menu.replenishment',
      path: '/admin/stock/replenishment',
      needs: 'stock.listOrderpoints',
      sequence: 1040,
    },
    'stock.config': { parent: 'stock', label: 'menu.config', sequence: 2000 },
    'stock.warehouses': {
      parent: 'stock.config',
      label: 'menu.warehouses',
      path: '/admin/stock/warehouses',
      needs: 'stock.listWarehouses',
      sequence: 10,
    },
    'stock.locations': {
      parent: 'stock.config',
      label: 'menu.locations',
      path: '/admin/stock/locations',
      needs: 'stock.listLocations',
      sequence: 20,
    },
    'stock.pickingTypes': {
      parent: 'stock.config',
      label: 'menu.pickingTypes',
      path: '/admin/stock/picking-types',
      needs: 'stock.listPickingTypes',
      sequence: 30,
    },
    'stock.lots': {
      parent: 'stock.config',
      label: 'menu.lots',
      path: '/admin/stock/lots',
      needs: 'stock.listLots',
      sequence: 40,
    },
    'stock.routes': {
      parent: 'stock.config',
      label: 'menu.routes',
      path: '/admin/stock/routes',
      needs: 'stock.listRoutes',
      sequence: 50,
    },
  },
  messages: {
    vi: {
      'overview.title': 'Tổng quan kho',
      'overview.queue': 'Phiếu cần xử lý',
      'overview.empty': 'Không có phiếu kho đang chờ xử lý.',
      'modal.edit': 'Sửa',
      'modal.relatedOperations': 'Giao hàng và lịch sử',
      'modal.information': 'Thông tin',
      'modal.products': 'Sản phẩm',
      'modal.demand': 'Nhu cầu',
      'modal.picked': 'Đã lấy hàng',
      'modal.recordPicked': 'Ghi nhận lấy hàng',
      'modal.quantity': 'Số lượng',
      'modal.yes': 'Có',
      'modal.no': 'Không',
      'modal.remaining': 'Phần hàng còn lại',
      'modal.confirmCancel': 'Huỷ phiếu dịch chuyển này?',

      'modal.confirmRun': 'Chạy bổ sung hàng theo quy tắc này?',
      'count.preview': 'Xem chênh lệch',
      'count.previewTitle': 'Chưa ghi nhận thay đổi',
      'count.previewHint': 'Kiểm tra chênh lệch trước khi áp dụng. Hàng đã giữ không thay đổi.',
      'count.difference': 'Chênh lệch',
      'count.reason': 'Lý do kiểm kê',
      'count.unitHint': 'Nhập theo đơn vị tồn kho gốc của sản phẩm.',
      'app.title': 'Kho trong quản trị',
      'app.summary': 'Quản lý đa kho, tồn kho, dịch chuyển và quy tắc cung ứng.',
      'app.category': 'Hệ thống',
      'menu.app': 'Kho',
      'menu.operations': 'Vận hành',
      'menu.transfers': 'Dịch chuyển',
      'menu.inventory': 'Tồn kho',
      'menu.forecast': 'Dự báo',
      'menu.replenishment': 'Bổ sung hàng',
      'menu.config': 'Cấu hình',
      'menu.warehouses': 'Kho hàng',
      'menu.locations': 'Vị trí',
      'menu.pickingTypes': 'Loại hoạt động',
      'menu.lots': 'Lô / Sê-ri',
      'menu.routes': 'Tuyến cung ứng',
      inventory: 'Tồn kho',
      'inventory.kicker': 'Vận hành kho',
      'inventory.workspace.title': 'Kiểm kê thực tế',
      'inventory.workspace.subtitle': 'Đối chiếu số lượng đếm được với tồn kho hệ thống.',
      'inventory.summary.onHand': 'Tổng tồn',
      'inventory.summary.balances': 'Số dư tồn kho',
      'inventory.summary.locations': 'Vị trí có hàng',
      'inventory.applied.title': 'Đã áp dụng kiểm kê',
      'inventory.applied.message': 'Chênh lệch đã được ghi nhận bằng dịch chuyển kho.',
      'inventory.configuration.title': 'Chưa đủ cấu hình để kiểm kê',
      'inventory.configuration.message':
        'Cần có sản phẩm, đơn vị tính, vị trí nội bộ và vị trí kiểm kê trước khi ghi nhận số đếm.',
      'inventory.configuration.action': 'Mở cấu hình vị trí',
      'inventory.adjustmentLocation.help': 'Vị trí ảo dùng để ghi nhận phần chênh lệch kiểm kê.',
      'inventory.balances.title': 'Tồn kho hiện tại',
      'inventory.balances.hint': 'Số lượng thực tế, đã giữ và có thể sử dụng theo từng vị trí.',
      'inventory.empty': 'Chưa có tồn kho tại vị trí nội bộ',
      'inventory.emptyHint': 'Ghi nhận số đếm đầu tiên để tạo số dư tồn kho.',
      'inventory.col.product': 'Sản phẩm',
      'inventory.col.reference': 'Mã nội bộ',
      'inventory.col.location': 'Vị trí',
      'inventory.col.lot': 'Lô / Sê-ri',
      'inventory.col.onHand': 'Tồn thực tế',
      'inventory.col.reserved': 'Đã giữ',
      'inventory.col.available': 'Có thể dùng',
      transfers: 'Dịch chuyển',
      'transfer.list.kicker': 'Vận hành kho',
      'transfer.list.title': 'Phiếu chuyển kho',
      'transfer.list.subtitle': 'Theo dõi nhập, xuất và dịch chuyển nội bộ tại một nơi.',
      'transfer.list.summary.open': 'Đang mở',
      'transfer.list.summary.ready': 'Sẵn sàng',
      'transfer.list.summary.done': 'Hoàn tất',
      'transfer.create.title': 'Tạo phiếu chuyển kho',
      'transfer.create.hint': 'Chọn loại hoạt động; vị trí nguồn và đích được lấy từ cấu hình kho.',
      'transfer.create.reference.help': 'Mã tham chiếu dùng để nhận diện phiếu trong vận hành kho.',
      'transfer.list.records.title': 'Phiếu chuyển kho',
      'transfer.list.records.hint': 'Các trường vận hành cốt lõi của danh sách dịch chuyển.',
      'transfer.list.col.reference': 'Tham chiếu',
      'transfer.list.col.source': 'Từ',
      'transfer.list.col.destination': 'Đến',
      'transfer.list.col.scheduledDate': 'Ngày dự kiến',
      'transfer.list.col.operationType': 'Loại hoạt động',
      'transfer.list.col.state': 'Trạng thái',
      'transfer.list.empty': 'Chưa có phiếu chuyển kho',
      'transfer.list.emptyHint': 'Tạo phiếu đầu tiên để bắt đầu xử lý hàng hóa.',
      warehouses: 'Kho hàng',
      'warehouse.kicker': 'Cấu hình kho',
      'warehouse.title': 'Kho hàng',
      'warehouse.subtitle': 'Định nghĩa kho vật lý và luồng nhận, giao hàng của từng kho.',
      'warehouse.summary.total': 'Kho đang dùng',
      'warehouse.summary.receipts': 'Nhận nhiều bước',
      'warehouse.summary.deliveries': 'Giao nhiều bước',
      'warehouse.create.title': 'Tạo kho hàng',
      'warehouse.create.hint': 'Các vị trí, loại hoạt động và tuyến mặc định được sinh từ cấu hình này.',
      'warehouse.configured.title': 'Kho đã cấu hình',
      'warehouse.configured.hint': 'Tóm tắt tên viết tắt và luồng hàng của từng kho.',
      'warehouse.field.name': 'Tên kho',
      'warehouse.field.name.placeholder': 'Ví dụ: Kho trung tâm',
      'warehouse.field.code': 'Tên viết tắt',
      'warehouse.field.code.placeholder': 'Ví dụ: KTT',
      'warehouse.field.code.help': 'Mã ngắn duy nhất trong công ty, dùng làm tiền tố vận hành.',
      'warehouse.col.name': 'Kho hàng',
      'warehouse.col.code': 'Tên viết tắt',
      'warehouse.col.reception': 'Lô hàng đến',
      'warehouse.col.delivery': 'Lô hàng đi',
      'warehouse.col.locations': 'Số vị trí',
      'warehouse.col.transfers': 'Số phiếu',
      'warehouse.empty': 'Chưa có kho hàng',
      'warehouse.emptyHint': 'Tạo kho đầu tiên để sinh vị trí và loại hoạt động mặc định.',
      routes: 'Tuyến cung ứng',
      'stockRoute.list.kicker': 'Cấu hình cung ứng',
      'stockRoute.list.title': 'Tuyến cung ứng',
      'stockRoute.list.subtitle': 'Định nghĩa thứ tự các luồng hàng chạy qua kho và vị trí.',
      'stockRoute.list.summary.total': 'Tổng tuyến',
      'stockRoute.list.summary.configured': 'Đã có quy tắc',
      'stockRoute.list.summary.rules': 'Tổng quy tắc',
      'stockRoute.create.title': 'Tạo tuyến cung ứng',
      'stockRoute.create.hint': 'Tạo tuyến trước, sau đó cấu hình các quy tắc kéo và đẩy hàng.',
      'stockRoute.field.name': 'Tên tuyến',
      'stockRoute.field.name.placeholder': 'Ví dụ: Nhận hàng hai bước',
      'stockRoute.field.sequence.help': 'Số nhỏ hơn được ưu tiên khi nhiều tuyến cùng áp dụng.',
      'stockRoute.list.records.title': 'Tuyến cung ứng đã cấu hình',
      'stockRoute.list.records.hint': 'Danh sách tuyến kho theo thứ tự ưu tiên.',
      'stockRoute.list.col.name': 'Tuyến cung ứng',
      'stockRoute.list.col.sequence': 'Thứ tự',
      'stockRoute.list.col.rules': 'Quy tắc',
      'stockRoute.list.col.sources': 'Vị trí nguồn',
      'stockRoute.list.col.destinations': 'Vị trí đích',
      'stockRoute.list.col.actions': 'Cách dịch chuyển',
      'stockRoute.list.empty': 'Chưa có tuyến cung ứng',
      'stockRoute.list.emptyHint': 'Tạo tuyến đầu tiên để mô tả luồng hàng qua kho.',
      'stockRoute.detail.kicker': 'Tuyến cung ứng',
      'stockRoute.status.active': 'Đang hoạt động',
      'stockRoute.status.archived': 'Đã lưu trữ',
      'stockRoute.detail.summary.rules': 'Tổng quy tắc',
      'stockRoute.detail.summary.pull': 'Quy tắc kéo',
      'stockRoute.detail.summary.push': 'Quy tắc đẩy',
      'stockRoute.detail.information.title': 'Thông tin tuyến',
      'stockRoute.detail.information.hint': 'Tên và thứ tự ưu tiên của tuyến trong quá trình cung ứng.',
      'stockRoute.detail.rules.title': 'Quy tắc đã cấu hình',
      'stockRoute.detail.rules.hint': 'Các bước kéo và đẩy hàng được áp dụng theo thứ tự.',
      'stockRoute.rule.col.name': 'Quy tắc',
      'stockRoute.rule.empty': 'Chưa có quy tắc',
      'stockRoute.rule.emptyHint': 'Thêm quy tắc đầu tiên để tuyến có thể điều phối luồng hàng.',
      'stockRoute.rule.create.title': 'Thêm quy tắc',
      'stockRoute.rule.create.hint': 'Chọn hành động, vị trí và loại hoạt động cho bước tiếp theo.',
      'stockRoute.rule.name.placeholder': 'Ví dụ: Kéo hàng về khu nhập',
      'record.receiptRule.supplier-stock': 'Nhận vào tồn kho',
      'record.receiptRule.supplier-input': 'Nhận vào khu nhập',
      'record.receiptRule.input-stock': 'Từ khu nhập vào tồn kho',
      'record.receiptRule.input-quality': 'Từ khu nhập đến kiểm tra chất lượng',
      'record.receiptRule.quality-stock': 'Từ kiểm tra chất lượng vào tồn kho',
      'record.deliveryRule.stock-customer': 'Giao trực tiếp từ tồn kho',
      'record.deliveryRule.stock-output': 'Lấy hàng ra khu xuất',
      'record.deliveryRule.stock-pack': 'Lấy hàng đến khu đóng gói',
      'record.deliveryRule.pack-output': 'Từ khu đóng gói ra khu xuất',
      'record.deliveryRule.output-customer': 'Giao từ khu xuất đến khách hàng',
      locations: 'Vị trí kho',
      'location.kicker': 'Cấu hình kho',
      'location.title': 'Vị trí kho',
      'location.subtitle': 'Phản ánh cấu trúc kho vật lý, vị trí đối tác và vị trí ảo của luồng tồn kho.',
      'location.summary.internal': 'Vị trí nội bộ',
      'location.summary.views': 'Nhóm vị trí',
      'location.summary.warehouses': 'Kho liên kết',
      'location.create.title': 'Tạo vị trí',
      'location.create.hint': 'Đặt vị trí trong cây kho và chọn đúng loại sử dụng cho dịch chuyển tồn kho.',
      'location.configured.title': 'Cây vị trí',
      'location.configured.hint': 'Tên đầy đủ, loại vị trí và kho liên kết.',
      'location.field.name': 'Tên vị trí',
      'location.field.name.placeholder': 'Ví dụ: Kệ A-01',
      'location.field.usage.help': 'Loại vị trí quyết định cách số lượng đi vào dự báo và tồn thực tế.',
      'location.field.warehouse.help': 'Chỉ chọn khi vị trí thuộc cấu trúc của một kho cụ thể.',
      'location.col.location': 'Vị trí',
      'location.col.usage': 'Loại vị trí',
      'location.col.warehouse': 'Kho hàng',
      'location.col.parent': 'Vị trí cha',
      'location.col.products': 'Sản phẩm có tồn',
      'location.empty': 'Chưa có vị trí kho',
      'location.emptyHint': 'Tạo kho hoặc vị trí đầu tiên để bắt đầu xây cây vị trí.',
      pickingTypes: 'Loại hoạt động',
      'pickingType.kicker': 'Cấu hình kho',
      'pickingType.title': 'Loại hoạt động',
      'pickingType.subtitle': 'Cấu hình luồng nhập, xuất và điều chuyển mặc định của từng kho.',
      'pickingType.summary.incoming': 'Luồng nhập',
      'pickingType.summary.outgoing': 'Luồng xuất',
      'pickingType.summary.internal': 'Luồng nội bộ',
      'pickingType.create.title': 'Tạo loại hoạt động',
      'pickingType.create.hint': 'Chọn kho, loại luồng, vị trí mặc định và chính sách backorder.',
      'pickingType.configured.title': 'Loại hoạt động đã cấu hình',
      'pickingType.configured.hint': 'Các luồng nhập, xuất và dịch chuyển nội bộ cốt lõi.',
      'pickingType.field.name': 'Tên loại hoạt động',
      'pickingType.field.name.placeholder': 'Ví dụ: Nhập kho cửa hàng',
      'pickingType.field.code': 'Loại thao tác',
      'pickingType.field.backorder.help': 'Cách xử lý số lượng còn lại khi hoàn tất một phần phiếu.',
      'pickingType.col.name': 'Loại hoạt động',
      'pickingType.col.code': 'Loại thao tác',
      'pickingType.col.warehouse': 'Kho hàng',
      'pickingType.col.route': 'Vị trí mặc định',
      'pickingType.col.backorder': 'Backorder',
      'pickingType.empty': 'Chưa có loại hoạt động',
      'pickingType.emptyHint': 'Tạo kho hoặc loại hoạt động đầu tiên để bắt đầu luân chuyển hàng.',
      'lot.list.kicker': 'Truy xuất kho',
      'lot.list.title': 'Lô và số sê-ri',
      'lot.list.subtitle': 'Theo dõi định danh, sản phẩm và tồn thực tế của từng lô hoặc số sê-ri.',
      'lot.list.summary.total': 'Tổng số',
      'lot.list.summary.active': 'Đang hoạt động',
      'lot.list.summary.withStock': 'Đang có hàng',
      'lot.create.title': 'Tạo lô hoặc số sê-ri',
      'lot.create.hint': 'Gắn định danh truy xuất với đúng sản phẩm trước khi nhận hàng vào kho.',
      'lot.create.product.help': 'Chỉ hiển thị các biến thể hàng hóa đang hoạt động và được lưu kho.',
      'lot.create.name.placeholder': 'Ví dụ: LOT-2026-008',
      'lot.list.records.title': 'Lô và số sê-ri đã cấu hình',
      'lot.list.records.hint': 'Tồn thực tế chỉ tính tại vị trí nội bộ và vị trí trung chuyển.',
      'lot.list.col.name': 'Lô / Sê-ri',
      'lot.list.col.product': 'Sản phẩm',
      'lot.list.col.reference': 'Tham chiếu nội bộ',
      'lot.list.col.onHand': 'Tồn thực tế',
      'lot.list.col.status': 'Trạng thái',
      'lot.list.empty': 'Chưa có lô hoặc số sê-ri',
      'lot.list.emptyHint': 'Tạo định danh đầu tiên để bắt đầu truy xuất hàng hóa.',
      'lot.kicker': 'Lô / Sê-ri',
      'lot.error.notFound': 'Không tìm thấy lô hoặc sê-ri trong công ty hiện tại.',
      'lot.collaboration.label': 'Trao đổi và hoạt động của lô hoặc sê-ri',
      'lot.status.active': 'Đang hoạt động',
      'lot.status.archived': 'Đã lưu trữ',
      'lot.summary.onHand': 'Tồn thực tế',
      'lot.summary.available': 'Có thể dùng',
      'lot.summary.locations': 'Vị trí',
      'lot.information.title': 'Thông tin',
      'lot.information.hint': 'Sản phẩm, số lô hoặc sê-ri, tham chiếu nội bộ và mô tả.',
      'lot.field.product': 'Sản phẩm',
      'lot.inventory.title': 'Tồn kho theo vị trí',
      'lot.inventory.hint': 'Số lượng thực tế, đã giữ và có thể dùng của riêng lô hoặc sê-ri này.',
      'lot.field.reference': 'Tham chiếu nội bộ',
      'lot.field.reference.help': 'Dùng khi mã nội bộ khác số lô hoặc sê-ri của nhà sản xuất.',
      'lot.field.description': 'Mô tả',
      'lot.col.location': 'Vị trí',
      'lot.col.onHand': 'Tồn thực tế',
      'lot.col.reserved': 'Đã giữ',
      'lot.col.available': 'Có thể dùng',
      'lot.empty': 'Lô hoặc sê-ri chưa có tồn kho',
      'lot.emptyHint': 'Tồn kho sẽ xuất hiện sau khi lô hoặc sê-ri được nhận vào một vị trí nội bộ.',
      lots: 'Lô / Sê-ri',
      replenishment: 'Bổ sung hàng',
      'replenishment.kicker': 'Quy tắc tái đặt hàng',
      'replenishment.title': 'Bổ sung hàng',
      'replenishment.subtitle': 'Theo dõi tồn dự báo và bổ sung hàng theo ngưỡng min/max.',
      'replenishment.summary.rules': 'Tổng quy tắc',
      'replenishment.summary.automatic': 'Tự động',
      'replenishment.summary.toOrder': 'Cần bổ sung',
      'replenishment.create.title': 'Tạo quy tắc tái đặt hàng',
      'replenishment.create.hint': 'Chọn sản phẩm lưu kho, vị trí và mức tồn tối thiểu/tối đa.',
      'replenishment.rules.title': 'Đề xuất bổ sung',
      'replenishment.rules.hint': 'Số lượng cần đặt được tính từ tồn dự báo tại vị trí của quy tắc.',
      'replenishment.col.product': 'Sản phẩm',
      'replenishment.col.forecasted': 'Dự báo',
      'replenishment.col.toOrder': 'Cần đặt',
      'replenishment.col.action': 'Thao tác',
      'replenishment.empty': 'Chưa có quy tắc tái đặt hàng',
      'replenishment.emptyHint': 'Tạo quy tắc đầu tiên để nhận đề xuất bổ sung hàng.',
      forecast: 'Dự báo tồn kho',
      transferDetail: 'Chi tiết dịch chuyển',
      'transfer.kicker': 'Dịch chuyển kho',
      'transfer.collaboration.label': 'Trao đổi và hoạt động của dịch chuyển',
      'transfer.actions.label': 'Hành động dịch chuyển',
      'transfer.summary.lines': 'Dòng thao tác',
      'transfer.operations.title': 'Dòng dịch chuyển',
      'transfer.operations.hint': 'Theo dõi nhu cầu, số lượng đã xử lý và trạng thái từng dòng.',
      'transfer.operations.empty': 'Chưa có dòng dịch chuyển',
      'transfer.operations.emptyHint': 'Thêm sản phẩm vào dịch chuyển để bắt đầu xử lý.',
      'transfer.addMove.title': 'Thêm sản phẩm',
      'transfer.addMove.hint': 'Khai báo sản phẩm, đơn vị và số lượng cần dịch chuyển.',
      'transfer.recordDone.title': 'Ghi nhận xử lý',
      'transfer.recordDone.hint': 'Nhập số lượng thực tế và lô hoặc sê-ri khi cần.',
      routeDetail: 'Quy tắc tuyến cung ứng',
      'col.name': 'Tên',
      'col.kind': 'Loại',
      'col.state': 'Trạng thái',
      'col.detail': 'Chi tiết',
      empty: 'Chưa có dữ liệu.',
      emptyHint: 'Tạo bản ghi đầu tiên để bắt đầu.',
      'error.invalid': 'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại.',
      'action.create': 'Tạo mới',
      'action.save': 'Lưu',
      'action.apply': 'Áp dụng kiểm kê',
      'action.addMove': 'Thêm dòng hàng',
      'action.confirm': 'Xác nhận',
      'action.assign': 'Giữ hàng',
      'action.validate': 'Hoàn tất',
      'action.validateCreateBackorder': 'Hoàn tất và tạo đơn bù',
      'action.validateNoBackorder': 'Hoàn tất, không tạo đơn bù',
      'action.recordDone': 'Ghi nhận đã xử lý',
      'action.cancel': 'Hủy',
      'action.addRule': 'Thêm quy tắc',
      'action.calculate': 'Tính dự báo',
      'action.run': 'Chạy bổ sung',
      'adjustment.title': 'Điều chỉnh tồn kho',
      'adjustment.hint': 'Chọn sản phẩm và vị trí, sau đó nhập số lượng đã đếm tại kho.',
      'field.product': 'Sản phẩm',
      'field.productId': 'ID biến thể',
      'field.location': 'Vị trí',
      'field.inventoryLocation': 'Vị trí kiểm kê',
      'field.uom': 'Đơn vị tính',
      'field.lot': 'Lô / Sê-ri',
      'field.counted': 'Số lượng đếm được',
      'field.reference': 'Tham chiếu',
      'field.operationType': 'Loại hoạt động',
      'field.scheduledDate': 'Ngày dự kiến',
      'field.demand': 'Nhu cầu',
      'field.operationLine': 'Dòng xử lý',
      'field.doneQuantity': 'Số lượng đã xử lý',
      'field.code': 'Mã',
      'field.receptionSteps': 'Các bước nhận hàng',
      'field.deliverySteps': 'Các bước giao hàng',
      'field.usage': 'Cách sử dụng',
      'field.warehouse': 'Kho hàng',
      'field.parentLocation': 'Vị trí cha',
      'field.sourceLocation': 'Vị trí nguồn',
      'field.destinationLocation': 'Vị trí đích',
      'field.backorder': 'Tạo backorder',
      'field.lotSerial': 'Số lô / sê-ri',
      'field.note': 'Ghi chú',
      'field.sequence': 'Thứ tự',
      'field.ruleAction': 'Hành động',
      'field.procureMethod': 'Phương thức cung ứng',
      'field.trigger': 'Kích hoạt',
      'field.minQuantity': 'Tồn tối thiểu',
      'field.maxQuantity': 'Tồn tối đa',
      'field.replenishmentUom': 'Đơn vị bổ sung',
      'field.route': 'Tuyến cung ứng',
      'forecast.onHand': 'Tồn thực tế',
      'forecast.reserved': 'Đã giữ chỗ',
      'forecast.available': 'Có thể sử dụng',
      'forecast.incoming': 'Sắp nhận',
      'forecast.outgoing': 'Sắp xuất',
      'forecast.value': 'Dự báo',
      'forecast.kicker': 'Báo cáo tồn dự báo',
      'forecast.title': 'Dự báo tồn kho',
      'forecast.subtitle': 'Chọn sản phẩm và phạm vi kho để xem khả năng đáp ứng dự kiến.',
      'forecast.summary.products': 'Sản phẩm lưu kho',
      'forecast.summary.warehouses': 'Kho hàng',
      'forecast.summary.locations': 'Vị trí',
      'forecast.filter.title': 'Phạm vi dự báo',
      'forecast.filter.hint': 'Vị trí được chọn sẽ ưu tiên hơn kho hàng.',
      'forecast.location.help': 'Để trống để tính toàn bộ kho đã chọn; chọn vị trí để thu hẹp phạm vi.',
      'forecast.result.title': 'Khả năng đáp ứng',
      'forecast.result.hint': 'Tồn thực tế + sắp nhận − sắp xuất = tồn dự báo.',
      'forecast.empty': 'Chưa chọn sản phẩm',
      'forecast.emptyHint': 'Chọn một sản phẩm lưu kho để tính tồn dự báo.',
      'forecast.scope.all': 'Tất cả vị trí nội bộ và trung chuyển có thể đọc.',
      'forecast.scope.warehouse': 'Kho: {name}',
      'forecast.scope.location': 'Vị trí: {name}',
      'state.draft': 'Nháp',
      'state.waiting': 'Đang chờ',
      'state.confirmed': 'Đã xác nhận',
      'state.partially_available': 'Có hàng một phần',
      'state.reserved': 'Đã giữ hàng',
      'state.assigned': 'Đã giữ hàng',
      'state.done': 'Hoàn tất',
      'state.cancel': 'Đã hủy',
      'kind.quant': 'Tồn theo vị trí',
      'kind.transfer': 'Dịch chuyển',
      'kind.move': 'Dòng dịch chuyển',
      'kind.move-line': 'Dòng thao tác',
      'kind.warehouse': 'Kho hàng',
      'kind.lot': 'Lô / Sê-ri',
      'kind.route': 'Tuyến cung ứng',
      'kind.internal': 'Nội bộ',
      'kind.view': 'Nhóm vị trí',
      'kind.supplier': 'Nhà cung cấp',
      'kind.customer': 'Khách hàng',
      'kind.inventory': 'Kiểm kê',
      'kind.production': 'Sản xuất',
      'kind.transit': 'Trung chuyển',
      'kind.incoming': 'Nhập kho',
      'kind.outgoing': 'Xuất kho',
      'kind.pull': 'Kéo hàng',
      'kind.push': 'Đẩy hàng',
      'kind.pull_push': 'Kéo và đẩy hàng',
      'kind.auto': 'Tự động',
      'kind.manual': 'Thủ công',
      'location.filter.stockHolding': 'Vị trí giữ hàng',
      'location.filter.counterparty': 'Vị trí đối tác',
      'location.filter.virtual': 'Vị trí ảo',
      'lot.filter.inStock': 'Còn tồn',
      'lot.filter.empty': 'Hết tồn',
      'stockRoute.filter.configured': 'Đã có quy tắc',
      'stockRoute.filter.unconfigured': 'Chưa có quy tắc',
      'replenishment.filter.toOrder': 'Cần đặt hàng',
      'replenishment.filter.covered': 'Đã đủ hàng',
      'warehouse.filter.stagedReception': 'Nhận hàng qua nhiều bước',
      'warehouse.filter.stagedDelivery': 'Giao hàng qua nhiều bước',
      'receptionSteps.one_step': 'Nhận hàng trực tiếp',
      'receptionSteps.two_steps': 'Nhập qua khu vực đầu vào',
      'receptionSteps.three_steps': 'Đầu vào, kiểm tra chất lượng, nhập kho',
      'deliverySteps.ship_only': 'Giao trực tiếp',
      'deliverySteps.pick_ship': 'Lấy hàng rồi giao',
      'deliverySteps.pick_pack_ship': 'Lấy hàng, đóng gói rồi giao',
      'usage.internal': 'Vị trí nội bộ',
      'usage.view': 'Nhóm vị trí',
      'usage.supplier': 'Vị trí nhà cung cấp',
      'usage.customer': 'Vị trí khách hàng',
      'usage.inventory': 'Vị trí kiểm kê',
      'usage.production': 'Vị trí sản xuất',
      'usage.transit': 'Vị trí trung chuyển',
      'pickingType.incoming': 'Nhập kho',
      'pickingType.outgoing': 'Xuất kho',
      'pickingType.internal': 'Điều chuyển nội bộ',
      'backorder.ask': 'Hỏi khi hoàn tất',
      'backorder.always': 'Luôn tạo backorder',
      'backorder.never': 'Không tạo backorder',
      'ruleAction.pull': 'Kéo hàng từ vị trí khác',
      'ruleAction.push': 'Đẩy hàng sang vị trí khác',
      'ruleAction.pull_push': 'Kéo và đẩy hàng',
      'procureMethod.make_to_stock': 'Lấy từ tồn kho',
      'procureMethod.make_to_order': 'Cung ứng theo nhu cầu',
      'procureMethod.mts_else_mto': 'Ưu tiên tồn kho, thiếu thì cung ứng',
      'trigger.auto': 'Tự động',
      'trigger.manual': 'Thủ công',
      'record.location.stock': 'Tồn kho',
      'record.location.input': 'Đầu vào',
      'record.location.quality': 'Kiểm tra chất lượng',
      'record.location.output': 'Đầu ra',
      'record.location.pick': 'Lấy hàng',
      'record.location.pack': 'Đóng gói',
      'record.location.supplier': 'Nhà cung cấp',
      'record.location.customer': 'Khách hàng',
      'record.pickingType.incoming': 'Nhập kho',
      'record.pickingType.outgoing': 'Xuất kho',
      'record.pickingType.internal': 'Điều chuyển nội bộ',
      'record.pickingType.quality': 'Kiểm tra chất lượng',
      'record.pickingType.store': 'Nhập kho nội bộ',
      'record.pickingType.pick': 'Lấy hàng',
      'record.pickingType.pack': 'Đóng gói',
      'record.pickingType.adjustment': 'Điều chỉnh kiểm kê',
    },
    en: {
      'overview.title': 'Inventory overview',
      'overview.queue': 'Transfers to process',
      'overview.empty': 'No stock transfers are waiting to be processed.',
      'modal.edit': 'Edit',
      'modal.relatedOperations': 'Delivery and history',
      'modal.information': 'Information',
      'modal.products': 'Products',
      'modal.demand': 'Demand',
      'modal.picked': 'Picked',
      'modal.recordPicked': 'Record picked quantity',
      'modal.quantity': 'Quantity',
      'modal.yes': 'Yes',
      'modal.no': 'No',
      'modal.remaining': 'Remaining quantities',
      'modal.confirmCancel': 'Cancel this transfer?',

      'modal.confirmRun': 'Run replenishment using this rule?',
      'count.preview': 'Preview difference',
      'count.previewTitle': 'No changes applied yet',
      'count.previewHint': 'Review the difference before applying. Reservations stay unchanged.',
      'count.difference': 'Difference',
      'count.reason': 'Count reason',
      'count.unitHint': 'Enter the quantity in the product stock unit.',
      'app.title': 'Inventory in admin',
      'app.summary': 'Manage multiple warehouses, stock, transfers, and procurement rules.',
      'app.category': 'System',
      'menu.app': 'Inventory',
      'menu.operations': 'Operations',
      'menu.transfers': 'Transfers',
      'menu.inventory': 'Stock',
      'menu.forecast': 'Forecast',
      'menu.replenishment': 'Replenishment',
      'menu.config': 'Configuration',
      'menu.warehouses': 'Warehouses',
      'menu.locations': 'Locations',
      'menu.pickingTypes': 'Operation types',
      'menu.lots': 'Lots / Serials',
      'menu.routes': 'Routes',
      inventory: 'Inventory',
      'inventory.kicker': 'Inventory operations',
      'inventory.workspace.title': 'Physical inventory',
      'inventory.workspace.subtitle': 'Reconcile counted quantities with the system inventory.',
      'inventory.summary.onHand': 'Total on hand',
      'inventory.summary.balances': 'Stock balances',
      'inventory.summary.locations': 'Stock locations',
      'inventory.applied.title': 'Inventory count applied',
      'inventory.applied.message': 'The difference was recorded through an inventory transfer.',
      'inventory.configuration.title': 'Inventory configuration is incomplete',
      'inventory.configuration.message':
        'A product, unit, internal location, and inventory adjustment location are required before recording a count.',
      'inventory.configuration.action': 'Open location settings',
      'inventory.adjustmentLocation.help': 'Virtual location used to record the inventory difference.',
      'inventory.balances.title': 'Current inventory',
      'inventory.balances.hint': 'Review on-hand, reserved, and available quantities by location.',
      'inventory.empty': 'No stock in an internal location',
      'inventory.emptyHint': 'Record the first count to create an inventory balance.',
      'inventory.col.product': 'Product',
      'inventory.col.reference': 'Internal reference',
      'inventory.col.location': 'Location',
      'inventory.col.lot': 'Lot / Serial',
      'inventory.col.onHand': 'On hand',
      'inventory.col.reserved': 'Reserved',
      'inventory.col.available': 'Available',
      transfers: 'Transfers',
      'transfer.list.kicker': 'Inventory operations',
      'transfer.list.title': 'Transfers',
      'transfer.list.subtitle': 'Review receipts, deliveries, and internal transfers in one place.',
      'transfer.list.summary.open': 'Open',
      'transfer.list.summary.ready': 'Ready',
      'transfer.list.summary.done': 'Done',
      'transfer.create.title': 'Create transfer',
      'transfer.create.hint':
        'Choose an operation type; source and destination come from its warehouse settings.',
      'transfer.create.reference.help': 'Operational reference used to identify this transfer.',
      'transfer.list.records.title': 'Transfers',
      'transfer.list.records.hint': 'Core operational fields for stock transfers.',
      'transfer.list.col.reference': 'Reference',
      'transfer.list.col.source': 'From',
      'transfer.list.col.destination': 'To',
      'transfer.list.col.scheduledDate': 'Scheduled date',
      'transfer.list.col.operationType': 'Operation type',
      'transfer.list.col.state': 'Status',
      'transfer.list.empty': 'No transfers yet',
      'transfer.list.emptyHint': 'Create the first transfer to begin moving stock.',
      warehouses: 'Warehouses',
      'warehouse.kicker': 'Inventory configuration',
      'warehouse.title': 'Warehouses',
      'warehouse.subtitle': 'Define physical warehouses and each warehouse receipt and delivery flow.',
      'warehouse.summary.total': 'Active warehouses',
      'warehouse.summary.receipts': 'Multi-step receipts',
      'warehouse.summary.deliveries': 'Multi-step deliveries',
      'warehouse.create.title': 'Create warehouse',
      'warehouse.create.hint':
        'Default locations, operation types, and routes are generated from this configuration.',
      'warehouse.configured.title': 'Configured warehouses',
      'warehouse.configured.hint': 'Review each warehouse short name and stock flow.',
      'warehouse.field.name': 'Warehouse name',
      'warehouse.field.name.placeholder': 'e.g. Central Warehouse',
      'warehouse.field.code': 'Short name',
      'warehouse.field.code.placeholder': 'e.g. CW',
      'warehouse.field.code.help': 'Company-unique short code used as the operational prefix.',
      'warehouse.col.name': 'Warehouse',
      'warehouse.col.code': 'Short name',
      'warehouse.col.reception': 'Incoming shipments',
      'warehouse.col.delivery': 'Outgoing shipments',
      'warehouse.col.locations': 'Locations',
      'warehouse.col.transfers': 'Transfers',
      'warehouse.empty': 'No warehouses yet',
      'warehouse.emptyHint':
        'Create the first warehouse to generate its default locations and operation types.',
      routes: 'Routes',
      'stockRoute.list.kicker': 'Supply configuration',
      'stockRoute.list.title': 'Inventory routes',
      'stockRoute.list.subtitle':
        'Define the ordered flows products follow through warehouses and locations.',
      'stockRoute.list.summary.total': 'Total routes',
      'stockRoute.list.summary.configured': 'With rules',
      'stockRoute.list.summary.rules': 'Total rules',
      'stockRoute.create.title': 'Create inventory route',
      'stockRoute.create.hint': 'Create the route first, then configure its pull and push rules.',
      'stockRoute.field.name': 'Route name',
      'stockRoute.field.name.placeholder': 'e.g. Two-step receipts',
      'stockRoute.field.sequence.help': 'A lower number takes priority when several routes apply.',
      'stockRoute.list.records.title': 'Configured inventory routes',
      'stockRoute.list.records.hint': 'Stock routes in priority order.',
      'stockRoute.list.col.name': 'Inventory route',
      'stockRoute.list.col.sequence': 'Sequence',
      'stockRoute.list.col.rules': 'Rules',
      'stockRoute.list.col.sources': 'Source locations',
      'stockRoute.list.col.destinations': 'Destination locations',
      'stockRoute.list.col.actions': 'Movement methods',
      'stockRoute.list.empty': 'No inventory routes yet',
      'stockRoute.list.emptyHint': 'Create the first route to describe a product flow through inventory.',
      'stockRoute.detail.kicker': 'Inventory route',
      'stockRoute.status.active': 'Active',
      'stockRoute.status.archived': 'Archived',
      'stockRoute.detail.summary.rules': 'Total rules',
      'stockRoute.detail.summary.pull': 'Pull rules',
      'stockRoute.detail.summary.push': 'Push rules',
      'stockRoute.detail.information.title': 'Route information',
      'stockRoute.detail.information.hint': 'The route name and its priority during procurement.',
      'stockRoute.detail.rules.title': 'Configured rules',
      'stockRoute.detail.rules.hint': 'Pull and push steps are applied in sequence order.',
      'stockRoute.rule.col.name': 'Rule',
      'stockRoute.rule.empty': 'No rules yet',
      'stockRoute.rule.emptyHint': 'Add the first rule so this route can direct a product flow.',
      'stockRoute.rule.create.title': 'Add rule',
      'stockRoute.rule.create.hint': 'Choose the action, locations and operation type for the next step.',
      'stockRoute.rule.name.placeholder': 'e.g. Pull goods to input',
      'record.receiptRule.supplier-stock': 'Receive in stock',
      'record.receiptRule.supplier-input': 'Receive in input',
      'record.receiptRule.input-stock': 'Input to stock',
      'record.receiptRule.input-quality': 'Input to quality control',
      'record.receiptRule.quality-stock': 'Quality control to stock',
      'record.deliveryRule.stock-customer': 'Deliver directly from stock',
      'record.deliveryRule.stock-output': 'Pick to output',
      'record.deliveryRule.stock-pack': 'Pick to packing',
      'record.deliveryRule.pack-output': 'Packing to output',
      'record.deliveryRule.output-customer': 'Deliver from output to customer',
      locations: 'Locations',
      'location.kicker': 'Inventory configuration',
      'location.title': 'Locations',
      'location.subtitle':
        'Model physical warehouse structure, partner locations, and virtual inventory counterparts.',
      'location.summary.internal': 'Internal locations',
      'location.summary.views': 'Location groups',
      'location.summary.warehouses': 'Linked warehouses',
      'location.create.title': 'Create location',
      'location.create.hint':
        'Place the location in the warehouse tree and choose the usage used by stock moves.',
      'location.configured.title': 'Location tree',
      'location.configured.hint': 'Complete name, location type, and linked warehouse.',
      'location.field.name': 'Location name',
      'location.field.name.placeholder': 'e.g. Shelf A-01',
      'location.field.usage.help':
        'Location type determines how quantities contribute to forecast and on-hand stock.',
      'location.field.warehouse.help': 'Choose a warehouse only when this location belongs to its structure.',
      'location.col.location': 'Location',
      'location.col.usage': 'Location type',
      'location.col.warehouse': 'Warehouse',
      'location.col.parent': 'Parent location',
      'location.col.products': 'Products in stock',
      'location.empty': 'No locations yet',
      'location.emptyHint': 'Create a warehouse or the first location to begin its location tree.',
      pickingTypes: 'Operation types',
      'pickingType.kicker': 'Inventory configuration',
      'pickingType.title': 'Operation types',
      'pickingType.subtitle':
        'Configure default receipt, delivery, and internal transfer flows per warehouse.',
      'pickingType.summary.incoming': 'Receipt flows',
      'pickingType.summary.outgoing': 'Delivery flows',
      'pickingType.summary.internal': 'Internal flows',
      'pickingType.create.title': 'Create operation type',
      'pickingType.create.hint': 'Choose the warehouse, flow type, default locations, and backorder policy.',
      'pickingType.configured.title': 'Configured operation types',
      'pickingType.configured.hint': 'Core receipt, delivery, and internal-transfer flows.',
      'pickingType.field.name': 'Operation type name',
      'pickingType.field.name.placeholder': 'e.g. Store receipts',
      'pickingType.field.code': 'Type of operation',
      'pickingType.field.backorder.help':
        'How remaining quantities are handled after partially validating a transfer.',
      'pickingType.col.name': 'Operation type',
      'pickingType.col.code': 'Type of operation',
      'pickingType.col.warehouse': 'Warehouse',
      'pickingType.col.route': 'Default locations',
      'pickingType.col.backorder': 'Backorder',
      'pickingType.empty': 'No operation types yet',
      'pickingType.emptyHint': 'Create a warehouse or the first operation type to begin moving stock.',
      'lot.list.kicker': 'Inventory traceability',
      'lot.list.title': 'Lots and serial numbers',
      'lot.list.subtitle': 'Review each lot or serial identity, product, and current on-hand stock.',
      'lot.list.summary.total': 'Total',
      'lot.list.summary.active': 'Active',
      'lot.list.summary.withStock': 'With stock',
      'lot.create.title': 'Create lot or serial number',
      'lot.create.hint': 'Bind the traceability identity to the correct product before receiving stock.',
      'lot.create.product.help': 'Only active, storable product variants are available.',
      'lot.create.name.placeholder': 'e.g. LOT-2026-008',
      'lot.list.records.title': 'Configured lots and serial numbers',
      'lot.list.records.hint': 'On-hand stock includes internal and transit locations only.',
      'lot.list.col.name': 'Lot / Serial',
      'lot.list.col.product': 'Product',
      'lot.list.col.reference': 'Internal reference',
      'lot.list.col.onHand': 'On hand',
      'lot.list.col.status': 'Status',
      'lot.list.empty': 'No lots or serial numbers yet',
      'lot.list.emptyHint': 'Create the first identity to begin tracing inventory.',
      'lot.kicker': 'Lot / Serial',
      'lot.error.notFound': 'The lot or serial was not found in the current company.',
      'lot.collaboration.label': 'Lot or serial conversation and activities',
      'lot.status.active': 'Active',
      'lot.status.archived': 'Archived',
      'lot.summary.onHand': 'On hand',
      'lot.summary.available': 'Available',
      'lot.summary.locations': 'Locations',
      'lot.information.title': 'Information',
      'lot.information.hint': 'Product, lot or serial number, internal reference, and description.',
      'lot.field.product': 'Product',
      'lot.inventory.title': 'Inventory by location',
      'lot.inventory.hint': 'On-hand, reserved, and available quantities for this lot or serial only.',
      'lot.field.reference': 'Internal reference',
      'lot.field.reference.help':
        'Use when the internal reference differs from the manufacturer lot or serial number.',
      'lot.field.description': 'Description',
      'lot.col.location': 'Location',
      'lot.col.onHand': 'On hand',
      'lot.col.reserved': 'Reserved',
      'lot.col.available': 'Available',
      'lot.empty': 'No inventory for this lot or serial',
      'lot.emptyHint': 'Inventory appears after the lot or serial is received into an internal location.',
      lots: 'Lots / Serials',
      replenishment: 'Replenishment',
      'replenishment.kicker': 'Reordering rules',
      'replenishment.title': 'Replenishment',
      'replenishment.subtitle': 'Track forecast stock and replenish from min/max thresholds.',
      'replenishment.summary.rules': 'Total rules',
      'replenishment.summary.automatic': 'Automatic',
      'replenishment.summary.toOrder': 'To replenish',
      'replenishment.create.title': 'Create reordering rule',
      'replenishment.create.hint': 'Choose a storable product, location and minimum/maximum stock.',
      'replenishment.rules.title': 'Replenishment suggestions',
      'replenishment.rules.hint': 'Quantity to order is calculated from forecast stock at the rule location.',
      'replenishment.col.product': 'Product',
      'replenishment.col.forecasted': 'Forecast',
      'replenishment.col.toOrder': 'To order',
      'replenishment.col.action': 'Action',
      'replenishment.empty': 'No reordering rules yet',
      'replenishment.emptyHint': 'Create the first rule to receive replenishment suggestions.',
      forecast: 'Stock forecast',
      transferDetail: 'Transfer details',
      'transfer.kicker': 'Inventory transfer',
      'transfer.collaboration.label': 'Transfer conversation and activities',
      'transfer.actions.label': 'Transfer actions',
      'transfer.summary.lines': 'Operation lines',
      'transfer.operations.title': 'Stock moves',
      'transfer.operations.hint': 'Review demand, completed quantities, and each line state.',
      'transfer.operations.empty': 'No stock moves yet',
      'transfer.operations.emptyHint': 'Add a product to begin processing this transfer.',
      'transfer.addMove.title': 'Add product',
      'transfer.addMove.hint': 'Set the product, unit, and quantity to move.',
      'transfer.recordDone.title': 'Record processing',
      'transfer.recordDone.hint': 'Enter the completed quantity and a lot or serial when required.',
      routeDetail: 'Route rules',
      'col.name': 'Name',
      'col.kind': 'Kind',
      'col.state': 'State',
      'col.detail': 'Detail',
      empty: 'No data yet.',
      emptyHint: 'Create the first record to begin.',
      'error.invalid': 'The submitted data is invalid. Please review it.',
      'action.create': 'Create',
      'action.save': 'Save',
      'action.apply': 'Apply inventory adjustment',
      'action.addMove': 'Add product line',
      'action.confirm': 'Confirm',
      'action.assign': 'Reserve',
      'action.validate': 'Validate',
      'action.validateCreateBackorder': 'Validate and create backorder',
      'action.validateNoBackorder': 'Validate without backorder',
      'action.recordDone': 'Record completed quantity',
      'action.cancel': 'Cancel',
      'action.addRule': 'Add rule',
      'action.calculate': 'Calculate forecast',
      'action.run': 'Run replenishment',
      'adjustment.title': 'Inventory adjustment',
      'adjustment.hint': 'Choose a product and location, then enter the quantity counted in the warehouse.',
      'field.product': 'Product',
      'field.productId': 'Variant ID',
      'field.location': 'Location',
      'field.inventoryLocation': 'Inventory location',
      'field.uom': 'Unit of measure',
      'field.lot': 'Lot / Serial',
      'field.counted': 'Counted quantity',
      'field.reference': 'Reference',
      'field.operationType': 'Operation type',
      'field.scheduledDate': 'Scheduled date',
      'field.demand': 'Demand',
      'field.operationLine': 'Operation line',
      'field.doneQuantity': 'Completed quantity',
      'field.code': 'Code',
      'field.receptionSteps': 'Receipt steps',
      'field.deliverySteps': 'Delivery steps',
      'field.usage': 'Usage',
      'field.warehouse': 'Warehouse',
      'field.parentLocation': 'Parent location',
      'field.sourceLocation': 'Source location',
      'field.destinationLocation': 'Destination location',
      'field.backorder': 'Create backorder',
      'field.lotSerial': 'Lot / Serial number',
      'field.note': 'Note',
      'field.sequence': 'Sequence',
      'field.ruleAction': 'Action',
      'field.procureMethod': 'Procurement method',
      'field.trigger': 'Trigger',
      'field.minQuantity': 'Minimum quantity',
      'field.maxQuantity': 'Maximum quantity',
      'field.replenishmentUom': 'Replenishment unit',
      'field.route': 'Route',
      'forecast.onHand': 'On hand',
      'forecast.reserved': 'Reserved',
      'forecast.available': 'Available',
      'forecast.incoming': 'Incoming',
      'forecast.outgoing': 'Outgoing',
      'forecast.value': 'Forecasted',
      'forecast.kicker': 'Forecasted report',
      'forecast.title': 'Stock forecast',
      'forecast.subtitle': 'Choose a product and inventory scope to review expected availability.',
      'forecast.summary.products': 'Storable products',
      'forecast.summary.warehouses': 'Warehouses',
      'forecast.summary.locations': 'Locations',
      'forecast.filter.title': 'Forecast scope',
      'forecast.filter.hint': 'A selected location takes precedence over the warehouse.',
      'forecast.location.help':
        'Leave blank for the selected warehouse, or choose a location to narrow the scope.',
      'forecast.result.title': 'Availability',
      'forecast.result.hint': 'On hand + incoming − outgoing = forecasted inventory.',
      'forecast.empty': 'No product selected',
      'forecast.emptyHint': 'Choose a storable product to calculate its forecast.',
      'forecast.scope.all': 'All readable internal and transit locations.',
      'forecast.scope.warehouse': 'Warehouse: {name}',
      'forecast.scope.location': 'Location: {name}',
      'state.draft': 'Draft',
      'state.waiting': 'Waiting',
      'state.confirmed': 'Confirmed',
      'state.partially_available': 'Partially available',
      'state.reserved': 'Reserved',
      'state.assigned': 'Ready',
      'state.done': 'Done',
      'state.cancel': 'Cancelled',
      'kind.quant': 'Stock by location',
      'kind.transfer': 'Transfer',
      'kind.move': 'Stock move',
      'kind.move-line': 'Operation line',
      'kind.warehouse': 'Warehouse',
      'kind.lot': 'Lot / Serial',
      'kind.route': 'Route',
      'kind.internal': 'Internal',
      'kind.view': 'Location group',
      'kind.supplier': 'Vendor',
      'kind.customer': 'Customer',
      'kind.inventory': 'Inventory loss',
      'kind.production': 'Production',
      'kind.transit': 'Transit',
      'kind.incoming': 'Receipt',
      'kind.outgoing': 'Delivery',
      'kind.pull': 'Pull',
      'kind.push': 'Push',
      'kind.pull_push': 'Pull and push',
      'kind.auto': 'Automatic',
      'kind.manual': 'Manual',
      'location.filter.stockHolding': 'Stock-holding locations',
      'location.filter.counterparty': 'Counterparty locations',
      'location.filter.virtual': 'Virtual locations',
      'lot.filter.inStock': 'In stock',
      'lot.filter.empty': 'Out of stock',
      'stockRoute.filter.configured': 'Has rules',
      'stockRoute.filter.unconfigured': 'No rules',
      'replenishment.filter.toOrder': 'To order',
      'replenishment.filter.covered': 'Covered',
      'warehouse.filter.stagedReception': 'Staged reception',
      'warehouse.filter.stagedDelivery': 'Staged delivery',
      'receptionSteps.one_step': 'Receive goods directly',
      'receptionSteps.two_steps': 'Receive goods in input and then stock',
      'receptionSteps.three_steps': 'Input, quality, then stock',
      'deliverySteps.ship_only': 'Deliver goods directly',
      'deliverySteps.pick_ship': 'Pick then deliver',
      'deliverySteps.pick_pack_ship': 'Pick, pack, then deliver',
      'usage.internal': 'Internal location',
      'usage.view': 'Location group',
      'usage.supplier': 'Vendor location',
      'usage.customer': 'Customer location',
      'usage.inventory': 'Inventory loss location',
      'usage.production': 'Production location',
      'usage.transit': 'Transit location',
      'pickingType.incoming': 'Receipt',
      'pickingType.outgoing': 'Delivery',
      'pickingType.internal': 'Internal transfer',
      'backorder.ask': 'Ask when validating',
      'backorder.always': 'Always create a backorder',
      'backorder.never': 'Never create a backorder',
      'ruleAction.pull': 'Pull from another location',
      'ruleAction.push': 'Push to another location',
      'ruleAction.pull_push': 'Pull and push',
      'procureMethod.make_to_stock': 'Take from stock',
      'procureMethod.make_to_order': 'Trigger another rule',
      'procureMethod.mts_else_mto': 'Use stock, trigger rule for the rest',
      'trigger.auto': 'Automatic',
      'trigger.manual': 'Manual',
      'record.location.stock': 'Stock',
      'record.location.input': 'Input',
      'record.location.quality': 'Quality',
      'record.location.output': 'Output',
      'record.location.pick': 'Pick',
      'record.location.pack': 'Pack',
      'record.location.supplier': 'Vendor',
      'record.location.customer': 'Customer',
      'record.pickingType.incoming': 'Receipts',
      'record.pickingType.outgoing': 'Delivery Orders',
      'record.pickingType.internal': 'Internal Transfers',
      'record.pickingType.quality': 'Quality Control',
      'record.pickingType.store': 'Store',
      'record.pickingType.pick': 'Pick',
      'record.pickingType.pack': 'Pack',
      'record.pickingType.adjustment': 'Inventory Adjustments',
    },
  },
  fills: {
    'backend:runtime': `{% island "stock.transfer-modal" %}{% island "stock.lot-modal" %}{% island "stock.route-modal" %}{% island "stock.replenishment-modal" %}{% island "stock.count-modal" %}{% island "stock.warehouse-modal" %}{% island "stock.location-modal" %}{% island "stock.picking-type-modal" %}`,
    'stock_backend:picking.editor': `{% island "stock.editor" %}`,
    'stock_backend:lot.editor': `{% island "stock.editor" %}`,
  },
})
