// Synthetic fixture data. No imports from here may enter the product client.
export const createData = () => ({
  user: { id: 'mai', name: 'Mai Anh' },
  company: { id: 'demo', name: 'Két Việt · Product studio' },
  columns: [
    { id: 'todo', labelKey: 'flow.ui.to.do', label: 'Chờ nhận', kind: 'todo' },
    { id: 'progress', labelKey: 'flow.ui.in.progress', label: 'Đang thực hiện', kind: 'progress' },
    { id: 'review', labelKey: 'flow.ui.awaiting.acceptance.9782f0', label: 'Chờ nghiệm thu', kind: 'review' },
    { id: 'done', labelKey: 'flow.ui.done', label: 'Hoàn thành', kind: 'done' },
  ],
  types: [
    { id: 'story', title: 'Story' },
    { id: 'bug', title: 'Bug' },
    { id: 'task', title: 'Task' },
  ],
  fields: [
    { id: 'env', title: 'Môi trường', description: 'Lựa chọn · Production / Staging' },
    { id: 'version', title: 'Phiên bản', description: 'Văn bản' },
  ],
  members: [
    { id: 'mai', name: 'Mai Anh', status: 'active' },
    { id: 'bao', name: 'Trần Quốc Bảo', status: 'active' },
    { id: 'ha', name: 'Lê Thu Hà', status: 'active' },
  ],
  people: ['Mai Anh', 'Trần Quốc Bảo', 'Lê Thu Hà'],
  projects: [
    {
      id: 'core',
      members: ['Mai Anh', 'Trần Quốc Bảo'],
      title: 'KetSuite Core',
      code: 'KV',
      description: 'Một nền tảng vận hành. Một trải nghiệm liền mạch.',
      progress: 64,
    },
    {
      id: 'ops',
      members: ['Mai Anh', 'Lê Thu Hà'],
      title: 'Vận hành nội bộ',
      code: 'OPS',
      description: 'Chuẩn hóa quy trình và nâng chất lượng bàn giao.',
      progress: 42,
    },
    {
      id: 'docs',
      members: ['Lê Thu Hà'],
      title: 'Tài liệu khách hàng',
      code: 'DOC',
      description: 'Giúp mỗi người dùng tìm được câu trả lời.',
      progress: 78,
    },
  ],
  tasks: [
    [
      'KV-142',
      'Đồng bộ tồn phòng giữa hai nguồn',
      'progress',
      'high',
      'Mai Anh',
      '24/09',
      'core',
      5,
      ['KV-144'],
    ],
    ['KV-131', 'Kiểm tra ràng buộc tồn phòng', 'progress', 'urgent', 'Mai Anh', '19/09', 'core', 3, []],
    ['KV-147', 'Chuẩn hóa thông điệp lỗi tiếng Việt', 'todo', 'normal', 'Lê Thu Hà', '26/09', 'core', 2, []],
    ['KV-150', 'Rà soát quyền cho nhóm lễ tân', 'review', 'high', 'Mai Anh', '25/09', 'core', 3, []],
    ['KV-139', 'Cập nhật hướng dẫn bàn giao', 'done', 'normal', 'Mai Anh', '20/09', 'docs', 2, []],
    [
      'KV-144',
      'Chuyển đổi bảng giá sang cấu trúc mới',
      'progress',
      'high',
      'Trần Quốc Bảo',
      '23/09',
      'core',
      8,
      [],
    ],
    ['KV-145', 'Kiểm tra vòng lặp phụ thuộc', 'review', 'normal', 'Lê Thu Hà', '24/09', 'core', 3, []],
    ['KV-129', 'Viết lại quy trình bàn giao ca', 'todo', 'urgent', 'Mai Anh', '20/09', 'ops', 5, []],
    ['KV-151', 'Chuẩn bị dữ liệu mẫu cho demo', 'todo', 'normal', 'Trần Quốc Bảo', '28/09', 'core', 2, []],
    ['KV-153', 'Dọn dữ liệu thử nghiệm', 'todo', 'normal', 'Lê Thu Hà', '29/09', 'ops', 1, []],
    ['KV-155', 'Viết truy vấn đối chiếu hai nguồn', 'done', 'normal', 'Mai Anh', '21/09', 'core', 2, []],
    ['KV-156', 'Bổ sung kiểm tra khi ghi', 'done', 'normal', 'Trần Quốc Bảo', '22/09', 'core', 3, []],
  ].map(([id, title, status, priority, assignee, due, projectId, points, blockedBy], i) => ({
    id,
    title,
    status,
    priority,
    assignee,
    due,
    projectId,
    points,
    blockedBy,
    version: 1,
    order: i,
    sprint: 'Sprint 12',
    epic: 'Kết nối kênh bán',
    archived: false,
    followed: i === 0,
    tags: i === 0 ? ['tech', 'risk'] : [],
    description:
      'Đối chiếu hai nguồn dữ liệu và thống nhất quy tắc ghi nhận.\n\nTiêu chí nghiệm thu:\n• Có kiểm tra cho trường hợp đồng thời.\n• Ghi lại kết quả vào tài liệu bàn giao.',
    dueDate: `2026-${due.slice(3, 5)}-${due.slice(0, 2)}`,
    startDate: {
      'KV-142': '2026-09-18',
      'KV-131': '2026-09-15',
      'KV-147': '2026-09-21',
      'KV-150': '2026-09-22',
      'KV-139': '2026-09-17',
      'KV-144': '2026-09-20',
      'KV-145': '2026-09-21',
      'KV-129': '2026-09-16',
      'KV-151': '2026-09-24',
      'KV-153': '2026-09-23',
      'KV-155': '2026-09-18',
      'KV-156': '2026-09-19',
    }[id],
    parentId: i > 9 ? 'KV-142' : null,
  })),
  pages: [
    {
      id: 'workspace-guide',
      title: 'Hướng dẫn làm việc chung',
      projectId: null,
      parentId: null,
      visibility: 'shared',
      content: 'Quy ước cộng tác áp dụng cho toàn không gian.',
    },
    {
      id: 'ops-handbook',
      title: 'Sổ tay vận hành',
      projectId: 'ops',
      parentId: null,
      visibility: 'shared',
      content: 'Quy trình vận hành và bàn giao của nhóm nội bộ.',
    },
    {
      id: 'handoff',
      title: 'Quy ước bàn giao',
      blocks: [
        { id: 'overview', type: 'heading', text: 'Tổng quan phát hành' },
        {
          id: 'release-info',
          type: 'table',
          rows: [
            ['Phiên bản', 'Flow 1.1 · Không gian làm việc mới'],
            ['Ngày phát hành', '30 tháng 9, 2026 · 14:00–15:00 (GMT+7)'],
            ['Phụ trách', 'Mai Anh · Product / Quốc Bảo · Engineering'],
            ['Trạng thái', 'Đang chuẩn bị'],
            ['Công việc liên quan', 'KV-142 · Đồng bộ tồn phòng giữa hai nguồn'],
          ],
        },
        { id: 'scope', type: 'heading', text: 'Phạm vi phát hành' },
        {
          id: 'scope-note',
          type: 'paragraph',
          text: 'Thống nhất một nơi để nhóm theo dõi công việc, lưu lại quyết định và bàn giao đầy đủ bối cảnh.',
        },
        {
          id: 'scope-table',
          type: 'table',
          rows: [
            ['Hạng mục', 'Kết quả mong đợi'],
            ['Không gian Flow', 'Bảng, danh sách và view cá nhân nhất quán'],
            ['Tài liệu cộng tác', 'Cấu trúc rõ ràng, tìm kiếm nhanh và gắn với công việc'],
          ],
        },
        { id: 'divider-1', type: 'divider' },
        { id: 'agreement', type: 'heading', text: '1. Thống nhất kế hoạch' },
        {
          id: 'agreement-note',
          type: 'paragraph',
          text: 'Xác nhận thời điểm phát hành và người chịu trách nhiệm với các bên liên quan.',
        },
        {
          id: 'check-pm',
          type: 'check',
          text: 'Product đã duyệt phạm vi và tiêu chí nghiệm thu',
          checked: true,
        },
        {
          id: 'check-eng',
          type: 'check',
          text: 'Engineering xác nhận kế hoạch triển khai',
          checked: true,
        },
        {
          id: 'check-ops',
          type: 'check',
          text: 'Vận hành đã nhận hướng dẫn và lịch thông báo',
          checked: false,
        },
        { id: 'testing', type: 'heading', text: '2. Kiểm thử tính năng' },
        {
          id: 'testing-note',
          type: 'paragraph',
          text: 'Kiểm tra luồng chính, quyền truy cập và khả năng phục hồi. Mỗi vấn đề cần có công việc theo dõi và người phụ trách.',
        },
        {
          id: 'check-browser',
          type: 'check',
          text: 'Kiểm tra desktop, mobile và chế độ tối',
          checked: false,
        },
        {
          id: 'check-data',
          type: 'check',
          text: 'Đối chiếu dữ liệu sau chuyển đổi',
          checked: false,
        },
        { id: 'pre-release', type: 'heading', text: '3. Checklist trước phát hành' },
        { id: 'environment', type: 'subheading', text: '3.1 Chuẩn bị môi trường' },
        {
          id: 'environment-note',
          type: 'paragraph',
          text: 'Xác nhận cấu hình, bản sao lưu và phương án quay lại phiên bản trước.',
        },
        { id: 'check-backup', type: 'check', text: 'Bản sao lưu đã được kiểm tra', checked: false },
        { id: 'communication', type: 'subheading', text: '3.2 Thông báo cho nhóm' },
        {
          id: 'communication-note',
          type: 'paragraph',
          text: 'Thông báo phạm vi, thời điểm và đầu mối hỗ trợ. Gắn liên kết tài liệu này vào công việc phát hành.',
        },
        { id: 'execution', type: 'heading', text: '4. Thực hiện phát hành' },
        {
          id: 'execution-note',
          type: 'paragraph',
          text: 'Triển khai theo kế hoạch, theo dõi tín hiệu vận hành và cập nhật tiến độ cho nhóm.',
        },
        { id: 'post-release', type: 'heading', text: '5. Sau phát hành' },
        {
          id: 'check-monitor',
          type: 'check',
          text: 'Theo dõi kết quả và ghi lại bài học cho lần tiếp theo',
          checked: false,
        },
      ],
      projectId: 'core',
      parentId: null,
      content:
        'Mỗi thay đổi cần có người chịu trách nhiệm và tiêu chí nghiệm thu rõ ràng.\n\nTrước khi bàn giao\n1. Kiểm tra luồng chính và tình huống lỗi.\n2. Cập nhật tài liệu liên quan.\n3. Gắn công việc với bản phát hành.',
      version: 1,
    },
    {
      id: 'checklist',
      title: 'Phiên bản 1.1',
      projectId: 'core',
      parentId: 'handoff',
      content: 'Kiểm tra quyền truy cập, dữ liệu và khả năng phục hồi.',
      version: 1,
    },
    {
      id: 'onboarding',
      title: 'Hướng dẫn thành viên mới',
      projectId: 'docs',
      parentId: null,
      content: 'Chào mừng bạn đến với nhóm. Bắt đầu từ Việc của tôi.',
      version: 1,
    },
    {
      id: 'release-copy',
      title: 'Phiên bản 1.1 · Ghi chú',
      projectId: 'core',
      parentId: 'handoff',
      content: 'Ghi lại các quyết định trong quá trình phát hành.',
      version: 1,
    },
    {
      id: 'release-next',
      title: 'Phiên bản 1.2',
      projectId: 'core',
      parentId: 'handoff',
      content: 'Phạm vi cho phiên bản tiếp theo sẽ được thống nhất sau buổi tổng kết.',
      version: 1,
    },
    {
      id: 'meeting',
      title: 'Nhật ký họp nhóm',
      projectId: 'core',
      parentId: null,
      content: 'Quyết định và các bước tiếp theo của nhóm.',
      version: 1,
    },
    {
      id: 'private-notes',
      title: 'Ghi chú cá nhân',
      visibility: 'private',
      projectId: 'core',
      parentId: null,
      content: 'Không gian để chuẩn bị ý tưởng trước khi chia sẻ với nhóm.',
      version: 1,
    },
  ],
  comments: [
    {
      id: 'c1',
      taskId: 'KV-142',
      person: 'Lê Thu Hà',
      text: 'Hai nguồn lệch nhau ở khoảng 18–20/09. Đã ghi lại truy vấn đối chiếu.',
      time: '21/09 · 09:42',
    },
    {
      id: 'c2',
      taskId: 'KV-142',
      person: 'Mai Anh',
      text: 'Bắt đầu từ phía ghi nhận; phía đọc để sau.',
      time: '21/09 · 09:50',
    },
  ],
  sprints: [
    {
      id: 's12',
      title: 'Sprint 12',
      description: 'Ổn định luồng đồng bộ và hoàn thiện trải nghiệm quản lý công việc.',
      start: '2026-09-21',
      end: '2026-10-02',
      state: 'active',
    },
    {
      id: 's13',
      title: 'Sprint 13',
      description: 'Tăng tốc cộng tác và giảm thao tác lặp.',
      start: '2026-10-05',
      end: '2026-10-16',
      state: 'planned',
    },
  ],
  epics: [
    {
      id: 'channels',
      title: 'Kết nối kênh bán',
      description: 'Thông tin nhất quán từ đặt phòng đến thanh toán.',
      progress: 64,
    },
    {
      id: 'experience',
      title: 'Trải nghiệm vận hành',
      description: 'Giảm bước thao tác cho nhóm tuyến đầu.',
      progress: 38,
    },
  ],
  tags: [
    { id: 'tech', title: 'Nợ kỹ thuật', color: 'blue' },
    { id: 'risk', title: 'Rủi ro dữ liệu', color: 'red' },
    { id: 'release', title: 'Phát hành tháng 9', color: 'green' },
  ],
  forms: [
    {
      id: 'f1',
      projectId: 'core',
      title: 'Tiếp nhận lỗi sản phẩm',
      description: 'Tên lỗi · mức ảnh hưởng · mô tả · người gửi',
      responses: 12,
    },
  ],
  views: [
    {
      id: 'v1',
      projectId: 'core',
      title: 'Cần chú ý trong tuần',
      description: 'Ưu tiên cao · chưa hoàn thành',
      query: '',
      status: 'all',
    },
  ],
  inbox: [
    {
      id: 'n1',
      title: 'Bạn được giao KV-142',
      description: 'Đồng bộ tồn phòng giữa hai nguồn',
      read: false,
      taskId: 'KV-142',
    },
    {
      id: 'n2',
      title: 'Thu Hà đã nhắc đến bạn',
      description: 'Kiểm tra lại truy vấn đối chiếu trước 15:00.',
      read: false,
      taskId: 'KV-142',
    },
    {
      id: 'n3',
      title: 'Sprint 12 đã bắt đầu',
      description: '12 công việc · 39 điểm ước lượng',
      read: true,
      taskId: 'KV-144',
    },
  ],
  history: [],
  files: [
    {
      id: 'file1',
      taskId: 'KV-142',
      title: 'doi-chieu-ton-phong.csv',
      description: '48 KB · Lê Thu Hà',
    },
  ],
  timezone: 'Asia/Ho_Chi_Minh',
})
