import { defineModule } from '@ketvietlab/ketjs'
import { routes } from './routes.ts'
import { searchFilterFunctions } from './search-functions.ts'

export default defineModule({
  name: 'hr_backend',
  version: '0.1.0',
  depends: ['hr', 'backend'],
  title: 'Nhân sự trong quản trị',
  summary: 'Hồ sơ, ca xoay và nghỉ phép.',
  category: 'Nhân sự',
  routes,
  functions: searchFilterFunctions,
  menus: {
    hr: {
      label: 'menu.app',
      icon: 'users',
      path: '/admin/hr',
      sequence: 40,
      needs: 'hr.employee.manageList',
    },
    'hr.roster': {
      parent: 'hr',
      label: 'menu.roster',
      path: '/admin/hr/roster',
      sequence: 10,
      needs: 'hr.roster.manageList',
    },
    'hr.leaves': {
      parent: 'hr',
      label: 'menu.leaves',
      path: '/admin/hr/leaves',
      sequence: 20,
      needs: 'hr.leave.manageList',
    },
  },
  messages: {
    vi: {
      'app.title': 'Nhân sự trong quản trị',
      'app.summary': 'Hồ sơ, ca xoay và nghỉ phép.',
      'app.category': 'Nhân sự',
      'menu.app': 'Nhân sự',
      'menu.roster': 'Lịch ca',
      'menu.leaves': 'Nghỉ phép',
      'employees.title': 'Nhân viên',
      'employees.create': 'Thêm nhân viên',
      'employees.edit': 'Chỉnh sửa nhân viên',
      'employees.formHint': 'Vai trò nhân viên được duy trì tự động cùng hồ sơ đối tác cá nhân.',
      'employees.nameHelp': 'Tên hiển thị thuộc hồ sơ đối tác và được chỉnh sửa tại màn hình Đối tác.',
      'employees.userHelp': 'ID tài khoản nội bộ liên kết, có thể để trống.',
      'employees.activeHelp': 'Bỏ chọn để lưu trữ nhân viên nhưng vẫn giữ lịch sử nhân sự.',
      'roster.title': 'Lịch ca',
      'roster.generate': 'Sinh lịch tuần',
      'roster.week': 'Tuần',
      'roster.hint': 'Ca xoay được sinh idempotent và chỉ sửa khi lịch ở trạng thái nháp.',
      'roster.reopenReason': 'Điều chỉnh lịch đã phát hành',
      'leaves.title': 'Duyệt nghỉ phép',
      'leaves.subtitle': 'Rà soát yêu cầu, thời lượng và trạng thái trước khi ra quyết định.',
      'leaves.decisionFailed': 'Không thể cập nhật yêu cầu nghỉ',
      'field.code': 'Mã',
      'field.name': 'Tên',
      'field.userId': 'User ID',
      'field.branchId': 'Chi nhánh',
      'field.timezone': 'Múi giờ',
      'field.startDate': 'Ngày vào làm',
      'field.endDate': 'Ngày nghỉ việc',
      'field.active': 'Đang làm việc',
      'field.state': 'Trạng thái',
      'field.weekStart': 'Thứ Hai đầu tuần',
      'field.employee': 'Nhân viên',
      'field.requestId': 'Mã yêu cầu',
      'field.leaveType': 'Loại nghỉ',
      'field.date': 'Ngày',
      'field.startAt': 'Bắt đầu',
      'field.stopAt': 'Kết thúc',
      'field.days': 'Số ngày',
      'field.reason': 'Lý do',
      'field.actions': 'Thao tác',
      'action.create': 'Tạo nhân viên',
      'action.save': 'Lưu',
      'action.cancel': 'Hủy',
      'action.archive': 'Lưu trữ',
      'action.restore': 'Khôi phục',
      'action.generate': 'Sinh lịch',
      'action.publish': 'Phát hành',
      'action.reopen': 'Mở lại',
      'action.approve': 'Duyệt',
      'action.reject': 'Từ chối',
      'state.active': 'Đang làm việc',
      'state.archived': 'Đã lưu trữ',
      'state.draft': 'Nháp',
      'state.published': 'Đã phát hành',
      'state.requested': 'Chờ duyệt',
      'state.approved': 'Đã duyệt',
      'state.rejected': 'Từ chối',
      'state.cancelled': 'Đã hủy',
      'search.leaves': 'Tìm theo mã, nhân viên, loại nghỉ hoặc ngày',
      'empty.employees': 'Chưa có nhân viên',
      'empty.employeesHint': 'Tạo hồ sơ nhân viên đầu tiên để bắt đầu quản lý nhân sự.',
      'empty.shifts': 'Chưa có ca',
      'empty.shiftsHint': 'Gán chu kỳ cho nhân viên rồi sinh lại lịch.',
      'empty.leaves': 'Không có yêu cầu nghỉ',
      'empty.leavesHint': 'Yêu cầu từ nhân viên sẽ xuất hiện tại đây.',
      'error.invalid': 'Không thể lưu dữ liệu.',
    },
    en: {
      'app.title': 'HR in admin',
      'app.summary': 'Employee records, rotating shifts, and leave.',
      'app.category': 'Human Resources',
      'menu.app': 'Human resources',
      'menu.roster': 'Shift roster',
      'menu.leaves': 'Leave',
      'employees.title': 'Employees',
      'employees.create': 'Add employee',
      'employees.edit': 'Edit employee',
      'employees.formHint': 'The employee role stays synchronized with the personal partner record.',
      'employees.nameHelp': 'The display name belongs to the partner record and is edited from Partners.',
      'employees.userHelp': 'Linked internal account ID; leave empty when no account is required.',
      'employees.activeHelp': 'Clear to archive the employee while retaining HR history.',
      'roster.title': 'Shift roster',
      'roster.generate': 'Generate weekly roster',
      'roster.week': 'Week',
      'roster.hint': 'Rotating shifts generate idempotently and can only change while the roster is draft.',
      'roster.reopenReason': 'Adjust a published roster',
      'leaves.title': 'Leave approvals',
      'leaves.subtitle': 'Review each request, duration, and status before making a decision.',
      'leaves.decisionFailed': 'The leave request could not be updated',
      'field.code': 'Code',
      'field.name': 'Name',
      'field.userId': 'User ID',
      'field.branchId': 'Branch',
      'field.timezone': 'Timezone',
      'field.startDate': 'Start date',
      'field.endDate': 'End date',
      'field.active': 'Active employee',
      'field.state': 'Status',
      'field.weekStart': 'Week Monday',
      'field.employee': 'Employee',
      'field.requestId': 'Request ID',
      'field.leaveType': 'Leave type',
      'field.date': 'Date',
      'field.startAt': 'Starts',
      'field.stopAt': 'Stops',
      'field.days': 'Days',
      'field.reason': 'Reason',
      'field.actions': 'Actions',
      'action.create': 'Create employee',
      'action.save': 'Save',
      'action.cancel': 'Cancel',
      'action.archive': 'Archive',
      'action.restore': 'Restore',
      'action.generate': 'Generate',
      'action.publish': 'Publish',
      'action.reopen': 'Reopen',
      'action.approve': 'Approve',
      'action.reject': 'Reject',
      'state.active': 'Active',
      'state.archived': 'Archived',
      'state.draft': 'Draft',
      'state.published': 'Published',
      'state.requested': 'Requested',
      'state.approved': 'Approved',
      'state.rejected': 'Rejected',
      'state.cancelled': 'Cancelled',
      'search.leaves': 'Search by request, employee, leave type, or date',
      'empty.employees': 'No employees',
      'empty.employeesHint': 'Create the first employee record to start managing your workforce.',
      'empty.shifts': 'No shifts',
      'empty.shiftsHint': 'Assign a rotation and generate the roster again.',
      'empty.leaves': 'No leave requests',
      'empty.leavesHint': 'Employee requests appear here.',
      'error.invalid': 'The data could not be saved.',
    },
  },
})

export {
  employeeFields,
  employeeFormModal,
  employeeFormScreen,
  employeeListColumns,
  employeesListScreen,
  leaveListColumns,
  leavesListScreen,
  rosterScreen,
} from './screens/index.ts'
export type {
  EmployeeFormScreenOptions,
  EmployeeFormValues,
  EmployeeListRow,
  EmployeesListScreenOptions,
  LeaveListRow,
  LeavesListScreenOptions,
  RosterScreenOptions,
} from './screens/index.ts'
