import { defineModule } from '@ketvietlab/ketjs'
import { functions } from './functions.ts'
import { islands } from './islands.ts'
import { routes } from './routes.ts'
import { menus } from './menus.ts'

/**
 * The catalogue, in the admin — kept out of `product`.
 *
 * `product` must not depend on `backend`. A catalogue is a catalogue whether or
 * not this deployment ships an admin UI, and requiring one would mean a headless
 * API could not have products. But a screen in the admin genuinely needs both.
 *
 * So it is a bridge selected by deployments that need both sides. A headless
 * deployment selects `product` without this module; an admin deployment selects
 * both and receives the screens.
 *
 * It owns the page as well as the link. A bridge that contributed only a button
 * would be a bridge that ships a link to a 404.
 */
export default defineModule({
  name: 'product_backend',
  version: '0.2.0',
  depends: ['product_media', 'backend'],
  title: 'Sản phẩm trong quản trị',
  summary: 'Màn hình danh mục sản phẩm và lối vào từ thanh điều hướng.',
  category: 'Hệ thống',
  assets: new URL('./client/', import.meta.url),
  styles: ['product.css'],
  islands,
  behaviors: {
    'product.editor': {
      client: 'product.mjs',
      export: 'editorBehavior',
      when: 'form[data-scope="product-detail"], form[data-scope="product-variant"]',
    },
  },
  routes,
  menus,
  functions,
  joints: {
    /** Presentation-only entries owned by modules that add product operations. */
    'catalogue.actions': { props: { locale: 'text?' }, multiple: true },
    'template.actions': { props: { templateId: 'id', locale: 'text?' }, multiple: true },
    /**
     * A tab another module adds to the template record modal. Fill it with one
     * island placement; the island renders the tab's panel with `{ templateId,
     * locale }`. The tab is labelled by the filling module's
     * `<module>.productTemplateTab` message and addressed as `tab=<module>`.
     */
    'template.recordTabs': { props: { templateId: 'id', locale: 'text?' }, multiple: true },
    /** Server detail page only; the record modal reads `template.recordTabs`. */
    'template.tabs': {
      props: { templateId: 'id', activeTab: 'text', locale: 'text?', querySuffix: 'text?' },
      multiple: true,
    },
    /** Server detail page only; the record modal reads `template.recordTabs`. */
    'template.panel': {
      props: { templateId: 'id', activeTab: 'text', locale: 'text?', querySuffix: 'text?' },
      multiple: true,
    },
    'template.media': { props: { templateId: 'id' } },
    'variant.media': { props: { productId: 'id' } },
    'template.collaboration': {
      props: { resModel: 'text', resId: 'id', lang: 'text' },
      multiple: true,
    },
    'variant.collaboration': {
      props: { resModel: 'text', resId: 'id', lang: 'text' },
      multiple: true,
    },
    'template.editor': { props: { identity: 'text', templateId: 'id', lang: 'text?' } },
    'variant.editor': { props: { identity: 'text', productId: 'id', lang: 'text?' } },
    'media.upload': { props: { identity: 'text', action: 'text', label: 'text' } },
    'template.page': {
      props: { id: 'text', tab: 'text?', title: 'text', loading: 'text', back: 'text', width: 'text?' },
    },
  },
  messages: {
    vi: {
      'app.title': 'Sản phẩm trong quản trị',
      'app.summary': 'Màn hình danh mục sản phẩm và lối vào từ thanh điều hướng.',
      'app.category': 'Hệ thống',
      'menu.app': 'Sản phẩm',
      'menu.catalogue': 'Danh mục',
      'menu.templates': 'Mẫu sản phẩm',
      'menu.attributes': 'Thuộc tính',
      'chrome.search': 'Tìm sản phẩm…',
      'search.label': 'Tìm và lọc sản phẩm',
      'table.sortAscending': 'Sắp xếp tăng dần',
      'table.sortDescending': 'Sắp xếp giảm dần',
      openCatalogue: 'Mở danh mục',
      'screen.title': 'Danh mục sản phẩm',
      'screen.results': '{count} sản phẩm',
      'screen.empty.message': 'Chưa có sản phẩm nào.',
      'screen.empty.hint': 'Tạo mẫu sản phẩm đầu tiên để bắt đầu.',
      'col.image': 'Ảnh',
      'col.name': 'Tên',
      'col.type': 'Loại',
      'col.uom': 'Đơn vị',
      'col.variants': 'Biến thể',
      'col.category': 'Nhóm',
      'col.sequence': 'Thứ tự',
      'col.state': 'Trạng thái',
      'state.active': 'Đang hoạt động',
      'state.archived': 'Đã lưu trữ',
      'type.goods': 'Hàng hoá',
      'type.service': 'Dịch vụ',
      'media.title': 'Hình ảnh',
      'media.description': 'Ảnh chính và thư viện ảnh của sản phẩm.',
      'media.unavailable': 'Chưa kết nối dịch vụ hình ảnh.',
      'media.empty': 'Chưa có hình ảnh.',
      'media.loading': 'Đang tải hình ảnh',
      'media.error': 'Không thể tải hình ảnh',
      'media.retry': 'Vui lòng thử lại khi dịch vụ hình ảnh hoạt động.',
      'media.primaryLabel': 'Ảnh chính',
      'media.primary': 'Đặt làm ảnh chính',
      'media.up': 'Dịch lên',
      'media.down': 'Dịch xuống',
      'media.remove': 'Xóa ảnh',
      'media.choose': 'Chọn ảnh',
      'media.add': 'Thêm ảnh',
      'media.panelTitle': 'Hình ảnh sản phẩm',
      'media.panelHint': 'Quản lý hình ảnh hiển thị của sản phẩm và thứ tự xuất hiện.',
      'media.sortAutomatic': 'Sắp xếp tự động',
      'media.primaryHint': 'Hình ảnh đầu tiên được dùng làm ảnh đại diện tại danh sách sản phẩm.',
      'media.variantTitle': 'Hình ảnh theo biến thể',
      'media.variantHint': 'Thiết lập hình ảnh riêng cho từng biến thể khi cần.',
      'media.variantColumn': 'Biến thể',
      'media.representative': 'Ảnh đại diện',
      'media.library': 'Thư viện ảnh',
      'media.variantEmpty': 'Sản phẩm chưa có biến thể để gắn hình ảnh.',
      'media.variantAdd': 'Thêm hình ảnh cho biến thể',
      'media.variantEdit': 'Chỉnh sửa hình ảnh biến thể',
      'media.variantRemove': 'Xóa ảnh đại diện của biến thể',
      'detail.information': 'Thông tin sản phẩm',
      'detail.kicker': 'Sản phẩm',
      'summary.variants': 'Biến thể',
      'summary.images': 'Hình ảnh',
      'summary.tracking': 'Truy xuất',
      'summary.channels': 'Hiển thị',
      'summary.updated': 'Cập nhật lần cuối',
      'tabs.label': 'Nội dung sản phẩm',
      'tabs.general': 'Thông tin chung',
      'tabs.variants': 'Thuộc tính & biến thể',
      'tabs.media': 'Hình ảnh',
      'tabs.display': 'Hiển thị',
      'tabs.documents': 'Tài liệu',
      'tabs.history': 'Lịch sử',
      'collaboration.label': 'Trao đổi và hoạt động của sản phẩm',
      'variant.kicker': 'Biến thể sản phẩm',
      'variant.template': 'Mẫu sản phẩm',
      'variant.combination': 'Tổ hợp',
      'variant.tabs.label': 'Nội dung biến thể',
      'variant.collaboration.label': 'Trao đổi và hoạt động của biến thể',
      'action.create': 'Tạo mới',
      'action.save': 'Lưu',
      'action.saveGeneral': 'Lưu thông tin chung',
      'action.delete': 'Xoá vĩnh viễn',
      'readOnly.title': 'Chỉ xem',
      'readOnly.message': 'Bạn không có quyền chỉnh sửa sản phẩm này.',
      'action.saveClose': 'Lưu & đóng',
      'action.saveOptions': 'Tuỳ chọn lưu',
      'action.internalNote': 'Ghi chú nội bộ',
      'action.more': 'Thêm thao tác',
      'action.moreShort': 'Thêm',
      'action.close': 'Đóng',
      'action.back': 'Về danh sách',
      'action.actions': 'Thao tác sản phẩm',
      'action.cancel': 'Hủy',
      'favorite.create': 'Lưu tìm kiếm hiện tại',
      'favorite.save': 'Lưu yêu thích',
      'favorite.name': 'Tên',
      'favorite.default': 'Dùng làm mặc định cho danh sách này',
      'favorite.invalid': 'Không thể lưu tìm kiếm này. Hãy kiểm tra tên và bộ lọc.',
      'action.add': 'Thêm',
      'create.title': 'Tạo sản phẩm',
      'create.kicker': 'Sản phẩm mới',
      'create.subtitle': 'Khai báo thông tin cơ bản; hình ảnh, biến thể và trao đổi sẽ có sau khi tạo.',
      'error.invalid': 'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại.',
      'field.name': 'Tên',
      'field.type': 'Loại',
      'field.businessUse': 'Nghiệp vụ áp dụng',
      'field.productKind': 'Loại hàng hoá',
      'field.uom': 'Đơn vị tính',
      'field.category': 'Danh mục',
      'field.active': 'Đang hoạt động',
      'field.createdAt': 'Ngày tạo',
      'field.updatedAt': 'Ngày cập nhật',
      'field.listPrice': 'Giá bán',
      'field.saleOk': 'Có thể bán',
      'field.purchaseOk': 'Có thể mua',
      'field.isStorable': 'Theo dõi tồn kho',
      'field.tracking': 'Truy xuất',
      'value.yes': 'Có',
      'value.no': 'Không',
      'tracking.none': 'Không theo dõi',
      'tracking.lot': 'Theo lô',
      'tracking.serial': 'Theo số sê-ri duy nhất',
      'field.description': 'Mô tả',
      'field.defaultCode': 'Mã nội bộ',
      'field.barcode': 'Mã vạch',
      'field.variantIdentityHint':
        'Sản phẩm đã có biến thể. Hãy đặt mã riêng trên từng biến thể; giá trị này chỉ thuộc biến thể mặc định.',
      'field.taxRate': 'Thuế suất',
      'field.brand': 'Thương hiệu',
      'field.origin': 'Xuất xứ',
      'field.archiveReason': 'Lý do lưu trữ',
      'field.weight': 'Khối lượng',
      'field.volume': 'Thể tích',
      'field.standardPrice': 'Giá vốn',
      'field.uomBarcode': 'Mã vạch theo đơn vị',
      'variants.title': 'Biến thể',
      'variants.generate': 'Sinh biến thể',
      'variants.empty': 'Chưa có biến thể.',
      'variants.panelHint': 'Danh sách biến thể được tạo từ các thuộc tính ở trên.',
      'variants.refresh': 'Làm mới danh sách biến thể',
      'variants.code': 'Mã biến thể',
      'variants.values': 'Thuộc tính',
      'variants.sku': 'SKU',
      'variants.stock': 'Tồn kho',
      'variants.actions': 'Hành động',
      'variants.selling': 'Đang bán',
      'variants.edit': 'Sửa biến thể',
      'variants.display': 'Hiển thị',
      'variants.range': '{from} – {to} / {total} biến thể',
      'variants.previous': 'Trang trước',
      'variants.next': 'Trang sau',
      'attributes.title': 'Thuộc tính sản phẩm',
      'attributes.createTitle': 'Thuộc tính mới',
      'attributes.createHint': 'Khai báo cách hiển thị và thời điểm sinh biến thể.',
      'attributes.configuredTitle': 'Thuộc tính đã cấu hình',
      'attributes.configuredHint': 'Xem nhanh các giá trị và bổ sung giá trị ngay tại từng thuộc tính.',
      'attributes.empty': 'Chưa có thuộc tính sản phẩm',
      'attributes.emptyHint': 'Tạo thuộc tính đầu tiên để khai báo các giá trị sản phẩm.',
      'attributes.search': 'Tìm thuộc tính…',
      'attributes.addValue': 'Thêm giá trị',
      'attributes.removeValue': 'Gỡ giá trị',
      'attributes.moveUp': 'Chuyển lên',
      'attributes.moveDown': 'Chuyển xuống',
      'attributes.dragValue': 'Kéo để đổi thứ tự',
      'attributes.color': 'Màu',
      'attributes.emptyValues': 'Chưa có giá trị. Thêm giá trị để sử dụng thuộc tính này.',
      'attributes.save': 'Lưu thuộc tính',
      'attributes.lines': 'Dòng thuộc tính',
      'attributes.linesHint': 'Chọn thuộc tính và các giá trị áp dụng cho mẫu sản phẩm này.',
      'attributes.panelTitle': 'Thuộc tính',
      'attributes.panelHint': 'Các thuộc tính dùng để tạo biến thể sản phẩm.',
      'attributes.sort': 'Sắp xếp',
      'attributes.nameColumn': 'Tên thuộc tính',
      'attributes.dataType': 'Kiểu dữ liệu',
      'attributes.required': 'Bắt buộc',
      'attributes.optional': 'Không',
      'attributes.selectOne': 'Chọn một',
      'attributes.actions': 'Hành động',
      'attributes.editLine': 'Sửa thuộc tính',
      'attributes.addLine': 'Thêm thuộc tính',
      'attributes.attribute': 'Thuộc tính',
      'attributes.values': 'Giá trị',
      'attributes.valuesHint': 'Chọn giá trị từ danh sách; có thể tạo mới ngay tại đây.',
      'relation.categories': 'Danh mục sản phẩm',
      'relation.brands': 'Thương hiệu',
      'relation.units': 'Đơn vị tính',
      'relation.attributes': 'Thuộc tính sản phẩm',
      'relation.attributeValues': 'Giá trị thuộc tính',
      'relation.templates': 'Mẫu sản phẩm',
      'relation.variants': 'Biến thể sản phẩm',
      'relation.unitFactor': 'Hệ số so với đơn vị cha',
      'attributes.displayType': 'Kiểu hiển thị',
      'attributes.createVariant': 'Tạo biến thể',
      'attributes.always': 'Luôn tạo',
      'attributes.never': 'Không tạo',
      'attributes.noValues': 'Chưa có giá trị',
      'attributes.removeLine': 'Gỡ',
      'archive.title': 'Lưu trữ sản phẩm',
      'archive.hint': 'Sản phẩm đã lưu trữ không còn xuất hiện trong danh mục, nhưng dữ liệu vẫn được giữ.',
      'archive.action': 'Lưu trữ',
      'archive.reasonPlaceholder': 'Nhập lý do lưu trữ (tuỳ chọn)…',
      'archive.restoreTitle': 'Sản phẩm đã lưu trữ',
      'archive.restoreHint': 'Khôi phục để sản phẩm xuất hiện trở lại trong danh mục.',
      'archive.restore': 'Khôi phục',
      'archive.deleteConfirm': 'Xoá vĩnh viễn sản phẩm "{name}"? Không thể hoàn tác.',
      'advanced.title': 'Thiết lập nâng cao',
      'rail.system': 'Thông tin hệ thống',
      'rail.id': 'ID',
      'rail.createdBy': 'Người tạo',
      'rail.createdAt': 'Ngày tạo',
      'rail.updatedBy': 'Cập nhật bởi',
      'rail.updatedAt': 'Cập nhật lần cuối',
      'rail.channels': 'Hiển thị trên kênh',
      'rail.channelsHint': 'Quản lý hiển thị sản phẩm trên các kênh bán hàng.',
      'rail.manageChannels': 'Quản lý hiển thị',
      'rail.activity': 'Nhật ký hoạt động',
      'channel.website': 'Website',
      'channel.pos': 'POS',
      'channel.mobile': 'Mobile App',
      'channel.shopee': 'Shopee',
      'channel.lazada': 'Lazada',
      'activity.updated': 'Cập nhật thông tin sản phẩm',
      'activity.created': 'Thêm mới sản phẩm',
      'activity.viewAll': 'Xem tất cả nhật ký',
      'attributes.linesEmpty': 'Chưa có dòng thuộc tính',
      'attributes.linesEmptyHint': 'Thêm một thuộc tính để có thể sinh biến thể.',
      'attributes.valueName': 'Tên giá trị',
      'image.open': 'Xem ảnh {alt}',
      'image.close': 'Đóng',
      'image.previous': 'Ảnh trước',
      'image.next': 'Ảnh sau',
      'image.zoomIn': 'Phóng to',
      'image.zoomOut': 'Thu nhỏ',
      'image.counter': '{index} / {total}',
      'image.empty': 'Chưa có ảnh',
      'image.upload': 'Tải ảnh lên',
      'image.replace': 'Thay ảnh',
      'image.remove': 'Gỡ',
      'image.drop': 'Kéo thả ảnh vào đây để tải lên',
      'image.removeConfirm': 'Gỡ ảnh chính của sản phẩm?',
      'image.saveFirst': 'Lưu biến thể trước khi thêm ảnh',
      'image.uploadFailed': 'Chưa tải được ảnh lên',
      'variantEditor.image': 'Ảnh',
      'variantEditor.uploadImage': 'Tải ảnh',
      'variantEditor.replaceImage': 'Thay ảnh',
      'variantEditor.removeImage': 'Gỡ ảnh',
      'variantEditor.dropImage': 'Kéo thả ảnh vào đây',
      'variantEditor.imageSaveFirst': 'Lưu biến thể trước khi thêm ảnh',
      'variantEditor.imageFailed': 'Chưa tải được ảnh lên',
      'variantEditor.imageRemoveConfirm': 'Gỡ ảnh của biến thể này?',
      'variantEditor.attributesTitle': 'Thuộc tính',
      'variantEditor.createAttribute': 'Tạo thuộc tính',
      'variantEditor.createAttributeHint':
        'Thuộc tính được lưu vào danh mục dùng chung. Sau khi thêm, bấm Lưu để áp dụng các thay đổi cho sản phẩm.',
      'variantEditor.attributeName': 'Tên thuộc tính',
      'variantEditor.attributeNameExample': 'Ví dụ: Dung tích',
      'variantEditor.attributeValues': 'Giá trị',
      'variantEditor.attributeValuesHint':
        'Mỗi dòng một giá trị. Các giá trị này sẽ được chọn sẵn cho sản phẩm.',
      'variantEditor.attributeValuesExample': '30 ml\n50 ml',
      'variantEditor.createAndAddAttribute': 'Tạo và thêm',
      'variantEditor.cancelAttribute': 'Huỷ',
      'variantEditor.attributeNameRequired': 'Nhập tên thuộc tính.',
      'variantEditor.attributeNameDuplicate':
        'Tên thuộc tính đã tồn tại. Hãy chọn thuộc tính có sẵn hoặc dùng tên khác.',
      'variantEditor.attributeValuesRequired': 'Nhập ít nhất một giá trị.',
      'variantEditor.attributeValuesDuplicate': 'Các giá trị không được trùng nhau.',
      'variantEditor.attributeValuesInvalid': 'Kiểm tra lại các giá trị thuộc tính.',
      'variantEditor.attributeCreateFailed': 'Chưa tạo được thuộc tính',
      'variantEditor.attributeRetryHint': 'Nội dung đã nhập được giữ lại. Hãy thử lại.',
      'variantEditor.stepAttributes': 'Bước 1',
      'variantEditor.stepVariants': 'Bước 2',
      'variantEditor.attributesHint': 'Chọn thuộc tính và tích những giá trị sản phẩm này có bán.',
      'variantEditor.attributesEmpty': 'Chưa có thuộc tính',
      'variantEditor.attributesEmptyHint':
        'Tìm hoặc tạo thuộc tính như Màu sắc, Dung tích ở ô “Thêm thuộc tính…”.',
      'variantEditor.addAttribute': 'Thêm thuộc tính…',
      'variantEditor.removeAttributeNamed': 'Gỡ thuộc tính {name}',
      'variantEditor.selectAll': 'Chọn tất cả',
      'variantEditor.valuesSelected': 'Đã chọn {count}/{total} giá trị',
      'variantEditor.valuesNone': 'Chưa chọn giá trị nào — thuộc tính này chưa tạo biến thể.',
      'variantEditor.noVariantHint': 'Chỉ mô tả sản phẩm, không tạo biến thể.',
      'variantEditor.priceExtrasSet': 'Giá cộng thêm: {list}',
      'variantEditor.priceExtrasNone': 'Giá cộng thêm: chưa đặt',
      'variantEditor.invalidNumber': 'Nhập một số hợp lệ.',
      'variantEditor.rowInvalid': 'Số chưa hợp lệ',
      'variantEditor.appliesTo': 'Áp dụng cho {count} biến thể',
      'variantEditor.noVariant': 'Không tạo biến thể',
      'variantEditor.variantsTitle': 'Biến thể',
      'variantEditor.variantsCount': '{active} đang bán / {total} biến thể',
      'variantEditor.variantsEmpty': 'Chưa có biến thể',
      'variantEditor.variantsEmptyHint': 'Mọi tổ hợp đã có biến thể. Có thể thêm biến thể thủ công.',
      'variantEditor.variantsNeedAttributes': 'Thêm thuộc tính có giá trị ở trên để tạo biến thể.',
      'variantEditor.generate': 'Tạo {count} biến thể',
      'variantEditor.missingMore': 'và {count} tổ hợp khác',
      'variantEditor.defaultVariant': 'Biến thể mặc định',
      'variantEditor.details': 'Chi tiết',
      'variantEditor.saving': 'Đang lưu…',
      'variantEditor.summaryInvalid': 'Có số chưa hợp lệ — sửa trước khi lưu.',
      'variantEditor.addVariant': 'Thêm biến thể',
      'variantEditor.activateAll': 'Bán tất cả',
      'variantEditor.archiveAll': 'Lưu trữ tất cả',
      'variantEditor.missing': 'Còn {count} tổ hợp chưa có biến thể',
      'variantEditor.choose': 'Chọn {name}',
      'variantEditor.archived': 'Lưu trữ',
      'variantEditor.duplicate': 'Trùng với #{row}',
      'variantEditor.incomplete': 'Chưa đủ thuộc tính',
      'variantEditor.new': 'Mới',
      'variantEditor.edit': 'Sửa',
      'variantEditor.collapse': 'Thu gọn',
      'variantEditor.remove': 'Bỏ',
      'variantEditor.archive': 'Lưu trữ',
      'variantEditor.restore': 'Bán lại',
      'variantEditor.defaultCode': 'Mã nội bộ (SKU)',
      'variantEditor.barcode': 'Mã vạch',
      'variantEditor.weight': 'Khối lượng',
      'variantEditor.volume': 'Thể tích',
      'variantEditor.listPrice': 'Giá bán',
      'variantEditor.summaryCreate': 'Sẽ tạo {count} biến thể mới',
      'variantEditor.summaryArchive': 'Sẽ lưu trữ {count} biến thể',
      'variantEditor.summaryChanged': 'Có thay đổi chưa lưu.',
      'variantEditor.summaryDuplicate': 'Có biến thể trùng tổ hợp — sửa trước khi lưu.',
      'variantEditor.reset': 'Huỷ thay đổi',
      'variantEditor.save': 'Lưu thuộc tính & biến thể',
      'variantEditor.saved': 'Đã lưu: tạo {created}, lưu trữ {archived}.',
      'variantEditor.saveFailed': 'Chưa lưu được',
      'variantEditor.readOnly': 'Bạn chỉ có quyền xem thuộc tính và biến thể.',
      'displayType.radio': 'Nút chọn',
      'displayType.pills': 'Nút dạng thẻ',
      'displayType.select': 'Danh sách chọn',
      'displayType.color': 'Màu sắc',
      'displayType.multi': 'Chọn nhiều',
      'createVariant.always': 'Luôn tạo biến thể',
      'createVariant.no_variant': 'Không tạo biến thể',
    },
    en: {
      'app.title': 'Products in admin',
      'app.summary': 'The catalogue screen, and the way into it.',
      'app.category': 'System',
      'menu.app': 'Products',
      'menu.catalogue': 'Catalogue',
      'menu.templates': 'Templates',
      'menu.attributes': 'Attributes',
      'chrome.search': 'Search products…',
      'search.label': 'Search and filter products',
      'table.sortAscending': 'Sorted ascending',
      'table.sortDescending': 'Sorted descending',
      openCatalogue: 'Open catalogue',
      'screen.title': 'Product catalogue',
      'screen.results': { one: '{count} product', other: '{count} products' },
      'screen.empty.message': 'No products yet.',
      'screen.empty.hint': 'Create the first template to begin.',
      'col.image': 'Image',
      'col.name': 'Name',
      'col.type': 'Type',
      'col.uom': 'Unit',
      'col.variants': 'Variants',
      'col.category': 'Category',
      'col.sequence': 'Sequence',
      'col.state': 'State',
      'state.active': 'Active',
      'state.archived': 'Archived',
      'type.goods': 'Goods',
      'type.service': 'Service',
      'media.title': 'Images',
      'media.description': 'Primary image and product gallery.',
      'media.unavailable': 'The image service is not connected.',
      'media.empty': 'No images yet.',
      'media.loading': 'Loading images',
      'media.error': 'Images could not be loaded',
      'media.retry': 'Try again when the image service is available.',
      'media.primaryLabel': 'Primary image',
      'media.primary': 'Set as primary',
      'media.up': 'Move up',
      'media.down': 'Move down',
      'media.remove': 'Remove image',
      'media.choose': 'Choose image',
      'media.add': 'Add image',
      'media.panelTitle': 'Product images',
      'media.panelHint': 'Manage the images shown for this product and their display order.',
      'media.sortAutomatic': 'Automatic ordering',
      'media.primaryHint': 'The first image is used as the product thumbnail in catalogue lists.',
      'media.variantTitle': 'Images by variant',
      'media.variantHint': 'Set variant-specific images when they are needed.',
      'media.variantColumn': 'Variant',
      'media.representative': 'Primary image',
      'media.library': 'Image library',
      'media.variantEmpty': 'This product has no variants to attach images to.',
      'media.variantAdd': 'Add variant image',
      'media.variantEdit': 'Edit variant images',
      'media.variantRemove': 'Remove the variant primary image',
      'detail.information': 'Product information',
      'detail.kicker': 'Product',
      'summary.variants': 'Variants',
      'summary.images': 'Images',
      'summary.tracking': 'Tracking',
      'summary.channels': 'Display',
      'summary.updated': 'Last updated',
      'tabs.label': 'Product sections',
      'tabs.general': 'General information',
      'tabs.variants': 'Attributes & variants',
      'tabs.media': 'Images',
      'tabs.display': 'Display',
      'tabs.documents': 'Documents',
      'tabs.history': 'History',
      'collaboration.label': 'Product conversation and activities',
      'variant.kicker': 'Product variant',
      'variant.template': 'Product template',
      'variant.combination': 'Combination',
      'variant.tabs.label': 'Variant sections',
      'variant.collaboration.label': 'Variant conversation and activities',
      'action.create': 'Create',
      'action.save': 'Save',
      'action.saveGeneral': 'Save general information',
      'action.delete': 'Delete permanently',
      'readOnly.title': 'Read only',
      'readOnly.message': 'You do not have permission to edit this product.',
      'action.saveClose': 'Save & close',
      'action.saveOptions': 'Save options',
      'action.internalNote': 'Internal note',
      'action.more': 'More actions',
      'action.moreShort': 'More',
      'action.close': 'Close',
      'action.back': 'Back to list',
      'action.actions': 'Product actions',
      'action.cancel': 'Cancel',
      'favorite.create': 'Save current search',
      'favorite.save': 'Save favorite',
      'favorite.name': 'Name',
      'favorite.default': 'Use as the default for this list',
      'favorite.invalid': 'This search could not be saved. Check its name and filters.',
      'action.add': 'Add',
      'create.title': 'Create product',
      'create.kicker': 'New product',
      'create.subtitle': 'Set the basics; images, variants, and collaboration are available after creation.',
      'error.invalid': 'The submitted data is invalid. Please review it.',
      'field.name': 'Name',
      'field.type': 'Type',
      'field.businessUse': 'Business use',
      'field.productKind': 'Product type',
      'field.uom': 'Unit of measure',
      'field.category': 'Category',
      'field.active': 'Active',
      'field.createdAt': 'Created at',
      'field.updatedAt': 'Updated at',
      'field.listPrice': 'Sales price',
      'field.saleOk': 'Can be sold',
      'field.purchaseOk': 'Can be purchased',
      'field.isStorable': 'Track inventory',
      'field.tracking': 'Tracking',
      'value.yes': 'Yes',
      'value.no': 'No',
      'tracking.none': 'No tracking',
      'tracking.lot': 'By lots',
      'tracking.serial': 'By unique serial number',
      'field.description': 'Description',
      'field.defaultCode': 'Internal reference',
      'field.barcode': 'Barcode',
      'field.variantIdentityHint':
        'This product has variants. Set identifiers on each variant; this value belongs only to the default variant.',
      'field.taxRate': 'Tax rate',
      'field.brand': 'Brand',
      'field.origin': 'Origin',
      'field.archiveReason': 'Archive reason',
      'field.weight': 'Weight',
      'field.volume': 'Volume',
      'field.standardPrice': 'Cost',
      'field.uomBarcode': 'Unit barcode',
      'variants.title': 'Variants',
      'variants.generate': 'Generate variants',
      'variants.empty': 'No variants yet.',
      'variants.panelHint': 'Variants generated from the attributes above.',
      'variants.refresh': 'Refresh variants',
      'variants.code': 'Variant code',
      'variants.values': 'Attributes',
      'variants.sku': 'SKU',
      'variants.stock': 'Stock',
      'variants.actions': 'Actions',
      'variants.selling': 'On sale',
      'variants.edit': 'Edit variant',
      'variants.display': 'Show',
      'variants.range': '{from} – {to} / {total} variants',
      'variants.previous': 'Previous page',
      'variants.next': 'Next page',
      'attributes.title': 'Product attributes',
      'attributes.createTitle': 'New attribute',
      'attributes.createHint': 'Define how the attribute is displayed and when variants are generated.',
      'attributes.configuredTitle': 'Configured attributes',
      'attributes.configuredHint': 'Review values at a glance and add a value to any attribute.',
      'attributes.empty': 'No product attributes yet',
      'attributes.emptyHint': 'Create the first attribute to define product values.',
      'attributes.search': 'Search attributes…',
      'attributes.addValue': 'Add value',
      'attributes.removeValue': 'Remove value',
      'attributes.moveUp': 'Move up',
      'attributes.moveDown': 'Move down',
      'attributes.dragValue': 'Drag to reorder',
      'attributes.color': 'Color',
      'attributes.emptyValues': 'No values yet. Add values to use this attribute.',
      'attributes.save': 'Save attribute',
      'attributes.lines': 'Attribute lines',
      'attributes.linesHint': 'Pick the attribute and the values that apply to this template.',
      'attributes.panelTitle': 'Attributes',
      'attributes.panelHint': 'Attributes used to generate product variants.',
      'attributes.sort': 'Sort',
      'attributes.nameColumn': 'Attribute name',
      'attributes.dataType': 'Data type',
      'attributes.required': 'Required',
      'attributes.optional': 'No',
      'attributes.selectOne': 'Single select',
      'attributes.actions': 'Actions',
      'attributes.editLine': 'Edit attribute',
      'attributes.addLine': 'Add attribute',
      'attributes.attribute': 'Attribute',
      'attributes.values': 'Values',
      'attributes.valuesHint': 'Pick values from the list; new ones can be created here.',
      'relation.categories': 'Product categories',
      'relation.brands': 'Brands',
      'relation.units': 'Units of measure',
      'relation.attributes': 'Product attributes',
      'relation.attributeValues': 'Attribute values',
      'relation.templates': 'Product templates',
      'relation.variants': 'Product variants',
      'relation.unitFactor': 'Factor against the parent unit',
      'attributes.displayType': 'Display type',
      'attributes.createVariant': 'Variant creation',
      'attributes.always': 'Always',
      'attributes.never': 'Never',
      'attributes.noValues': 'No values yet',
      'attributes.removeLine': 'Remove',
      'archive.title': 'Archive this product',
      'archive.hint': 'An archived product leaves the catalogue; nothing about it is deleted.',
      'archive.action': 'Archive',
      'archive.reasonPlaceholder': 'Enter an archive reason (optional)…',
      'archive.restoreTitle': 'This product is archived',
      'archive.restoreHint': 'Restore it to bring it back into the catalogue.',
      'archive.restore': 'Restore',
      'archive.deleteConfirm': 'Permanently delete "{name}"? This cannot be undone.',
      'advanced.title': 'Advanced settings',
      'rail.system': 'System information',
      'rail.id': 'ID',
      'rail.createdBy': 'Created by',
      'rail.createdAt': 'Created at',
      'rail.updatedBy': 'Updated by',
      'rail.updatedAt': 'Last updated',
      'rail.channels': 'Display on channels',
      'rail.channelsHint': 'Manage product visibility across sales channels.',
      'rail.manageChannels': 'Manage display',
      'rail.activity': 'Activity log',
      'channel.website': 'Website',
      'channel.pos': 'POS',
      'channel.mobile': 'Mobile App',
      'channel.shopee': 'Shopee',
      'channel.lazada': 'Lazada',
      'activity.updated': 'Updated product information',
      'activity.created': 'Created product',
      'activity.viewAll': 'View full activity log',
      'attributes.linesEmpty': 'No attribute lines yet',
      'attributes.linesEmptyHint': 'Add an attribute so variants can be generated.',
      'attributes.valueName': 'Value name',
      'image.open': 'View image {alt}',
      'image.close': 'Close',
      'image.previous': 'Previous image',
      'image.next': 'Next image',
      'image.zoomIn': 'Zoom in',
      'image.zoomOut': 'Zoom out',
      'image.counter': '{index} / {total}',
      'image.empty': 'No image',
      'image.upload': 'Upload image',
      'image.replace': 'Replace',
      'image.remove': 'Remove',
      'image.drop': 'Drop an image here to upload',
      'image.removeConfirm': "Remove the product's main image?",
      'image.saveFirst': 'Save the variant before adding an image',
      'image.uploadFailed': 'Could not upload the image',
      'variantEditor.image': 'Image',
      'variantEditor.uploadImage': 'Upload image',
      'variantEditor.replaceImage': 'Replace image',
      'variantEditor.removeImage': 'Remove image',
      'variantEditor.dropImage': 'Drop an image here',
      'variantEditor.imageSaveFirst': 'Save the variant before adding an image',
      'variantEditor.imageFailed': 'Could not upload the image',
      'variantEditor.imageRemoveConfirm': 'Remove this variant image?',
      'variantEditor.attributesTitle': 'Attributes',
      'variantEditor.createAttribute': 'Create attribute',
      'variantEditor.createAttributeHint':
        'The attribute is saved to the shared catalogue. After adding it, use Save to apply your changes to this product.',
      'variantEditor.attributeName': 'Attribute name',
      'variantEditor.attributeNameExample': 'For example: Capacity',
      'variantEditor.attributeValues': 'Values',
      'variantEditor.attributeValuesHint':
        'One value per line. These values will be selected for this product.',
      'variantEditor.attributeValuesExample': '30 ml\n50 ml',
      'variantEditor.createAndAddAttribute': 'Create and add',
      'variantEditor.cancelAttribute': 'Cancel',
      'variantEditor.attributeNameRequired': 'Enter an attribute name.',
      'variantEditor.attributeNameDuplicate':
        'This attribute name already exists. Select the existing attribute or use another name.',
      'variantEditor.attributeValuesRequired': 'Enter at least one value.',
      'variantEditor.attributeValuesDuplicate': 'Values must not be repeated.',
      'variantEditor.attributeValuesInvalid': 'Check the attribute values.',
      'variantEditor.attributeCreateFailed': 'Could not create the attribute',
      'variantEditor.attributeRetryHint': 'Your input has been kept. Please try again.',
      'variantEditor.stepAttributes': 'Step 1',
      'variantEditor.stepVariants': 'Step 2',
      'variantEditor.attributesHint': 'Choose attributes and tick the values this product is sold in.',
      'variantEditor.attributesEmpty': 'No attributes yet',
      'variantEditor.attributesEmptyHint':
        'Find or create an attribute such as Color or Size in “Add attribute…”.',
      'variantEditor.addAttribute': 'Add attribute…',
      'variantEditor.removeAttributeNamed': 'Remove attribute {name}',
      'variantEditor.selectAll': 'Select all',
      'variantEditor.valuesSelected': '{count} of {total} values selected',
      'variantEditor.valuesNone': 'No values selected — this attribute adds no variants yet.',
      'variantEditor.noVariantHint': 'Describes the product only; creates no variants.',
      'variantEditor.priceExtrasSet': 'Price extras: {list}',
      'variantEditor.priceExtrasNone': 'Price extras: none',
      'variantEditor.invalidNumber': 'Enter a valid number.',
      'variantEditor.rowInvalid': 'Invalid number',
      'variantEditor.appliesTo': 'Applies to {count} variants',
      'variantEditor.noVariant': 'No variants',
      'variantEditor.variantsTitle': 'Variants',
      'variantEditor.variantsCount': '{active} on sale / {total} variants',
      'variantEditor.variantsEmpty': 'No variants yet',
      'variantEditor.variantsEmptyHint': 'Every combination has a variant. You can still add one by hand.',
      'variantEditor.variantsNeedAttributes': 'Add an attribute with values above to create variants.',
      'variantEditor.generate': 'Create {count} variants',
      'variantEditor.missingMore': 'and {count} more',
      'variantEditor.defaultVariant': 'Default variant',
      'variantEditor.details': 'Details',
      'variantEditor.saving': 'Saving…',
      'variantEditor.summaryInvalid': 'Some numbers are not valid — fix them before saving.',
      'variantEditor.addVariant': 'Add variant',
      'variantEditor.activateAll': 'Sell all',
      'variantEditor.archiveAll': 'Archive all',
      'variantEditor.missing': '{count} combinations have no variant yet',
      'variantEditor.choose': 'Choose {name}',
      'variantEditor.archived': 'Archived',
      'variantEditor.duplicate': 'Same as #{row}',
      'variantEditor.incomplete': 'Attributes missing',
      'variantEditor.new': 'New',
      'variantEditor.edit': 'Edit',
      'variantEditor.collapse': 'Collapse',
      'variantEditor.remove': 'Drop',
      'variantEditor.archive': 'Archive',
      'variantEditor.restore': 'Sell again',
      'variantEditor.defaultCode': 'Internal reference (SKU)',
      'variantEditor.barcode': 'Barcode',
      'variantEditor.weight': 'Weight',
      'variantEditor.volume': 'Volume',
      'variantEditor.listPrice': 'Sales price',
      'variantEditor.summaryCreate': 'Will create {count} new variants',
      'variantEditor.summaryArchive': 'Will archive {count} variants',
      'variantEditor.summaryChanged': 'Unsaved changes.',
      'variantEditor.summaryDuplicate': 'Some variants share a combination — fix them before saving.',
      'variantEditor.reset': 'Discard changes',
      'variantEditor.save': 'Save attributes & variants',
      'variantEditor.saved': 'Saved: {created} created, {archived} archived.',
      'variantEditor.saveFailed': 'Could not save',
      'variantEditor.readOnly': 'You may only view attributes and variants.',
      'displayType.radio': 'Radio buttons',
      'displayType.pills': 'Pills',
      'displayType.select': 'Select',
      'displayType.color': 'Color',
      'displayType.multi': 'Multiple choice',
      'createVariant.always': 'Always create variants',
      'createVariant.no_variant': 'Never create variants',
    },
  },
  fills: {
    'product_backend:template.editor': `{% island "product.editor" %}`,
    'product_backend:variant.editor': `{% island "product.editor" %}`,
    'product_backend:media.upload': `{% island "product.media-upload" %}`,
    // A template opens on its own page (`/admin/product/templates/{id}`), rendered
    // client side by the KetSuite record runtime in its page presentation.
    'product_backend:template.page': `{% island "product.template-page" %}`,
    // Attributes still open in a client-side record modal: a closed host on every
    // admin page, opened by a link naming `product.attribute`.
    'backend:runtime': `{% island "product.attribute-modal" %}`,
  },
})

export { productsScreen, productDetailScreen } from './screens/index.ts'
export type { TemplateRow } from './screens/index.ts'
