import type { ModelDef } from '@ketvietlab/ketjs'

export const models: Record<string, ModelDef> = {
  Policy: {
    scope: 'company',
    fields: {
      id: 'id',
      timezone: 'text',
      lateGraceMinutes: 'int',
      earlyGraceMinutes: 'int',
      roundingMinutes: 'int',
      overtimeMinimumMinutes: 'int',
      updatedAt: 'datetime',
    },
  },
  Kiosk: {
    scope: 'company+branch',
    fields: {
      id: 'id',
      name: 'text',
      secretDigest: 'text',
      active: 'bool',
      createdAt: 'datetime',
      lastUsedAt: 'datetime?',
    },
    indexes: { digest: { fields: ['companyId', 'secretDigest'], unique: true } },
  },
  Credential: {
    scope: 'company',
    fields: {
      id: 'id',
      employeeId: 'ref:hr.Employee',
      pinHash: 'text?',
      qrDigest: 'text?',
      qrRequestKey: 'text?',
      qrIssuedAt: 'datetime?',
      active: 'bool',
      updatedAt: 'datetime',
    },
    indexes: {
      employee: { fields: ['companyId', 'employeeId'], unique: true },
      qr: { fields: ['companyId', 'qrDigest'], unique: true },
    },
  },
  Throttle: {
    scope: 'company',
    fields: { id: 'id', failures: 'int', blockedUntil: 'datetime?', updatedAt: 'datetime' },
  },
  ClockState: {
    scope: 'company',
    fields: {
      id: 'id',
      employeeId: 'ref:hr.Employee',
      openSessionId: 'ref:attendance.Session?',
      version: 'int',
    },
    indexes: { employee: { fields: ['companyId', 'employeeId'], unique: true } },
  },
  Punch: {
    scope: 'company+branch',
    fields: {
      id: 'id',
      employeeId: 'ref:hr.Employee',
      sessionId: 'ref:attendance.Session',
      kind: 'text',
      occurredAt: 'datetime',
      timezone: 'text',
      source: 'text',
      kioskId: 'ref:attendance.Kiosk?',
      actorUserId: 'ref:user.User?',
      networkFingerprint: 'text?',
      userAgent: 'text?',
      createdAt: 'datetime',
    },
    indexes: { employee_time: { fields: ['companyId', 'employeeId', 'occurredAt'] } },
  },
  Session: {
    scope: 'company+branch',
    fields: {
      id: 'id',
      employeeId: 'ref:hr.Employee',
      checkInPunchId: 'ref:attendance.Punch',
      checkOutPunchId: 'ref:attendance.Punch?',
      startAt: 'datetime',
      stopAt: 'datetime?',
      correctedStartAt: 'datetime?',
      correctedStopAt: 'datetime?',
      state: 'text',
      version: 'int',
    },
    indexes: { employee_start: { fields: ['companyId', 'employeeId', 'startAt'] } },
  },
  Correction: {
    scope: 'company',
    fields: {
      id: 'id',
      sessionId: 'ref:attendance.Session',
      employeeId: 'ref:hr.Employee',
      requestedStartAt: 'datetime',
      requestedStopAt: 'datetime',
      reason: 'text',
      state: 'text',
      requestedAt: 'datetime',
      decidedAt: 'datetime?',
      decidedBy: 'ref:user.User?',
      decisionNote: 'text?',
    },
    indexes: { session_state: { fields: ['companyId', 'sessionId', 'state'] } },
  },
  Overtime: {
    scope: 'company',
    fields: {
      id: 'id',
      employeeId: 'ref:hr.Employee',
      shiftId: 'ref:hr.Shift',
      minutes: 'int',
      state: 'text',
      decidedAt: 'datetime?',
      decidedBy: 'ref:user.User?',
      decisionNote: 'text?',
    },
    indexes: { shift: { fields: ['companyId', 'shiftId'], unique: true } },
  },
  WorkEntry: {
    scope: 'company',
    fields: {
      id: 'id',
      periodId: 'ref:attendance.Period',
      employeeId: 'ref:hr.Employee',
      shiftId: 'ref:hr.Shift',
      localDate: 'date',
      plannedMinutes: 'int',
      workedMinutes: 'int',
      lateMinutes: 'int',
      earlyMinutes: 'int',
      leaveMinutes: 'int',
      overtimeMinutes: 'int',
      approvedOvertimeMinutes: 'int',
      exception: 'text?',
      updatedAt: 'datetime',
    },
    indexes: { shift: { fields: ['companyId', 'periodId', 'shiftId'], unique: true } },
  },
  Period: {
    scope: 'company',
    fields: {
      id: 'id',
      month: 'text',
      timezone: 'text',
      state: 'text',
      version: 'int',
      lockedAt: 'datetime?',
      lockedBy: 'ref:user.User?',
      reopenedAt: 'datetime?',
      reopenedBy: 'ref:user.User?',
      reopenReason: 'text?',
    },
    indexes: { month: { fields: ['companyId', 'month'], unique: true } },
  },
}
