import { defineModule } from '@ketvietlab/ketjs'
import { customerRoutes } from './customer.ts'
import { staffRoutes } from './staff.ts'

export default defineModule({
  name: 'channel_api',
  version: '1.0.0',
  depends: ['website', 'user'],
  title: 'Channel API',
  summary: 'Contract API ổn định cho website, mobile, POS và tích hợp.',
  category: 'Kỹ thuật',
  reserves: ['/api/customer/v1/', '/api/staff/v1/', '/api/pos/v1/', '/api/integration/v1/', '/internal/v1/'],
  routes: { ...customerRoutes, ...staffRoutes },
  messages: {
    vi: {
      'app.title': 'Channel API',
      'app.summary': 'Contract API ổn định cho website, mobile, POS và tích hợp.',
      'app.category': 'Kỹ thuật',
      'error.methodNotAllowed': 'Phương thức không hợp lệ; hãy dùng {method}.',
      'error.internal': 'Không thể xử lý yêu cầu lúc này.',
      'error.unauthenticated': 'Bạn cần đăng nhập để tiếp tục.',
      'error.credentialConflict': 'Yêu cầu chứa nhiều thông tin đăng nhập không tương thích.',
      'error.forbidden': 'Bạn không có quyền thực hiện thao tác này.',
      'error.idempotencyRequired': 'Yêu cầu cần khóa chống xử lý lặp.',
      'error.idempotencyConflict': 'Khóa chống xử lý lặp đã được dùng cho một yêu cầu khác.',
      'error.idempotencyInFlight': 'Yêu cầu trước với khóa này đang được xử lý; hãy thử lại sau giây lát.',
      'error.invalidRefreshToken': 'Refresh token không hợp lệ hoặc đã hết hạn.',
      'error.originMismatch': 'Nguồn gửi yêu cầu không được phép.',
      'error.csrf': 'Yêu cầu bảo mật không hợp lệ. Vui lòng tải lại trang.',
      'error.rateLimited': 'Bạn thao tác quá nhanh. Vui lòng thử lại sau.',
      'error.invalidRequest': 'Nội dung yêu cầu không hợp lệ.',
      'error.fieldRequired': 'Trường bắt buộc chưa có giá trị.',
      'error.fieldUnknown': 'Trường này không thuộc hợp đồng của yêu cầu.',
      'error.fieldInvalid': 'Giá trị của trường không hợp lệ.',
      'unsupportedMediaType.error': 'Nội dung yêu cầu phải dùng application/json.',
      'payloadTooLarge.error': 'Nội dung yêu cầu vượt quá giới hạn cho phép.',
      'invalidBody.error': 'Nội dung JSON của yêu cầu không hợp lệ.',
    },
    en: {
      'app.title': 'Channel API',
      'app.summary': 'Stable contracts for websites, mobile, POS and integrations.',
      'app.category': 'Technical',
      'error.methodNotAllowed': 'Method not allowed; use {method}.',
      'error.internal': 'The request cannot be processed right now.',
      'error.unauthenticated': 'Sign in to continue.',
      'error.credentialConflict': 'The request contains conflicting credentials.',
      'error.forbidden': 'You do not have permission to perform this action.',
      'error.idempotencyRequired': 'This request requires an idempotency key.',
      'error.idempotencyConflict': 'The idempotency key was already used for another request.',
      'error.idempotencyInFlight': 'An earlier request with this key is still running; retry shortly.',
      'error.invalidRefreshToken': 'The refresh token is invalid or expired.',
      'error.originMismatch': 'The request origin is not allowed.',
      'error.csrf': 'The security token is invalid. Reload the page and try again.',
      'error.rateLimited': 'Too many attempts. Please try again later.',
      'error.invalidRequest': 'The request body does not match the contract.',
      'error.fieldRequired': 'This required field is missing.',
      'error.fieldUnknown': 'This field is not part of the request contract.',
      'error.fieldInvalid': 'This field has an invalid value.',
      'unsupportedMediaType.error': 'The request content type must be application/json.',
      'payloadTooLarge.error': 'The request body exceeds the allowed size.',
      'invalidBody.error': 'The request body is not valid JSON.',
    },
  },
})

export {
  CHANNEL_API_VERSION,
  authorizedChannelCapabilities,
  channelCredentialFailure,
  channelCommandId,
  defineChannelRoute,
  registerChannelCapabilityAuthorizer,
  registerChannelIdentity,
  registerChannelIdentityPresentation,
  registerChannelRealm,
  routesOf,
} from './core.ts'
export { openApiDocument } from './openapi.ts'
export type {
  ChannelAccount,
  AuthorizedChannelCapability,
  ChannelCapability,
  ChannelCapabilityAuthorizer,
  ChannelCapabilityAuthorizerRegistration,
  ChannelCredentialFailure,
  ChannelIdentities,
  ChannelIdentityFor,
  ChannelIdentityPresentation,
  ChannelIdentityPresentationResolver,
  CustomerIdentity,
  PosIdentity,
  StaffIdentity,
  ChannelAuth,
  ChannelIdentity,
  ChannelIdentityResolver,
  ChannelProfile,
  ChannelRequest,
  ChannelRouteSpec,
} from './core.ts'
