import type { ModelDef } from '@ketvietlab/ketjs'

export const models: Record<string, ModelDef> = {
  Sequence: {
    scope: 'company',
    fields: { id: 'id', nextNumber: 'int' },
  },
  Order: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      partnerId: 'ref:partner.Partner',
      partnerRef: 'text',
      state: 'text',
      locked: 'bool',
      dateOrder: 'datetime',
      dateApprove: 'datetime?',
      datePlanned: 'datetime',
      pickingTypeId: 'ref:stock.PickingType',
      currency: 'text',
      invoiceStatus: 'text',
      amountUntaxed: 'decimal',
      amountTax: 'decimal',
      amountTotal: 'decimal',
      notes: 'text?',
      revision: 'int?',
    },
    indexes: { company_name: { fields: ['companyId', 'name'], unique: true } },
  },
  OrderLine: {
    scope: 'company',
    fields: {
      id: 'id',
      orderId: 'ref:purchase.Order',
      productId: 'ref:product.Product',
      name: 'text',
      productQty: 'decimal',
      productUomId: 'ref:uom.Unit',
      priceUnit: 'decimal',
      discount: 'decimal',
      taxId: 'ref:account.Tax?',
      datePlanned: 'datetime',
      qtyReceived: 'decimal',
      qtyInvoiced: 'decimal',
      priceSubtotal: 'decimal',
      sequence: 'int',
    },
    indexes: { order_sequence: { fields: ['companyId', 'orderId', 'sequence'] } },
  },
  SupplierInfo: {
    scope: 'company',
    fields: {
      id: 'id',
      partnerId: 'ref:partner.Partner',
      productTemplateId: 'ref:product.Template',
      productId: 'ref:product.Product?',
      productUomId: 'ref:uom.Unit',
      productName: 'text?',
      productCode: 'text?',
      minQty: 'decimal',
      price: 'decimal',
      discount: 'decimal',
      delay: 'int',
      sequence: 'int',
      dateStart: 'datetime?',
      dateEnd: 'datetime?',
    },
  },
}
