import { defineModule } from '@ketvietlab/ketjs'
import { functions } from './functions.ts'
import { islands } from './islands.ts'
import { menus } from './menus.ts'
import { routes } from './routes.ts'

export default defineModule({
  name: 'partner_backend',
  version: '0.1.0',
  depends: ['partner', 'address', 'backend'],
  title: 'Danh bạ đối tác',
  summary: 'Quản lý khách hàng, nhà cung cấp, liên hệ và địa chỉ.',
  category: 'Bán hàng',
  assets: new URL('./client/', import.meta.url),
  styles: ['address.css', 'partner.css'],
  islands,
  routes,
  menus,
  functions,
  joints: {
    'record.actions': { props: { partnerId: 'id', locale: 'text?' } },
    'record.salesActions': {
      props: { partnerId: 'id', lang: 'text' },
      multiple: true,
    },
    'record.collaboration': {
      props: { resModel: 'text', resId: 'id', lang: 'text' },
      multiple: true,
    },
    'address.form': {
      props: {
        action: 'text',
        address: 'json',
        countries: 'json',
        provinces: 'json',
        provinceId: 'id?',
        divisions: 'json',
        uses: 'json',
        labels: 'json',
        submitLabel: 'text',
        defaultCountry: 'text?',
      },
    },
  },
  fills: { 'partner_backend:address.form': `{% island "partner.address-form" %}` },
  messages: {
    vi: {
      'app.title': 'Danh bạ đối tác',
      'app.summary': 'Quản lý khách hàng, nhà cung cấp, liên hệ và địa chỉ.',
      'app.category': 'Bán hàng',
      'menu.app': 'Đối tác',
      'menu.directory': 'Danh bạ',
      'screen.title': 'Đối tác',
      'screen.description': 'Quản lý khách hàng, nhà cung cấp và liên hệ trong một danh bạ thống nhất.',
      'screen.results': '{count} đối tác',
      'screen.empty': 'Chưa có đối tác nào',
      'screen.emptyHint': 'Tạo khách hàng, nhà cung cấp hoặc liên hệ đầu tiên.',
      'filter.customers': 'Khách hàng',
      'filter.suppliers': 'Nhà cung cấp',
      'filter.includeArchived': 'Gồm đã lưu trữ',
      'filter.activeOnly': 'Chỉ đang hoạt động',
      'groupBy.kind': 'Loại đối tác',
      'groupBy.state': 'Trạng thái',
      'search.label': 'Tìm và lọc đối tác',
      'search.placeholder': 'Tìm theo tên, email hoặc điện thoại…',
      'action.create': 'Tạo đối tác',
      'action.save': 'Lưu thông tin',
      'action.cancel': 'Hủy',
      'action.saveRoles': 'Lưu vai trò',
      'action.saveAddress': 'Lưu địa chỉ',
      'action.addAddress': 'Thêm địa chỉ',
      'action.saveTerms': 'Lưu điều khoản',
      'action.archive': 'Lưu trữ đối tác',
      'action.restore': 'Khôi phục đối tác',
      'action.bulkArchive': 'Lưu trữ đã chọn',
      'action.bulkRestore': 'Khôi phục đã chọn',
      'action.email': 'Gửi email',
      'action.call': 'Gọi điện',
      'action.more': 'Thêm thao tác',
      'create.title': 'Tạo đối tác',
      'create.subtitle': 'Tạo hồ sơ đối tác và thông tin liên hệ.',
      'create.actions': 'Thao tác tạo đối tác',
      'detail.identity': 'Thông tin chính',
      'detail.identityHint': 'Thông tin nhận diện, phân loại và liên hệ của đối tác.',
      'detail.actions': 'Thao tác đối tác',
      'collaboration.label': 'Trao đổi và hoạt động của đối tác',
      'field.name': 'Tên',
      'field.kind': 'Loại',
      'field.parent': 'Tổ chức cha',
      'relation.parents': 'Quản lý tổ chức',
      'field.ref': 'Mã đối tác',
      'field.vat': 'Mã số thuế',
      'field.email': 'Email',
      'field.phone': 'Điện thoại',
      'field.lang': 'Ngôn ngữ',
      'field.state': 'Trạng thái',
      'state.active': 'Đang hoạt động',
      'state.archived': 'Đã lưu trữ',
      'state.title': 'Trạng thái hồ sơ',
      'table.selectAll': 'Chọn tất cả dòng',
      'table.selectRow': 'Chọn dòng',
      'table.sortAscending': 'Đã sắp xếp tăng dần',
      'table.sortDescending': 'Đã sắp xếp giảm dần',
      'table.previousPage': 'Trang trước',
      'table.nextPage': 'Trang sau',
      'table.loading': 'Đang tải…',
      'table.loadError': 'Không tải được danh sách',
      'table.retry': 'Thử lại',
      'roles.title': 'Vai trò nghiệp vụ',
      'roles.hint': 'Một đối tác có thể đồng thời là khách hàng, nhà cung cấp hoặc nhân viên.',
      'addresses.title': 'Địa chỉ',
      'addresses.hint': 'Mỗi mục đích chỉ có một địa chỉ mặc định.',
      'address.new': 'Thêm địa chỉ',
      'address.use': 'Mục đích',
      'address.street': 'Địa chỉ',
      'address.street2': 'Dòng địa chỉ 2',
      'address.city': 'Tỉnh/Thành phố',
      'address.state': 'Tỉnh/Bang',
      'address.zip': 'Mã bưu chính',
      'address.country': 'Quốc gia',
      'address.country.VN': 'Việt Nam',
      'address.province': 'Tỉnh/Thành phố',
      'address.division': 'Xã/Phường/Đặc khu',
      'address.locality': 'Khu vực/Thôn/Tổ dân phố',
      'address.localityHint': 'Không bắt buộc',
      'address.chooseProvince': 'Chọn tỉnh/thành phố',
      'address.chooseDivision': 'Chọn xã/phường/đặc khu',
      'address.loading': 'Đang tải…',
      'address.loadError': 'Không tải được địa giới',
      'address.catalogMissing': 'Catalog địa giới chưa được cài. Hãy cài trong Cấu hình → Dữ liệu địa chỉ.',
      'address.previewHint': 'Bản xem trước địa chỉ sẽ hiển thị sau khi lưu.',
      'address.default': 'Mặc định',
      'terms.title': 'Điều khoản theo công ty',
      'terms.hint': 'Hạn mức và ghi chú áp dụng cho công ty đang hoạt động.',
      'terms.creditLimit': 'Hạn mức tín dụng',
      'terms.note': 'Ghi chú',
      'error.notFound': 'Không tìm thấy đối tác.',
    },
    en: {
      'app.title': 'Partner directory',
      'app.summary': 'Manage customers, suppliers, contacts and addresses.',
      'app.category': 'Sales',
      'menu.app': 'Partners',
      'menu.directory': 'Directory',
      'screen.title': 'Partners',
      'screen.description': 'Manage customers, suppliers and contacts in one unified directory.',
      'screen.results': '{count} partners',
      'screen.empty': 'No partners yet',
      'screen.emptyHint': 'Create the first customer, supplier or contact.',
      'filter.customers': 'Customers',
      'filter.suppliers': 'Suppliers',
      'filter.includeArchived': 'Include archived',
      'filter.activeOnly': 'Active only',
      'groupBy.kind': 'Partner type',
      'groupBy.state': 'Status',
      'search.label': 'Search and filter partners',
      'search.placeholder': 'Search by name, email or phone…',
      'action.create': 'Create partner',
      'action.save': 'Save information',
      'action.cancel': 'Cancel',
      'action.saveRoles': 'Save roles',
      'action.saveAddress': 'Save address',
      'action.addAddress': 'Add address',
      'action.saveTerms': 'Save terms',
      'action.archive': 'Archive partner',
      'action.restore': 'Restore partner',
      'action.bulkArchive': 'Archive selected',
      'action.bulkRestore': 'Restore selected',
      'action.email': 'Send email',
      'action.call': 'Call',
      'action.more': 'More actions',
      'create.title': 'Create partner',
      'create.subtitle': 'Create a partner profile and contact information.',
      'create.actions': 'Create partner actions',
      'detail.identity': 'Main information',
      'detail.identityHint': 'The partner identity, classification and contact information.',
      'detail.actions': 'Partner actions',
      'collaboration.label': 'Partner conversation and activities',
      'field.name': 'Name',
      'field.kind': 'Type',
      'field.parent': 'Parent organisation',
      'relation.parents': 'Manage organisations',
      'field.ref': 'Partner reference',
      'field.vat': 'Tax ID',
      'field.email': 'Email',
      'field.phone': 'Phone',
      'field.lang': 'Language',
      'field.state': 'Status',
      'state.active': 'Active',
      'state.archived': 'Archived',
      'state.title': 'Record status',
      'table.selectAll': 'Select all rows',
      'table.selectRow': 'Select row',
      'table.sortAscending': 'Sorted ascending',
      'table.sortDescending': 'Sorted descending',
      'table.previousPage': 'Previous page',
      'table.nextPage': 'Next page',
      'table.loading': 'Loading…',
      'table.loadError': 'Could not load the list',
      'table.retry': 'Retry',
      'roles.title': 'Business roles',
      'roles.hint': 'A partner may be a customer, supplier and employee at the same time.',
      'addresses.title': 'Addresses',
      'addresses.hint': 'Each purpose has one default address.',
      'address.new': 'Add address',
      'address.use': 'Purpose',
      'address.street': 'Street',
      'address.street2': 'Street line 2',
      'address.city': 'City',
      'address.state': 'State/Province',
      'address.zip': 'Postal code',
      'address.country': 'Country',
      'address.country.VN': 'Vietnam',
      'address.province': 'Province/City',
      'address.division': 'Commune/Ward/Special zone',
      'address.locality': 'Locality/Village',
      'address.localityHint': 'Optional',
      'address.chooseProvince': 'Choose a province or city',
      'address.chooseDivision': 'Choose a commune, ward, or special zone',
      'address.loading': 'Loading…',
      'address.loadError': 'Could not load administrative divisions',
      'address.catalogMissing':
        'The administrative catalog is not installed. Install it under Settings → Address data.',
      'address.previewHint': 'The formatted address preview appears after saving.',
      'address.default': 'Default',
      'terms.title': 'Company terms',
      'terms.hint': 'The limit and note apply to the active company.',
      'terms.creditLimit': 'Credit limit',
      'terms.note': 'Note',
      'error.notFound': 'Partner not found.',
    },
  },
})

export { newPartnerScreen, partnerFormScreen, partnersScreen } from './screens/index.ts'
export { partnerRelationControl } from './relation-control.ts'
