// Phase 1 of the `--demo-data` seed: CRM leads and opportunities.
//
// Each title names a real ask from a real (seeded) customer — not "Lead 01" —
// and is spread across the pipeline's real default stages
// (`crm-stage-new` / `-qualified` / `-proposition` / `-won` / `-lost`, seeded by
// `ensureCrmDefaults` the first time a case is saved) so the kanban and the list
// both show genuine variety instead of everything sitting in one column.

import type { Call } from './util.ts'

type CaseSeed = {
  id: string
  kind: 'lead' | 'opportunity'
  name: string
  partnerId: string
  stageId: string
  priority: '0' | '1' | '2' | '3'
  expectedRevenue?: string
  description: string
  close?: 'won' | 'lost'
  lostReason?: string
}

const STAGE = {
  new: 'crm-stage-new',
  qualified: 'crm-stage-qualified',
  proposition: 'crm-stage-proposition',
  won: 'crm-stage-won',
  lost: 'crm-stage-lost',
} as const

const CASES: CaseSeed[] = [
  {
    id: 'demo-case-01',
    kind: 'lead',
    name: 'Hỏi báo giá đồng phục 200 bộ – Đại Phát',
    partnerId: 'demo-partner-dai-phat',
    stageId: STAGE.new,
    priority: '1',
    description: 'Khách để lại thông tin qua form website, cần báo giá cho công trường mới.',
  },
  {
    id: 'demo-case-02',
    kind: 'lead',
    name: 'PPE xưởng dệt theo quý – Sông Hồng',
    partnerId: 'demo-partner-song-hong',
    stageId: STAGE.qualified,
    priority: '2',
    description: 'Đã xác nhận nhu cầu găng tay và ủng chống hóa chất cho 3 chuyền sản xuất.',
  },
  {
    id: 'demo-case-03',
    kind: 'lead',
    name: 'Catalogue quà tặng – Biển Xanh',
    partnerId: 'demo-partner-bien-xanh',
    stageId: STAGE.new,
    priority: '0',
    description: 'Chuẩn bị quà cuối năm cho đối tác lữ hành.',
  },
  {
    id: 'demo-case-04',
    kind: 'lead',
    name: 'Mũ bảo hộ công trường mới – Việt Nhật',
    partnerId: 'demo-partner-viet-nhat',
    stageId: STAGE.qualified,
    priority: '2',
    description: 'Công trường mới cần trang bị PPE cho 80 công nhân trong tháng tới.',
  },
  {
    id: 'demo-case-05',
    kind: 'lead',
    name: 'Áo mưa công trường – Hồng Hà',
    partnerId: 'demo-partner-hong-ha',
    stageId: STAGE.new,
    priority: '1',
    description: 'Cần trước mùa mưa, số lượng chưa xác định.',
  },
  {
    id: 'demo-case-06',
    kind: 'lead',
    name: 'Thẻ nhân viên chi nhánh mới – Thái Sơn',
    partnerId: 'demo-partner-thai-son',
    stageId: STAGE.new,
    priority: '0',
    description: 'Mở thêm chi nhánh, cần thẻ và dây đeo đồng bộ với chi nhánh cũ.',
  },
  {
    id: 'demo-case-07',
    kind: 'lead',
    name: 'Demo dây đai an toàn – Tây Bắc',
    partnerId: 'demo-partner-tay-bac',
    stageId: STAGE.qualified,
    priority: '2',
    description: 'Đội khai thác khoáng sản cần đánh giá trước khi ký hợp đồng khung.',
  },
  {
    id: 'demo-case-08',
    kind: 'lead',
    name: 'Bình giữ nhiệt in logo – Mặt Trời Việt',
    partnerId: 'demo-partner-mat-troi-viet',
    stageId: STAGE.new,
    priority: '0',
    description: 'Dự kiến làm quà tặng khách hàng dịp khai trương dự án điện mặt trời.',
  },
  {
    id: 'demo-case-09',
    kind: 'lead',
    name: 'Đồng phục lễ tân khách sạn – Biển Xanh',
    partnerId: 'demo-partner-bien-xanh',
    stageId: STAGE.qualified,
    priority: '1',
    description: 'Khách sạn chuẩn bị khai trương, cần đồng phục cho 15 nhân sự lễ tân.',
  },
  {
    id: 'demo-case-10',
    kind: 'lead',
    name: 'Khẩu trang số lượng lớn – An Bình',
    partnerId: 'demo-partner-an-binh',
    stageId: STAGE.new,
    priority: '1',
    description: 'Nhà máy thực phẩm cần trang bị định kỳ hàng tháng.',
  },
  {
    id: 'demo-case-11',
    kind: 'lead',
    name: 'Ủng mũi thép – Thép Việt',
    partnerId: 'demo-partner-thep-viet',
    stageId: STAGE.new,
    priority: '1',
    description: 'Đối tác sản xuất thép cần gấp cho ca làm việc mới.',
  },
  {
    id: 'demo-case-12',
    kind: 'lead',
    name: 'In logo lên balo – Minh Đức',
    partnerId: 'demo-partner-minh-duc',
    stageId: STAGE.qualified,
    priority: '0',
    description: 'Muốn đặt balo đồng bộ cho đội kỹ thuật hiện trường.',
  },
  {
    id: 'demo-case-13',
    kind: 'lead',
    name: 'Bộ sơ cứu cho tổ đội – Hòa Bình',
    partnerId: 'demo-partner-hoa-binh',
    stageId: STAGE.new,
    priority: '2',
    description: 'Yêu cầu tuân thủ quy định an toàn lao động mới ban hành.',
  },
  {
    id: 'demo-case-14',
    kind: 'lead',
    name: 'Mẫu vải áo khoác vận hành – Phương Nam',
    partnerId: 'demo-partner-phuong-nam',
    stageId: STAGE.new,
    priority: '1',
    description: 'Muốn xem mẫu thật trước khi quyết định đơn hàng nội thất công trường.',
  },

  {
    id: 'demo-case-15',
    kind: 'opportunity',
    name: 'Đồng phục công trường GĐ1 – Đại Phát',
    partnerId: 'demo-partner-dai-phat',
    stageId: STAGE.proposition,
    priority: '3',
    expectedRevenue: '185000000',
    description: 'Đã gửi báo giá cho 300 bộ đồng phục và gile phản quang, chờ duyệt ngân sách.',
  },
  {
    id: 'demo-case-16',
    kind: 'opportunity',
    name: 'Hợp đồng PPE theo quý – Sông Hồng',
    partnerId: 'demo-partner-song-hong',
    stageId: STAGE.qualified,
    priority: '2',
    expectedRevenue: '96000000',
    description: 'Đàm phán hợp đồng cung cấp găng tay và ủng theo quý cho 3 nhà máy.',
  },
  {
    id: 'demo-case-17',
    kind: 'opportunity',
    name: 'Quà tặng cuối năm – Biển Xanh',
    partnerId: 'demo-partner-bien-xanh',
    stageId: STAGE.proposition,
    priority: '1',
    expectedRevenue: '42000000',
    description: 'Đã chốt đơn ô cầm tay và sổ tay in logo cho 400 đối tác.',
    close: 'won',
  },
  {
    id: 'demo-case-18',
    kind: 'opportunity',
    name: 'Mũ bảo hộ & kính bụi – Việt Nhật',
    partnerId: 'demo-partner-viet-nhat',
    stageId: STAGE.proposition,
    priority: '2',
    expectedRevenue: '58000000',
    description: 'Khách đã duyệt mẫu, chờ xác nhận số lượng cuối cùng.',
  },
  {
    id: 'demo-case-19',
    kind: 'opportunity',
    name: 'Áo mưa & ủng thi công – Hồng Hà',
    partnerId: 'demo-partner-hong-ha',
    stageId: STAGE.qualified,
    priority: '1',
    expectedRevenue: '31000000',
    description: 'Chờ khách xác nhận cỡ số trước khi lên đơn chính thức.',
  },
  {
    id: 'demo-case-20',
    kind: 'opportunity',
    name: 'Thẻ nhân viên toàn hệ thống – Thái Sơn',
    partnerId: 'demo-partner-thai-son',
    stageId: STAGE.proposition,
    priority: '1',
    expectedRevenue: '18000000',
    description: 'Khách chọn nhà cung cấp khác vì thời gian giao hàng ngắn hơn.',
    close: 'lost',
    lostReason: 'Chọn nhà cung cấp khác có thời gian giao hàng nhanh hơn',
  },
  {
    id: 'demo-case-21',
    kind: 'opportunity',
    name: 'Dây đai an toàn đội khai thác – Tây Bắc',
    partnerId: 'demo-partner-tay-bac',
    stageId: STAGE.proposition,
    priority: '3',
    expectedRevenue: '272000000',
    description: 'Đã ký hợp đồng cung cấp 400 bộ dây đai an toàn kèm huấn luyện sử dụng.',
    close: 'won',
  },
  {
    id: 'demo-case-22',
    kind: 'opportunity',
    name: 'Bình nước & ô cầm tay – Mặt Trời Việt',
    partnerId: 'demo-partner-mat-troi-viet',
    stageId: STAGE.new,
    priority: '1',
    expectedRevenue: '26000000',
    description: 'Mới tiếp nhận nhu cầu, chưa gửi báo giá chi tiết.',
  },
  {
    id: 'demo-case-23',
    kind: 'opportunity',
    name: 'Đồng phục lễ tân khách sạn mới – Biển Xanh',
    partnerId: 'demo-partner-bien-xanh',
    stageId: STAGE.proposition,
    priority: '2',
    expectedRevenue: '33000000',
    description: 'Đã gửi mẫu vải, chờ khách chọn màu chính thức trước khai trương.',
  },
  {
    id: 'demo-case-24',
    kind: 'opportunity',
    name: 'Khẩu trang & nút tai theo năm – An Bình',
    partnerId: 'demo-partner-an-binh',
    stageId: STAGE.qualified,
    priority: '2',
    expectedRevenue: '64000000',
    description: 'Đàm phán mức giá cho hợp đồng cung cấp 12 tháng.',
  },
  {
    id: 'demo-case-25',
    kind: 'opportunity',
    name: 'Ủng mũi thép ca mới – Thép Việt',
    partnerId: 'demo-partner-thep-viet',
    stageId: STAGE.proposition,
    priority: '2',
    expectedRevenue: '89000000',
    description: 'Hoàn tất đơn hàng 260 đôi cho ca sản xuất mới mở.',
    close: 'won',
  },
  {
    id: 'demo-case-26',
    kind: 'opportunity',
    name: 'Balo & túi dụng cụ – Minh Đức',
    partnerId: 'demo-partner-minh-duc',
    stageId: STAGE.proposition,
    priority: '1',
    expectedRevenue: '21000000',
    description: 'Khách yêu cầu chỉnh lại thiết kế logo trước khi chốt đơn.',
  },
  {
    id: 'demo-case-27',
    kind: 'opportunity',
    name: 'PPE công trường – Hòa Bình',
    partnerId: 'demo-partner-hoa-binh',
    stageId: STAGE.qualified,
    priority: '2',
    expectedRevenue: '47000000',
    description: 'Đang chờ phòng an toàn lao động phê duyệt danh mục thiết bị.',
  },
  {
    id: 'demo-case-28',
    kind: 'opportunity',
    name: 'Nội thất & đồng phục khai trương – Phương Nam',
    partnerId: 'demo-partner-phuong-nam',
    stageId: STAGE.proposition,
    priority: '1',
    expectedRevenue: '39000000',
    description: 'Ngân sách bị cắt giảm nên hoãn kế hoạch khai trương.',
    close: 'lost',
    lostReason: 'Khách hoãn ngân sách sang năm sau',
  },
  {
    id: 'demo-case-29',
    kind: 'opportunity',
    name: 'Găng tay cách điện – Hoàng Long',
    partnerId: 'demo-partner-hoang-long',
    stageId: STAGE.proposition,
    priority: '2',
    expectedRevenue: '52000000',
    description: 'Đã giao đủ số lượng cho đợt bảo trì định kỳ quý này.',
    close: 'won',
  },
  {
    id: 'demo-case-30',
    kind: 'opportunity',
    name: 'Đồng phục sự kiện hội chợ – Hoàng Long',
    partnerId: 'demo-partner-hoang-long',
    stageId: STAGE.new,
    priority: '0',
    expectedRevenue: '17000000',
    description: 'Mới nhận yêu cầu, cần xác định số lượng gian hàng tham gia.',
  },
  {
    id: 'demo-case-31',
    kind: 'opportunity',
    name: 'PPE xưởng cơ khí mới – Việt Nhật',
    partnerId: 'demo-partner-viet-nhat',
    stageId: STAGE.qualified,
    priority: '2',
    expectedRevenue: '73000000',
    description: 'Xưởng mới mở rộng, cần trang bị đồng bộ trong quý này.',
  },
  {
    id: 'demo-case-32',
    kind: 'opportunity',
    name: 'Yếm phản quang giao thông – Đại Phát',
    partnerId: 'demo-partner-dai-phat',
    stageId: STAGE.proposition,
    priority: '1',
    expectedRevenue: '14500000',
    description: 'Đã hoàn tất giao hàng cho đợt thi công giai đoạn 2.',
    close: 'won',
  },
  {
    id: 'demo-case-33',
    kind: 'opportunity',
    name: 'Nón bảo hiểm xe nâng – Sông Hồng',
    partnerId: 'demo-partner-song-hong',
    stageId: STAGE.proposition,
    priority: '1',
    expectedRevenue: '19500000',
    description: 'Đang thương lượng chiết khấu cho đơn hàng trên 100 sản phẩm.',
  },
  {
    id: 'demo-case-34',
    kind: 'opportunity',
    name: 'Đèn pin & nhiệt kế – Thái Sơn',
    partnerId: 'demo-partner-thai-son',
    stageId: STAGE.proposition,
    priority: '0',
    expectedRevenue: '11000000',
    description: 'Khách tự mua trực tiếp từ nhà sản xuất thiết bị.',
    close: 'lost',
    lostReason: 'Khách mua trực tiếp từ nhà sản xuất',
  },
  {
    id: 'demo-case-35',
    kind: 'opportunity',
    name: 'Áo khoác vận hành đồng bộ – Miền Trung',
    partnerId: 'demo-partner-mien-trung',
    stageId: STAGE.qualified,
    priority: '2',
    expectedRevenue: '61000000',
    description: 'Cần đồng phục mới đồng bộ nhận diện thương hiệu cho đội xe.',
  },
  {
    id: 'demo-case-36',
    kind: 'opportunity',
    name: 'Găng tay hàn & tạp dề – Việt Nhật',
    partnerId: 'demo-partner-viet-nhat',
    stageId: STAGE.new,
    priority: '1',
    expectedRevenue: '24000000',
    description: 'Mới liên hệ lại sau đợt mua hàng năm trước.',
  },
  {
    id: 'demo-case-37',
    kind: 'opportunity',
    name: 'Đồng phục khai trương chi nhánh – Thái Sơn',
    partnerId: 'demo-partner-thai-son',
    stageId: STAGE.proposition,
    priority: '2',
    expectedRevenue: '35000000',
    description: 'Đã hoàn tất đơn hàng cho lễ khai trương chi nhánh mới.',
    close: 'won',
  },
]

export async function seedCrm(call: Call): Promise<string[]> {
  const ids: string[] = []
  for (const item of CASES) {
    const saved = await call('crm.case.save', {
      id: item.id,
      kind: item.kind,
      name: item.name,
      partnerId: item.partnerId,
      stageId: item.stageId,
      priority: item.priority,
      description: item.description,
      idempotencyKey: `seed:${item.id}`,
      ...(item.expectedRevenue ? { expectedRevenue: item.expectedRevenue } : {}),
    })
    if (item.close === 'won') {
      await call('crm.case.markWon', {
        id: item.id,
        expectedVersion: Number(saved.version),
        idempotencyKey: `seed:${item.id}:won`,
      })
    } else if (item.close === 'lost') {
      await call('crm.case.markLost', {
        id: item.id,
        expectedVersion: Number(saved.version),
        lostReason: item.lostReason ?? 'Không còn phù hợp với nhu cầu hiện tại',
        idempotencyKey: `seed:${item.id}:lost`,
      })
    }
    ids.push(item.id)
  }
  return ids
}
