import type { ModelDef } from '@ketvietlab/ketjs'

export const models: Record<string, ModelDef> = {
  Department: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      parentId: 'ref:hr.Department?',
      managerEmployeeId: 'ref:hr.Employee?',
      active: 'bool',
    },
    indexes: { name: { fields: ['companyId', 'name'], unique: true } },
  },
  Job: {
    scope: 'company',
    fields: { id: 'id', name: 'text', active: 'bool' },
    indexes: { name: { fields: ['companyId', 'name'], unique: true } },
  },
  Employee: {
    scope: 'company',
    fields: {
      id: 'id',
      code: 'text',
      partnerId: 'ref:partner.Partner',
      userId: 'ref:user.User?',
      departmentId: 'ref:hr.Department?',
      jobId: 'ref:hr.Job?',
      homeBranchId: 'ref:company.Branch',
      timezone: 'text',
      startDate: 'date',
      endDate: 'date?',
      active: 'bool',
      createdAt: 'datetime',
      updatedAt: 'datetime',
    },
    indexes: {
      code: { fields: ['companyId', 'code'], unique: true },
      partner: { fields: ['companyId', 'partnerId'], unique: true },
      user: { fields: ['companyId', 'userId'], unique: true },
    },
  },
  ShiftTemplate: {
    scope: 'company+branch',
    fields: {
      id: 'id',
      code: 'text',
      name: 'text',
      startTime: 'text',
      endTime: 'text',
      breakMinutes: 'int',
      timezone: 'text',
      active: 'bool',
    },
    indexes: { code: { fields: ['companyId', 'code'], unique: true } },
  },
  Rotation: {
    scope: 'company',
    fields: { id: 'id', name: 'text', cycleWeeks: 'int', active: 'bool' },
    indexes: { name: { fields: ['companyId', 'name'], unique: true } },
  },
  RotationSlot: {
    scope: 'company',
    fields: {
      id: 'id',
      rotationId: 'ref:hr.Rotation',
      weekIndex: 'int',
      weekday: 'int',
      shiftTemplateId: 'ref:hr.ShiftTemplate',
    },
    indexes: {
      slot: { fields: ['companyId', 'rotationId', 'weekIndex', 'weekday'], unique: true },
    },
  },
  RotationAssignment: {
    scope: 'company+branch',
    fields: {
      id: 'id',
      employeeId: 'ref:hr.Employee',
      rotationId: 'ref:hr.Rotation',
      anchorDate: 'date',
      effectiveFrom: 'date',
      effectiveTo: 'date?',
      active: 'bool',
    },
    indexes: { employee_from: { fields: ['companyId', 'employeeId', 'effectiveFrom'] } },
  },
  Roster: {
    scope: 'company+branch',
    fields: {
      id: 'id',
      weekStart: 'date',
      state: 'text',
      version: 'int',
      publishedAt: 'datetime?',
      publishedBy: 'ref:user.User?',
      reopenedAt: 'datetime?',
      reopenedBy: 'ref:user.User?',
      reopenReason: 'text?',
    },
    indexes: { week: { fields: ['companyId', 'branchId', 'weekStart'], unique: true } },
  },
  Shift: {
    scope: 'company+branch',
    fields: {
      id: 'id',
      rosterId: 'ref:hr.Roster',
      employeeId: 'ref:hr.Employee',
      shiftTemplateId: 'ref:hr.ShiftTemplate?',
      localDate: 'date',
      startAt: 'datetime',
      stopAt: 'datetime',
      timezone: 'text',
      breakMinutes: 'int',
      state: 'text',
      source: 'text',
      sourceKey: 'text?',
      note: 'text?',
      version: 'int',
    },
    indexes: {
      source: { fields: ['companyId', 'sourceKey'], unique: true },
      employee_start: { fields: ['companyId', 'employeeId', 'startAt'] },
    },
  },
  LeaveType: {
    scope: 'company',
    fields: { id: 'id', code: 'text', name: 'text', paid: 'bool', active: 'bool' },
    indexes: { code: { fields: ['companyId', 'code'], unique: true } },
  },
  LeaveAllocation: {
    scope: 'company',
    fields: {
      id: 'id',
      employeeId: 'ref:hr.Employee',
      leaveTypeId: 'ref:hr.LeaveType',
      year: 'int',
      days: 'decimal',
      note: 'text?',
    },
    indexes: {
      employee_type_year: {
        fields: ['companyId', 'employeeId', 'leaveTypeId', 'year'],
        unique: true,
      },
    },
  },
  LeaveRequest: {
    scope: 'company',
    fields: {
      id: 'id',
      employeeId: 'ref:hr.Employee',
      leaveTypeId: 'ref:hr.LeaveType',
      dateFrom: 'date',
      dateTo: 'date',
      portion: 'text',
      requestedDays: 'decimal',
      reason: 'text?',
      state: 'text',
      requestedAt: 'datetime',
      decidedAt: 'datetime?',
      decidedBy: 'ref:user.User?',
      decisionNote: 'text?',
    },
    indexes: { employee_date: { fields: ['companyId', 'employeeId', 'dateFrom', 'dateTo'] } },
  },
}
