import type { CatalogueMaturity, CatalogueState } from './groups.ts'

export type ComponentRegistration = {
  name: string
  owner: string
  source: string
  groupId: string
  specimenId: string
  maturity: CatalogueMaturity
  states: readonly CatalogueState[]
}

const states = ['default', 'responsive'] as const
const entry = (
  name: string,
  owner: string,
  source: string,
  groupId: string,
  specimenId: string,
  maturity: CatalogueMaturity = 'stable',
  componentStates: readonly CatalogueState[] = states,
): ComponentRegistration => ({
  name,
  owner,
  source,
  groupId,
  specimenId,
  maturity,
  states: componentStates,
})

export const componentRegistry: readonly ComponentRegistration[] = [
  entry('Icon', 'Icons', 'primitives/icon', 'status', 'typography-icons'),
  entry('Link', 'Actions', 'primitives/actions', 'actions', 'button'),
  entry('ReorderList', 'Forms', 'interactions/reorder-list', 'fields', 'reorder-list'),
  entry('ActionGroup', 'Actions', 'primitives/actions', 'actions', 'button'),
  entry('Button', 'Actions', 'primitives/actions', 'actions', 'button', 'stable', [
    'default',
    'disabled',
    'loading',
  ]),
  entry('IconButton', 'Actions', 'primitives/actions', 'actions', 'action-sizes'),
  entry('LinkButton', 'Actions', 'primitives/actions', 'actions', 'button'),
  entry('Avatar', 'Status', 'primitives/status', 'status', 'identity'),
  entry('Badge', 'Status', 'primitives/status', 'status', 'badges'),
  entry('CodeBlock', 'Status', 'primitives/status', 'status', 'code-block'),
  entry('Text', 'Status', 'primitives/status', 'status', 'badges'),
  entry('MediaLabel', 'Status', 'primitives/status', 'status', 'identity'),
  entry('Code', 'Status', 'primitives/status', 'status', 'identity'),
  entry('CountBadge', 'Status', 'primitives/status', 'status', 'badges'),
  entry('Tag', 'Status', 'primitives/status', 'status', 'badges'),
  entry('EmptyState', 'Feedback', 'primitives/feedback', 'feedback', 'empty-loading', 'stable', [
    'empty',
    'responsive',
  ]),
  entry('LoadingState', 'Feedback', 'primitives/feedback', 'feedback', 'empty-loading', 'stable', [
    'loading',
    'responsive',
  ]),
  entry('Notice', 'Feedback', 'primitives/feedback', 'feedback', 'notice'),
  entry('Field', 'Forms', 'primitives/field', 'fields', 'field', 'stable', [
    'default',
    'disabled',
    'invalid',
    'responsive',
  ]),
  entry('Breadcrumbs', 'Navigation', 'primitives/navigation', 'navigation', 'navigation-items'),
  entry('NavItem', 'Navigation', 'primitives/navigation', 'navigation', 'navigation-items'),
  entry('NavList', 'Navigation', 'primitives/navigation', 'navigation', 'navigation-items'),
  entry('Tab', 'Navigation', 'primitives/navigation', 'navigation', 'navigation-items'),
  entry('TabPanel', 'Navigation', 'primitives/navigation', 'navigation', 'navigation-items'),
  entry('TabbedView', 'Navigation', 'primitives/navigation', 'navigation', 'navigation-items'),
  entry('Tabs', 'Navigation', 'primitives/navigation', 'navigation', 'navigation-items'),
  entry('Progress', 'Feedback', 'primitives/progress', 'navigation', 'progress'),
  entry('Stack', 'Layout', 'layouts/layout', 'layouts', 'surface-section'),
  entry('Inline', 'Layout', 'layouts/layout', 'layouts', 'surface-section'),
  entry('Grid', 'Layout', 'layouts/layout', 'layouts', 'surface-section'),
  entry('CardGrid', 'Layout', 'layouts/layout', 'layouts', 'content-card'),
  entry('Surface', 'Layout', 'layouts/layout', 'layouts', 'surface-section'),
  entry('Disclosure', 'Layout', 'layouts/layout', 'layouts', 'disclosure'),
  entry('Section', 'Layout', 'layouts/layout', 'layouts', 'surface-section'),
  entry('ContentCard', 'Layout', 'layouts/layout', 'layouts', 'content-card'),
  entry('KanbanCard', 'Layout', 'layouts/layout', 'layouts', 'kanban-card'),
  entry('KanbanGrid', 'Layout', 'layouts/layout', 'layouts', 'kanban-card'),
  entry('Metric', 'Layout', 'layouts/layout', 'layouts', 'surface-section'),
  entry('AppShell', 'Shell', 'layouts/shell', 'application-structure', 'app-shell'),
  entry('AppBrand', 'Shell', 'layouts/shell', 'application-structure', 'app-shell'),
  entry('AppTopbar', 'Shell', 'layouts/shell', 'application-structure', 'app-shell'),
  entry(
    'NavigationToggle',
    'Navigation',
    'layouts/app-navigation',
    'application-structure',
    'app-navigation',
  ),
  entry('Page', 'Shell', 'layouts/shell', 'application-structure', 'app-shell'),
  entry('PageHeader', 'Shell', 'layouts/shell', 'application-structure', 'app-shell'),
  entry('RecordCanvas', 'Shell', 'layouts/shell', 'application-structure', 'record-page'),
  entry('RecordSection', 'Shell', 'layouts/shell', 'application-structure', 'record-page'),
  entry('AppNavigation', 'Navigation', 'layouts/app-navigation', 'application-structure', 'app-navigation'),
  entry(
    'NavigationHeader',
    'Navigation',
    'layouts/app-navigation',
    'application-structure',
    'app-navigation',
  ),
  entry('NavigationGroup', 'Navigation', 'layouts/app-navigation', 'application-structure', 'app-navigation'),
  entry(
    'NavigationItem',
    'Navigation',
    'layouts/app-navigation',
    'application-structure',
    'app-navigation',
    'stable',
    ['default', 'selected', 'responsive'],
  ),
  entry(
    'NavigationTrigger',
    'Navigation',
    'layouts/app-navigation',
    'application-structure',
    'app-navigation',
  ),
  entry(
    'NavigationDrawer',
    'Navigation',
    'layouts/app-navigation',
    'application-structure',
    'app-navigation',
  ),
  entry('DataTable', 'Data display', 'patterns/data-table', 'patterns', 'data-table'),
  entry('BulkActions', 'Data operations', 'patterns/list-chrome', 'patterns', 'list-chrome'),
  entry('ListChrome', 'Data operations', 'patterns/list-chrome', 'patterns', 'list-chrome'),
  entry('PagerBar', 'Data operations', 'patterns/list-chrome', 'patterns', 'list-chrome'),
  entry('ListPage', 'Page patterns', 'patterns/list-page', 'application-structure', 'list-page'),
  entry('RecordPage', 'Page patterns', 'patterns/record-page', 'application-structure', 'record-page'),
  entry(
    'WorkspacePage',
    'Page patterns',
    'patterns/workspace-page',
    'application-structure',
    'workspace-flow',
  ),
  entry('FormPage', 'Page recipes', 'patterns/form-page', 'patterns', 'form-page', 'deprecated'),
  entry(
    'DashboardPage',
    'Page recipes',
    'patterns/dashboard-page',
    'patterns',
    'dashboard-page',
    'deprecated',
  ),
  entry('BoardPage', 'Page recipes', 'patterns/board-page', 'patterns', 'board-page', 'deprecated'),
  entry('ModalSheet', 'Overlays', 'patterns/modal-sheet', 'patterns', 'modal-sheet'),
  entry('Pipeline', 'Data display', 'patterns/pipeline', 'patterns', 'pipeline'),
  entry('RecordForm', 'Forms', 'patterns/record-form', 'patterns', 'record-form'),
  entry('Menu', 'Actions', 'interactions/menu', 'interactions', 'menu'),
  entry('ContextButton', 'Navigation', 'interactions/context-button', 'interactions', 'context-button'),
  entry('ActionMenu', 'Actions', 'interactions/menu', 'interactions', 'grouped-action-menu'),
  entry('Popover', 'Overlays', 'interactions/popover', 'interactions', 'popover'),
  entry('Tooltip', 'Overlays', 'interactions/tooltip', 'interactions', 'popover'),
  entry('Dialog', 'Overlays', 'interactions/dialog', 'interactions', 'dialog'),
  entry('ConfirmDialog', 'Overlays', 'interactions/dialog', 'interactions', 'dialog'),
  entry('Toast', 'Feedback', 'interactions/toast', 'interactions', 'feedback-runtime'),
  entry('ToastRegion', 'Feedback', 'interactions/toast', 'interactions', 'feedback-runtime'),
  entry('Spinner', 'Feedback', 'interactions/spinner', 'interactions', 'feedback-runtime'),
  entry('Skeleton', 'Feedback', 'interactions/skeleton', 'interactions', 'feedback-runtime'),
  entry(
    'createSearchFilterView',
    'Data operations',
    'interactions/search-filter',
    'interactions',
    'search-filter',
  ),
  entry(
    'searchFilterRuleLabel',
    'Data operations',
    'interactions/search-filter',
    'interactions',
    'search-filter',
  ),
  entry('searchFilter', 'Data operations', 'interactions/search-filter', 'interactions', 'search-filter'),
  entry('createKetTableView', 'Data operations', 'interactions/ket-table', 'interactions', 'ket-table'),
  entry('ketTable', 'Data operations', 'interactions/ket-table', 'interactions', 'ket-table'),
  entry('KetTable', 'Data operations', 'interactions/ket-table', 'interactions', 'ket-table'),
  entry(
    'createRelationSelectView',
    'Forms',
    'interactions/relation-select',
    'interactions',
    'relation-select',
  ),
  entry('relationSelect', 'Forms', 'interactions/relation-select', 'interactions', 'relation-select'),
  entry('createLightbox', 'Overlays', 'interactions/lightbox', 'interactions', 'lightbox'),
  entry('createLightboxView', 'Overlays', 'interactions/lightbox', 'interactions', 'lightbox'),
  entry('lightbox', 'Overlays', 'interactions/lightbox', 'interactions', 'lightbox'),
  entry('LightboxThumb', 'Overlays', 'interactions/lightbox', 'interactions', 'lightbox'),
  entry('TextField', 'Forms', 'forms/scalar-fields', 'form-controls', 'scalar-fields'),
  entry('TextArea', 'Forms', 'forms/scalar-fields', 'form-controls', 'scalar-fields'),
  entry('NumberField', 'Forms', 'forms/scalar-fields', 'form-controls', 'scalar-fields'),
  entry('MoneyField', 'Forms', 'forms/scalar-fields', 'form-controls', 'scalar-fields'),
  entry('SearchField', 'Forms', 'forms/scalar-fields', 'form-controls', 'scalar-fields'),
  entry('Checkbox', 'Forms', 'forms/scalar-fields', 'form-controls', 'selection-controls'),
  entry('CheckboxGroup', 'Forms', 'forms/scalar-fields', 'form-controls', 'selection-controls'),
  entry('RadioGroup', 'Forms', 'forms/scalar-fields', 'form-controls', 'selection-controls'),
  entry('Switch', 'Forms', 'forms/scalar-fields', 'form-controls', 'selection-controls'),
  entry('Select', 'Forms', 'forms/scalar-fields', 'form-controls', 'selection-controls'),
  entry('Combobox', 'Forms', 'forms/combobox', 'form-controls', 'comboboxes'),
  entry('MultiCombobox', 'Forms', 'forms/combobox', 'form-controls', 'comboboxes'),
  entry('TagPicker', 'Forms', 'forms/combobox', 'form-controls', 'comboboxes'),
  entry('DatePresetPicker', 'Forms', 'forms/date-presets', 'form-controls', 'date-time'),
  entry('DatePicker', 'Forms', 'forms/date-time', 'form-controls', 'date-time'),
  entry('DateRangePicker', 'Forms', 'forms/date-time', 'form-controls', 'date-time'),
  entry('DateTimePicker', 'Forms', 'forms/date-time', 'form-controls', 'date-time'),
  entry('TimePicker', 'Forms', 'forms/date-time', 'form-controls', 'date-time'),
  entry('FileUpload', 'Forms', 'forms/upload', 'form-controls', 'uploads'),
  entry('DropZone', 'Forms', 'forms/upload', 'form-controls', 'uploads'),
  entry('ImageDropZone', 'Forms', 'forms/upload', 'form-controls', 'uploads'),
  entry('RelationPicker', 'Forms', 'forms/relation-picker', 'form-controls', 'relation-picker'),
  entry(
    'SearchBar',
    'Data operations',
    'data-operations/list-controls',
    'data-operations',
    'collection-controls',
  ),
  entry(
    'FilterBar',
    'Data operations',
    'data-operations/list-controls',
    'data-operations',
    'collection-controls',
  ),
  entry(
    'AppliedFilters',
    'Data operations',
    'data-operations/list-controls',
    'data-operations',
    'collection-controls',
  ),
  entry(
    'SortMenu',
    'Data operations',
    'data-operations/list-controls',
    'data-operations',
    'collection-controls',
  ),
  entry('SavedViews', 'Data operations', 'data-operations/list-controls', 'data-operations', 'saved-views'),
  entry('ViewSettings', 'Data operations', 'data-operations/list-controls', 'data-operations', 'saved-views'),
  entry('ResourceList', 'Data display', 'data-display/resource-list', 'data-operations', 'resource-list'),
  entry('DataGrid', 'Data display', 'data-display/data-grid', 'data-operations', 'data-grid'),
  entry('Tree', 'Data display', 'data-display/tree', 'data-operations', 'tree'),
  entry('TreeGrid', 'Data display', 'data-display/tree', 'data-operations', 'tree'),
  entry('DataMatrix', 'Data display', 'data-display/matrix', 'data-operations', 'data-matrix'),
  entry('BarChart', 'Data display', 'data-display/bar-chart', 'data-operations', 'bar-chart'),
  entry(
    'TimeframeFilter',
    'Data operations',
    'data-operations/timeframe-filter',
    'data-operations',
    'timeframe-filter',
  ),
  entry('InlineEdit', 'Data operations', 'data-operations/inline-edit', 'data-operations', 'inline-edit'),
  entry('DescriptionList', 'Record', 'record/display', 'record-workspace', 'record-display'),
  entry('KeyValue', 'Record', 'record/display', 'record-workspace', 'record-display'),
  entry('Person', 'Record', 'record/display', 'record-workspace', 'record-display'),
  entry('AvatarGroup', 'Record', 'record/display', 'record-workspace', 'record-display'),
  entry('Status', 'Record', 'record/display', 'record-workspace', 'record-display'),
  entry('FormattedDate', 'Formatted values', 'record/formatted-values', 'record-workspace', 'record-display'),
  entry(
    'FormattedNumber',
    'Formatted values',
    'record/formatted-values',
    'record-workspace',
    'record-display',
  ),
  entry(
    'FormattedMoney',
    'Formatted values',
    'record/formatted-values',
    'record-workspace',
    'record-display',
  ),
  entry('RecordSummary', 'Record', 'record/composition', 'record-workspace', 'record-composition'),
  entry('RecordActions', 'Record', 'record/composition', 'record-workspace', 'record-composition'),
  entry('RecordRail', 'Record', 'record/composition', 'record-workspace', 'record-composition'),
  entry('ActivityTimeline', 'Activity', 'record/activity', 'record-workspace', 'activity-audit'),
  entry('AuditLog', 'Activity', 'record/activity', 'record-workspace', 'activity-audit'),
  entry('Attachments', 'Media', 'record/media', 'record-workspace', 'attachments-media'),
  entry('MediaGallery', 'Media', 'record/media', 'record-workspace', 'attachments-media'),
]
