import type { MenuDef } from '@ketvietlab/ketjs'

export const menus: Record<string, MenuDef> = {
  hospitality: { label: 'menu.app', icon: 'hotel', sequence: 10 },
  'hospitality.frontDesk': {
    parent: 'hospitality',
    label: 'menu.frontDesk',
    path: '/admin/hospitality/front-desk',
    needs: 'hospitality_core.listStays',
    for: ['hospitality_core.checkIn', 'hospitality_core.checkOut'],
    sequence: 1010,
  },
  'hospitality.tapeChart': {
    parent: 'hospitality',
    label: 'menu.tapeChart',
    path: '/admin/hospitality/tape-chart',
    needs: 'hospitality_core.getTapeChart',
    for: ['hospitality_core.createReservation', 'hospitality_core.moveRoom'],
    sequence: 1020,
  },
  'hospitality.reservations': {
    parent: 'hospitality',
    label: 'menu.reservations',
    path: '/admin/hospitality/reservations',
    needs: 'hospitality_core.listReservations',
    for: [
      'hospitality_core.createReservation',
      'hospitality_core.amendReservation',
      'hospitality_core.cancelReservation',
    ],
    sequence: 1030,
  },
  'hospitality.stays': {
    parent: 'hospitality',
    label: 'menu.stays',
    path: '/admin/hospitality/stays',
    needs: 'hospitality_core.listStays',
    for: [
      'hospitality_core.checkIn',
      'hospitality_core.addStayGuest',
      'hospitality_core.moveRoom',
      'hospitality_core.markNoShow',
    ],
    sequence: 1040,
  },
  'hospitality.folios': {
    parent: 'hospitality',
    label: 'menu.folios',
    path: '/admin/hospitality/folios',
    needs: 'hospitality_core.listFolios',
    for: [
      'hospitality_core.addCharge',
      'hospitality_core.voidCharge',
      'hospitality_billing.recordFolioPayment',
    ],
    sequence: 1050,
  },
  'hospitality.services': {
    parent: 'hospitality',
    label: 'menu.services',
    path: '/admin/hospitality/services',
    needs: 'hospitality_core.listExtraLines',
    for: ['hospitality_core.addCharge', 'hospitality_core.materializeExtraLine'],
    sequence: 1052,
  },
  'hospitality.nightAudit': {
    parent: 'hospitality',
    label: 'menu.nightAudit',
    path: '/admin/hospitality/night-audit',
    needs: 'hospitality_core.listNightAudits',
    for: ['hospitality_core.requestNightAudit', 'hospitality_core.previewNightAudit'],
    sequence: 1054,
  },
  'hospitality.inventory': {
    parent: 'hospitality',
    label: 'menu.inventory',
    path: '/admin/hospitality/inventory',
    needs: 'hospitality_core.listInventory',
    for: ['hospitality_core.setInventoryRange', 'hospitality_core.setRestrictionRange'],
    sequence: 1055,
  },
  'hospitality.properties': {
    parent: 'hospitality',
    label: 'menu.properties',
    path: '/admin/hospitality/properties',
    needs: 'hospitality_core.listProperties',
    for: ['hospitality_core.saveProperty'],
    sequence: 1060,
  },
  'hospitality.rooms': {
    parent: 'hospitality',
    label: 'menu.rooms',
    path: '/admin/hospitality/rooms',
    needs: 'hospitality_core.listRooms',
    for: ['hospitality_core.saveRoom'],
    sequence: 1070,
  },
  'hospitality.cleaningTasks': {
    parent: 'hospitality',
    label: 'menu.cleaningTasks',
    path: '/admin/hospitality/housekeeping',
    needs: 'hospitality_core.listCleaningTasks',
    for: ['hospitality_core.startCleaningTask', 'hospitality_core.completeCleaningTask'],
    sequence: 7010,
  },
  'hospitality.housekeepingRooms': {
    parent: 'hospitality',
    label: 'menu.housekeepingRooms',
    path: '/admin/hospitality/housekeeping/rooms',
    needs: 'hospitality_core.listRooms',
    for: ['hospitality_core.setRoomStatus', 'hospitality_core.createCleaningTask'],
    sequence: 7020,
  },
  'hospitality.stayNotices': {
    parent: 'hospitality',
    label: 'menu.stayNotices',
    path: '/admin/hospitality/stay-notices',
    needs: 'hospitality_core.listStayNotices',
    for: ['hospitality_core.recordStayNoticeSubmission', 'hospitality_core.confirmStayNotice'],
    sequence: 8010,
  },
  'hospitality.configuration': { parent: 'hospitality', label: 'menu.configuration', sequence: 9000 },
  'hospitality.roomTypes': {
    parent: 'hospitality.configuration',
    label: 'menu.roomTypes',
    path: '/admin/hospitality/room-types',
    needs: 'hospitality_core.listRoomTypes',
    for: ['hospitality_core.saveRoomType'],
    sequence: 10,
  },
  'hospitality.content': {
    parent: 'hospitality.configuration',
    label: 'menu.content',
    path: '/admin/hospitality/content',
    needs: 'hospitality_core.listContentImages',
    for: ['hospitality_core.setPrimaryContentImage'],
    sequence: 12,
  },
  'hospitality.ratePlans': {
    parent: 'hospitality.configuration',
    label: 'menu.ratePlans',
    path: '/admin/hospitality/rate-plans',
    needs: 'hospitality_core.listRatePlans',
    for: ['hospitality_core.saveRatePlan'],
    sequence: 15,
  },
  'hospitality.amenities': {
    parent: 'hospitality.configuration',
    label: 'menu.amenities',
    path: '/admin/hospitality/amenities',
    needs: 'hospitality_core.listAmenities',
    for: ['hospitality_core.saveAmenity'],
    sequence: 20,
  },
  'hospitality.policies': {
    parent: 'hospitality.configuration',
    label: 'menu.policies',
    path: '/admin/hospitality/policies',
    needs: 'hospitality_core.listCancellationPolicies',
    for: ['hospitality_core.saveCancellationPolicy'],
    sequence: 30,
  },
}
