import type { ModelDef } from '@ketvietlab/ketjs'

export const models: Record<string, ModelDef> = {
  Warehouse: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      code: 'text',
      receptionSteps: 'text',
      deliverySteps: 'text',
      active: 'bool',
    },
    indexes: { code_company: { fields: ['companyId', 'code'], unique: true } },
  },
  Location: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      usage: 'text',
      parentId: 'ref:stock.Location?',
      parentPath: 'text',
      warehouseId: 'ref:stock.Warehouse?',
      active: 'bool',
    },
    indexes: {
      parent: { fields: ['companyId', 'parentId'] },
      warehouse: { fields: ['companyId', 'warehouseId'] },
    },
  },
  PickingType: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      code: 'text',
      warehouseId: 'ref:stock.Warehouse?',
      defaultLocationSrcId: 'ref:stock.Location?',
      defaultLocationDestId: 'ref:stock.Location?',
      createBackorder: 'text',
      active: 'bool',
    },
  },
  Picking: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      pickingTypeId: 'ref:stock.PickingType',
      locationId: 'ref:stock.Location',
      locationDestId: 'ref:stock.Location',
      moveType: 'text',
      state: 'text',
      backorderId: 'ref:stock.Picking?',
      scheduledDate: 'datetime',
      dateDone: 'datetime?',
    },
    indexes: { state_type: { fields: ['companyId', 'state', 'pickingTypeId'] } },
  },
  Move: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      pickingId: 'ref:stock.Picking?',
      productId: 'ref:product.Product',
      productUomId: 'ref:uom.Unit',
      productUomQty: 'decimal',
      quantity: 'decimal',
      locationId: 'ref:stock.Location',
      locationDestId: 'ref:stock.Location',
      state: 'text',
      picked: 'bool',
      procureMethod: 'text',
      ruleId: 'ref:stock.Rule?',
      origin: 'text?',
    },
    indexes: {
      product_locations: { fields: ['companyId', 'productId', 'locationId', 'locationDestId', 'state'] },
    },
  },
  MoveLine: {
    scope: 'company',
    fields: {
      id: 'id',
      moveId: 'ref:stock.Move',
      pickingId: 'ref:stock.Picking?',
      productId: 'ref:product.Product',
      productUomId: 'ref:uom.Unit',
      quantity: 'decimal',
      quantityProductUom: 'decimal',
      locationId: 'ref:stock.Location',
      locationDestId: 'ref:stock.Location',
      lotId: 'ref:stock.Lot?',
      picked: 'bool',
    },
    indexes: {
      move: { fields: ['companyId', 'moveId'] },
      reservation: { fields: ['companyId', 'productId', 'locationId', 'picked'] },
    },
  },
  Quant: {
    scope: 'company',
    fields: {
      id: 'id',
      productId: 'ref:product.Product',
      locationId: 'ref:stock.Location',
      lotId: 'ref:stock.Lot?',
      lotKey: 'text',
      quantity: 'decimal',
      reservedQuantity: 'decimal',
      inDate: 'datetime',
      version: 'int',
    },
    indexes: { identity: { fields: ['companyId', 'productId', 'locationId', 'lotKey'], unique: true } },
  },
  Lot: {
    scope: 'company',
    fields: {
      id: 'id',
      productId: 'ref:product.Product',
      name: 'text',
      ref: 'text?',
      note: 'text?',
      expirationDate: 'datetime?',
      active: 'bool',
    },
    indexes: { product_name: { fields: ['companyId', 'productId', 'name'], unique: true } },
  },
  Route: {
    scope: 'company',
    fields: { id: 'id', name: 'text', sequence: 'int', active: 'bool' },
  },
  Rule: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      routeId: 'ref:stock.Route',
      action: 'text',
      sequence: 'int',
      locationSrcId: 'ref:stock.Location?',
      locationDestId: 'ref:stock.Location',
      pickingTypeId: 'ref:stock.PickingType',
      procureMethod: 'text',
      active: 'bool',
    },
    indexes: { route_destination: { fields: ['companyId', 'routeId', 'locationDestId', 'sequence'] } },
  },
  ProductRoute: {
    scope: 'company',
    fields: { id: 'id', productId: 'ref:product.Product', routeId: 'ref:stock.Route' },
    indexes: { product_route: { fields: ['companyId', 'productId', 'routeId'], unique: true } },
  },
  CategoryRoute: {
    scope: 'company',
    fields: { id: 'id', categoryId: 'ref:product.Category', routeId: 'ref:stock.Route' },
    indexes: { category_route: { fields: ['companyId', 'categoryId', 'routeId'], unique: true } },
  },
  WarehouseRoute: {
    scope: 'company',
    fields: { id: 'id', warehouseId: 'ref:stock.Warehouse', routeId: 'ref:stock.Route' },
    indexes: { warehouse_route: { fields: ['companyId', 'warehouseId', 'routeId'], unique: true } },
  },
  MoveLink: {
    scope: 'company',
    fields: { id: 'id', originMoveId: 'ref:stock.Move', destinationMoveId: 'ref:stock.Move' },
    indexes: { move_link: { fields: ['companyId', 'originMoveId', 'destinationMoveId'], unique: true } },
  },
  Orderpoint: {
    scope: 'company',
    fields: {
      id: 'id',
      productId: 'ref:product.Product',
      warehouseId: 'ref:stock.Warehouse',
      locationId: 'ref:stock.Location',
      trigger: 'text',
      minQuantity: 'decimal',
      maxQuantity: 'decimal',
      replenishmentUomId: 'ref:uom.Unit?',
      routeId: 'ref:stock.Route?',
      active: 'bool',
    },
    indexes: { product_location: { fields: ['companyId', 'productId', 'locationId'], unique: true } },
  },
}
