// Regenerates src/icons.mjs from a local lucide-static package:
//   node tools/vendor-lucide.mjs /path/to/node_modules/lucide-static
// Flow keys stay stable; only the Lucide glyph behind each key is chosen here.
import { readFile, writeFile, copyFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const glyphs = {
  user: 'user',
  tag: 'tag',
  status: 'circle-dot',
  plus: 'plus',
  search: 'search',
  grid: 'layout-grid',
  list: 'list',
  board: 'kanban',
  sun: 'sun',
  moon: 'moon',
  arrow: 'arrow-right',
  check: 'check',
  close: 'x',
  chevron: 'chevron-right',
  down: 'chevron-down',
  inbox: 'inbox',
  folder: 'folder',
  calendar: 'calendar',
  book: 'book-open',
  filter: 'list-filter',
  settings: 'settings',
  flag: 'flag',
  clock: 'clock',
  link: 'link',
  layers: 'layers',
  reset: 'rotate-ccw',
  download: 'download',
  image: 'image',
  play: 'square-play',
  file: 'file',
  more: 'ellipsis',
}

const n = (x) => Number(x ?? 0)
const fmt = (x) => String(Math.round(x * 1000) / 1000)
const NUM = /[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?/gi
// A leading relative moveto becomes absolute; its implicit follow-up pairs stay relative linetos.
const absoluteStart = (d) => {
  d = d.trim()
  if (d[0] !== 'm') return d
  const rest = d.slice(1),
    numbers = [...rest.matchAll(NUM)]
  const pairEnd = numbers[1].index + numbers[1][0].length,
    tail = rest.slice(pairEnd)
  return `M${rest.slice(0, pairEnd).trim()}${/^\s*[+\-.\d]/.test(tail) ? 'l' : ''}${tail}`
}
const toPath = ([tag, a]) => {
  switch (tag) {
    case 'path':
      return absoluteStart(a.d)
    case 'line':
      return `M${fmt(n(a.x1))} ${fmt(n(a.y1))}L${fmt(n(a.x2))} ${fmt(n(a.y2))}`
    case 'polyline':
    case 'polygon': {
      const p = a.points
          .trim()
          .split(/[\s,]+/)
          .map(Number),
        pairs = []
      for (let i = 0; i < p.length; i += 2) pairs.push(`${fmt(p[i])} ${fmt(p[i + 1])}`)
      return `M${pairs.join('L')}${tag === 'polygon' ? 'Z' : ''}`
    }
    case 'circle':
    case 'ellipse': {
      const rx = n(a.r ?? a.rx),
        ry = n(a.r ?? a.ry),
        cx = n(a.cx),
        cy = n(a.cy)
      return `M${fmt(cx - rx)} ${fmt(cy)}a${fmt(rx)} ${fmt(ry)} 0 1 0 ${fmt(2 * rx)} 0a${fmt(rx)} ${fmt(ry)} 0 1 0 ${fmt(-2 * rx)} 0`
    }
    case 'rect': {
      const x = n(a.x),
        y = n(a.y),
        w = n(a.width),
        h = n(a.height)
      const rx = Math.min(n(a.rx ?? a.ry), w / 2),
        ry = Math.min(n(a.ry ?? a.rx), h / 2)
      if (!rx || !ry) return `M${fmt(x)} ${fmt(y)}h${fmt(w)}v${fmt(h)}h${fmt(-w)}Z`
      const arc = (dx, dy) => `a${fmt(rx)} ${fmt(ry)} 0 0 1 ${fmt(dx)} ${fmt(dy)}`
      return `M${fmt(x + rx)} ${fmt(y)}h${fmt(w - 2 * rx)}${arc(rx, ry)}v${fmt(h - 2 * ry)}${arc(-rx, ry)}h${fmt(-(w - 2 * rx))}${arc(-rx, -ry)}v${fmt(-(h - 2 * ry))}${arc(rx, -ry)}Z`
    }
    default:
      throw new Error(`Unsupported Lucide element <${tag}>`)
  }
}

const source = resolve(process.argv[2] ?? 'node_modules/lucide-static')
const { version } = JSON.parse(await readFile(resolve(source, 'package.json'), 'utf8'))
const nodes = JSON.parse(await readFile(resolve(source, 'icon-nodes.json'), 'utf8'))
const lines = Object.entries(glyphs).map(([key, name]) => {
  if (!nodes[name]) throw new Error(`Lucide ${version} has no "${name}"`)
  return `  ${key}: ${JSON.stringify(nodes[name].map(toPath).join(''))}, // ${name}`
})
const out = fileURLToPath(new URL('../src/icons.mjs', import.meta.url))
await writeFile(
  out,
  `// Generated by tools/vendor-lucide.mjs from lucide-static ${version} (ISC, see LUCIDE-LICENSE). Do not edit by hand.
// Each Lucide element is folded into one stroke-only path; rendering is identical because icons use fill="none".
export const LUCIDE_VERSION = ${JSON.stringify(version)};
export const icons = {
${lines.join('\n')}
};
`,
)
await copyFile(resolve(source, 'LICENSE'), fileURLToPath(new URL('../LUCIDE-LICENSE', import.meta.url)))
console.log(`Vendored ${lines.length} Lucide ${version} glyphs into src/icons.mjs`)
