// Assembly only. Each concern lives in its own file so a reader looking for the
// models, the extension points or the server functions knows where to go without
// scrolling past the other two.

import { defineModule } from '@ketvietlab/ketjs'
import { imageModels, imageFunctions, imageJobs } from './image-assets.ts'
import { models } from './models.ts'
import { joints } from './joints.ts'
import { sections } from './sections.ts'
import { views } from './views.ts'
import { functions } from './functions.ts'
import { tokens } from './tokens.ts'
import { contentTypes, taxonomies } from './content-types.ts'
import { saveStudioStyle } from './studio-style.ts'
import { cmsFunctions } from './cms.ts'
import { publicationFunctions } from './publication.ts'
import { customerFunctions } from './customer.ts'
import { jobs } from './jobs.ts'

export default defineModule({
  name: 'website',
  version: '0.1.0',
  title: 'Website',
  summary: 'Trang, section và điều hướng — nội dung soạn bằng dữ liệu, không phải code.',
  category: 'Website',
  messages: {
    vi: {
      'app.title': 'Website',
      'app.summary': 'Trang, section và điều hướng — nội dung soạn bằng dữ liệu, không phải code.',
      'app.category': 'Website',
      'page.notFound': 'Không tìm thấy trang',
      'content.page': 'Trang',
      'content.pages': 'Các trang',
      'content.post': 'Bài viết',
      'content.posts': 'Bài viết',
      'taxonomy.category': 'Chuyên mục',
      'taxonomy.categories': 'Chuyên mục',
      'taxonomy.tag': 'Thẻ',
      'taxonomy.tags': 'Thẻ',
      'error.forbidden': 'Bạn không có quyền thao tác trên website này.',
      'error.unknownField': 'Trường không được khai báo.',
      'error.required': 'Thông tin bắt buộc.',
      'error.invalidFieldType': 'Kiểu dữ liệu không hợp lệ.',
      'error.invalidTheme': 'Theme không có trong bản triển khai.',
      'error.invalidName': 'Tên không hợp lệ hoặc quá dài.',
      'error.invalidTitle': 'Tiêu đề không hợp lệ hoặc quá dài.',
      'error.invalidLocale': 'Mã ngôn ngữ không hợp lệ.',
      'error.invalidGoogleTagManagerId': 'Mã container phải có dạng GTM-XXXXXXX.',
      'error.payloadTooLarge': 'Dữ liệu vượt quá giới hạn cho phép.',
      'error.duplicateName': 'Tên này đã được sử dụng.',
      'error.duplicateHost': 'Tên miền này đã được gán cho website khác.',
      'error.immutableHost': 'Muốn đổi tên miền thì thêm tên miền mới.',
      'error.invalidTokens': 'Token giao diện phải là một đối tượng khoá–giá trị.',
      'error.invalidLogo': 'Logo phải là ảnh tải lên hoặc một đường dẫn https://.',
      'error.invalidTokenValue':
        'Có token mang tên hoặc giá trị không hợp lệ. Giá trị chỉ được chứa chữ, số, khoảng trắng và # . , % ( ) / + * -',
      'error.primaryDomainInUse':
        'Không thể gỡ tên miền chính khi website còn tên miền khác. Hãy đặt một tên miền khác làm chính trước.',
      'error.duplicateRedirect':
        'Đường dẫn này đã có chuyển hướng. Hãy sửa chuyển hướng đang có thay vì thêm mới.',
      'error.duplicatePath': 'Đường dẫn này đã được sử dụng trên website.',
      'error.duplicateSlug': 'Slug này đã được sử dụng.',
      'error.siteNotFound': 'Không tìm thấy website.',
      'error.invalidHost': 'Tên miền không hợp lệ.',
      'error.invalidRole': 'Vai trò website không hợp lệ.',
      'error.immutableOwnership': 'Không thể chuyển dữ liệu sang website khác.',
      'error.homeCannotTrash': 'Không thể xoá trang chủ của website.',
      'error.homePathRequired': 'Trang chủ phải giữ đường dẫn /.',
      'error.editConflict': 'Nội dung đã thay đổi ở nơi khác. Hãy tải lại trước khi lưu.',
      'error.invalidContentType': 'Loại nội dung chưa được đăng ký.',
      'error.invalidPath': 'Đường dẫn nội bộ không hợp lệ.',
      'error.invalidSlug': 'Slug chỉ được chứa chữ, số và dấu gạch ngang.',
      'error.revisionNotFound': 'Không tìm thấy revision.',
      'error.previewAudience': 'Chọn người xem: nhân viên hoặc người có liên kết.',
      'error.entryUnrenderable': 'Trang này dùng section mà bản cài đặt hiện tại không còn cung cấp.',
      'error.publicationUnrenderable':
        'Bản xuất bản chứa trang dùng section mà bản cài đặt hiện tại không còn cung cấp.',
      'error.invalidDatetime': 'Ngày giờ không hợp lệ.',
      'error.invalidTaxonomy': 'Taxonomy chưa được đăng ký.',
      'error.invalidParent': 'Term cha không hợp lệ.',
      'error.taxonomyCycle': 'Cấu trúc term tạo thành vòng lặp.',
      'error.termSiteMismatch': 'Nội dung và term phải thuộc cùng website.',
      'error.invalidPostTerm': 'Chuyên mục hoặc thẻ không thuộc website này.',
      'error.termArchived': 'Chủ đề này đã được lưu trữ.',
      'error.invalidTermSeo':
        'Thông tin SEO không hợp lệ: canonical cần là đường dẫn nội bộ hoặc địa chỉ HTTPS.',
      'error.coverAltRequired': 'Ảnh bìa cần có mô tả cho người không xem được ảnh.',
      'error.termInUse': 'Không thể xóa term đang có term con hoặc đang được gán cho nội dung.',
      'error.mediaInUse': 'Không thể xóa ảnh đang được đặt trên một trang. Hãy gỡ khỏi trang trước.',
      'error.mediaUsageUnknown':
        'Website quá lớn để rà hết trong một lần, nên không thể khẳng định ảnh này không còn được dùng. Hãy gỡ ảnh khỏi các trang rồi thử lại.',
      'error.invalidDimensions': 'Kích thước media không hợp lệ.',
      'error.invalidRedirect': 'Hai đường dẫn redirect phải khác nhau và là đường dẫn nội bộ.',
      'error.redirectCycle': 'Redirect tạo thành vòng lặp.',
      'error.lastAdministrator': 'Website phải luôn còn ít nhất một quản trị viên.',
      'error.publicationEmpty': 'Cần chọn ít nhất một nội dung để xuất bản.',
      'error.publicationTooLarge': 'Một lần xuất bản vượt quá số nội dung cho phép.',
      'error.publicationDuplicate': 'Một nội dung xuất hiện hai lần trong lần xuất bản này.',
      'error.publicationEntryOutsideSite': 'Nội dung không thuộc website này.',
      'error.publicationEntryTrashed': 'Nội dung đã bị xóa nên không thể xuất bản.',
      'error.publicationConflict': 'Mã xuất bản này đã dùng cho một tập nội dung khác.',
      'error.publicationNotFound': 'Không tìm thấy lần xuất bản.',
      'error.publicationSuperseded': 'Lần xuất bản này đã bị thay thế.',
      'error.publicationStaleBase': 'Nội dung công khai vừa thay đổi. Hãy xem lại rồi xuất bản.',
      'error.publicationNoBase': 'Chưa có lần xuất bản trước để quay lại.',
      'customer.error.realmUnavailable': 'Website chưa sẵn sàng cho tài khoản khách hàng.',
      'customer.error.invalidName': 'Tên khách hàng không hợp lệ hoặc quá dài.',
      'customer.error.invalidEmail': 'Địa chỉ email không hợp lệ.',
      'customer.error.invalidPassword': 'Mật khẩu phải có từ 6 đến 128 ký tự.',
      'customer.error.rateLimit': 'Bạn thao tác quá nhanh. Vui lòng thử lại sau.',
      'customer.error.emailInUse': 'Địa chỉ email này đã được sử dụng.',
      'customer.error.phoneInUse': 'Số điện thoại này đã gắn với một khách hàng khác.',
      'customer.error.invalidPhone': 'Số điện thoại không hợp lệ.',
      'customer.error.loginRequired': 'Cần số điện thoại hoặc email để khách đăng nhập.',
      'customer.error.signupClosed':
        'Trang này không cho tự đăng ký. Vui lòng liên hệ bộ phận chăm sóc khách hàng.',
      'customer.error.partnerUnavailable': 'Không tìm thấy khách hàng.',
      'customer.error.partnerInOtherRealm': 'Khách hàng này đã có tài khoản ở một trang khác.',
      'customer.error.accountUnavailable': 'Khách hàng này chưa có tài khoản.',
      'customer.error.invalidCredentials': 'Email hoặc mật khẩu không đúng.',
      'customer.error.sessionExpired': 'Phiên đăng nhập đã hết hạn.',
      'customer.error.csrf': 'Yêu cầu bảo mật không hợp lệ. Vui lòng tải lại trang.',
      'customer.error.originMismatch': 'Nguồn gửi yêu cầu không được phép.',
      'customer.error.invalidRequest': 'Yêu cầu không hợp lệ.',
      'customer.error.resetExpired': 'Liên kết đặt lại mật khẩu đã hết hạn hoặc đã được dùng.',
    },
    en: {
      'app.title': 'Website',
      'app.summary': 'Pages, sections and navigation — composed as data, not code.',
      'app.category': 'Website',
      'page.notFound': 'Page not found',
      'content.page': 'Page',
      'content.pages': 'Pages',
      'content.post': 'Post',
      'content.posts': 'Posts',
      'taxonomy.category': 'Category',
      'taxonomy.categories': 'Categories',
      'taxonomy.tag': 'Tag',
      'taxonomy.tags': 'Tags',
      'error.forbidden': 'You do not have access to this site.',
      'error.unknownField': 'This field is not declared.',
      'error.required': 'This field is required.',
      'error.invalidFieldType': 'The field has an invalid data type.',
      'error.invalidTheme': 'The theme is not shipped with this deployment.',
      'error.invalidName': 'The name is invalid or too long.',
      'error.invalidTitle': 'The title is invalid or too long.',
      'error.invalidLocale': 'The locale code is invalid.',
      'error.invalidGoogleTagManagerId': 'The container ID must match GTM-XXXXXXX.',
      'error.payloadTooLarge': 'The payload exceeds the allowed size.',
      'error.duplicateName': 'This name is already in use.',
      'error.duplicateHost': 'This domain is already assigned to another site.',
      'error.immutableHost': 'To use another name, add it as a new domain.',
      'error.invalidTokens': 'Theme tokens have to be an object of names and values.',
      'error.invalidLogo': 'The logo has to be an uploaded image or an https:// address.',
      'error.invalidTokenValue':
        'A token name or value is not allowed. A value may hold letters, digits, spaces and # . , % ( ) / + * -',
      'error.primaryDomainInUse':
        'The primary domain cannot be removed while the site has others. Make one of them primary first.',
      'error.duplicateRedirect':
        'That path already redirects somewhere. Edit the redirect it has rather than adding another.',
      'error.duplicatePath': 'This path is already in use on the site.',
      'error.duplicateSlug': 'This slug is already in use.',
      'error.siteNotFound': 'The site was not found.',
      'error.invalidHost': 'The domain name is invalid.',
      'error.invalidRole': 'The site role is invalid.',
      'error.immutableOwnership': 'This record cannot be moved to another site.',
      'error.homeCannotTrash': 'The website home page cannot be deleted.',
      'error.homePathRequired': 'The home page must keep the / path.',
      'error.editConflict': 'The content changed elsewhere. Reload it before saving.',
      'error.invalidContentType': 'The content type is not registered.',
      'error.invalidPath': 'The local path is invalid.',
      'error.invalidSlug': 'The slug may only contain letters, numbers and hyphens.',
      'error.revisionNotFound': 'The revision was not found.',
      'error.previewAudience': 'Choose who can open it: staff or anyone with the link.',
      'error.entryUnrenderable': 'This page places a section this deployment no longer provides.',
      'error.publicationUnrenderable':
        'The publication holds a page placing a section this deployment no longer provides.',
      'error.invalidDatetime': 'The date and time are invalid.',
      'error.invalidTaxonomy': 'The taxonomy is not registered.',
      'error.invalidParent': 'The parent term is invalid.',
      'error.taxonomyCycle': 'The term hierarchy contains a cycle.',
      'error.termSiteMismatch': 'The content and term must belong to the same site.',
      'error.invalidPostTerm': 'The category or tag does not belong to this site.',
      'error.termArchived': 'This term has been archived.',
      'error.invalidTermSeo':
        'The SEO settings are invalid: the canonical must be a local path or an HTTPS address.',
      'error.coverAltRequired': 'The cover image needs a description for people who cannot see it.',
      'error.termInUse': 'A term with children or content assignments cannot be deleted.',
      'error.mediaInUse': 'This image is placed on a page. Take it off the page first.',
      'error.mediaUsageUnknown':
        'The site is larger than one scan, so nothing can say this image is unused. Take it off the pages that draw it and try again.',
      'error.invalidDimensions': 'The media dimensions are invalid.',
      'error.invalidRedirect': 'Redirect paths must be distinct local paths.',
      'error.redirectCycle': 'The redirect creates a cycle.',
      'error.lastAdministrator': 'A site must always retain at least one administrator.',
      'error.publicationEmpty': 'Select at least one piece of content to publish.',
      'error.publicationTooLarge': 'One publication exceeds the allowed number of entries.',
      'error.publicationDuplicate': 'An entry appears twice in this publication.',
      'error.publicationEntryOutsideSite': 'That entry does not belong to this site.',
      'error.publicationEntryTrashed': 'That entry is in the trash and cannot be published.',
      'error.publicationConflict': 'This publication id was already used for a different set.',
      'error.publicationNotFound': 'Publication not found.',
      'error.publicationSuperseded': 'This publication has already been replaced.',
      'error.publicationStaleBase': 'What is public changed while you were working. Review, then publish.',
      'error.publicationNoBase': 'There is no earlier publication to roll back to.',
      'customer.error.realmUnavailable': 'Customer accounts are not ready for this site.',
      'customer.error.invalidName': 'The customer name is invalid or too long.',
      'customer.error.invalidEmail': 'The email address is invalid.',
      'customer.error.invalidPassword': 'The password must contain 6 to 128 characters.',
      'customer.error.rateLimit': 'Too many attempts. Please try again later.',
      'customer.error.emailInUse': 'This email address is already in use.',
      'customer.error.phoneInUse': 'This phone number already belongs to another customer.',
      'customer.error.invalidPhone': 'This phone number is not valid.',
      'customer.error.loginRequired': 'A phone number or an email is needed to sign in.',
      'customer.error.signupClosed': 'This site does not take sign-ups. Please contact customer care.',
      'customer.error.partnerUnavailable': 'Customer not found.',
      'customer.error.partnerInOtherRealm': 'This customer already has an account on another site.',
      'customer.error.accountUnavailable': 'This customer has no account yet.',
      'customer.error.invalidCredentials': 'The email or password is incorrect.',
      'customer.error.sessionExpired': 'The customer session has expired.',
      'customer.error.csrf': 'The security token is invalid. Reload the page and try again.',
      'customer.error.originMismatch': 'The request origin is not allowed.',
      'customer.error.invalidRequest': 'The request is invalid.',
      'customer.error.resetExpired': 'This password reset link has expired or was already used.',
    },
  },
  requires: ['layout', 'website.page'],
  depends: ['partner'],
  models: { ...models, ...imageModels },
  contentTypes,
  taxonomies,
  joints,
  sections,
  views,
  functions: {
    ...functions,
    ...cmsFunctions,
    saveStudioStyle,
    ...publicationFunctions,
    ...customerFunctions,
    ...imageFunctions,
  },
  jobs: { ...jobs, ...imageJobs },
  tokens,
})

export type { SectionPlacement } from './types.ts'
