import type { SearchFilterConfig } from './index.tsx'

// Shared by the live catalogue and KetAtlas. The default layout separates search,
// section triggers and applied chips; mobile opens the same sections in a sheet.
// Without a manager, selections remain local to the specimen.
export const searchFilterDemoConfig: SearchFilterConfig = {
  name: 'orders',
  facets: [
    { id: 'open', type: 'filter', label: 'Open' },
    { id: 'customer', type: 'groupBy', label: 'Customer' },
    { id: 'fav-open-orders', type: 'favorite', label: 'My open orders' },
  ],
  filters: [
    { id: 'open', label: 'Open', active: true, group: 'status' },
    { id: 'closed', label: 'Closed', active: false, group: 'status' },
    { id: 'archived', label: 'Archived', active: false, group: 'status' },
    {
      id: 'created',
      label: 'Created on',
      active: false,
      group: 'date',
      options: [
        { id: 'created-today', label: 'Today', active: false },
        { id: 'created-week', label: 'This week', active: false },
        { id: 'created-month', label: 'This month', active: false },
      ],
    },
  ],
  groupBy: [
    { id: 'customer', label: 'Customer', active: true },
    { id: 'status', label: 'Status', active: false },
    { id: 'createdMonth', label: 'Order date', active: false },
  ],
  favorites: [
    { id: 'fav-open-orders', label: 'My open orders', isDefault: true, active: true },
    { id: 'fav-overdue', label: 'Overdue', isDefault: false, active: false },
  ],
  customFilterFields: [
    { value: 'reference', label: 'Reference', type: 'text' },
    { value: 'total', label: 'Total', type: 'number' },
    { value: 'confirmed', label: 'Confirmed', type: 'boolean' },
    { value: 'createdAt', label: 'Created on', type: 'date' },
  ],
  labels: {
    searchLabel: 'Search orders',
    searchPlaceholder: 'Search orders…',
    toggleLabel: 'Toggle search panel',
    searchGenericLabel: 'Search for',
    searchFieldPrefix: 'Search',
    searchFieldPreposition: 'for',
    filters: 'Filters',
    groupBy: 'Group by',
    groupByApplied: 'Currently grouped by',
    groupByAdd: 'Add grouping field',
    groupByClear: 'Clear all',
    groupByMoveEarlier: 'Move earlier',
    groupByMoveLater: 'Move later',
    favorites: 'Favorites',
    customFilterField: 'Field',
    customFilterOperator: 'Condition',
    customFilterValue: 'Value',
    customFilterAdd: 'Add custom filter',
    customGroupByPlaceholder: 'Add custom group',
    saveSearch: 'Save current search',
    favoriteName: 'Name',
    favoriteDefault: 'Default',
    favoriteSaveAction: 'Save',
    favoriteRemove: 'Remove favorite',
    favoriteSetDefault: 'Set as default',
    noFavorites: 'No saved searches yet',
    clear: 'Remove',
    applyError: 'Could not apply the search',
    retry: 'Retry',
  },
}
