import { defineModule } from '@ketvietlab/ketjs'
import { channelRoutes } from './channel-routes.ts'
import { contentTypes } from './content-types.ts'
import { functions } from './functions.ts'
import { models } from './models.ts'
import { online } from './online.ts'
import { sections } from './sections.ts'

export default defineModule({
  name: 'website_retail',
  version: '0.1.0',
  depends: ['website', 'product', 'product_media', 'channel_api', 'sale', 'stock', 'pricing', 'uom'],
  compatible: { channel_api: '^1' },
  title: 'Website Retail',
  summary: 'Catalog, giỏ hàng và checkout lead cho website bán lẻ.',
  category: 'Website',
  messages: {
    vi: {
      'app.title': 'Website Retail',
      'app.summary': 'Catalog, giỏ hàng và checkout lead cho website bán lẻ.',
      'app.category': 'Website',
      'content.product': 'Sản phẩm website',
      'content.products': 'Sản phẩm website',
      'section.products': 'Lưới sản phẩm',
      'section.cart': 'Giỏ hàng',
      'error.invalidSite': 'Website không thuộc ngành retail hoặc đang tạm dừng.',
      'error.productUnavailable': 'Sản phẩm không khả dụng trên website này.',
      'error.duplicateProduct': 'Sản phẩm đã có trong catalog của website.',
      'error.invalidCurrency': 'Mã tiền tệ phải gồm ba chữ cái.',
      'error.cartUnavailable': 'Giỏ hàng không còn khả dụng.',
      'error.invalidQuantity': 'Số lượng phải lớn hơn 0 và không vượt quá 10.000.',
      'error.cartConflict': 'Giỏ hàng vừa thay đổi. Vui lòng thử lại.',
      'error.emptyCart': 'Giỏ hàng đang trống.',
      'error.invalidName': 'Tên khách hàng không hợp lệ hoặc quá dài.',
      'error.invalidEmail': 'Địa chỉ email không hợp lệ.',
      'error.invalidPhone': 'Số điện thoại không hợp lệ.',
      'error.noteTooLong': 'Ghi chú vượt quá giới hạn cho phép.',
      'error.cartFull': 'Giỏ hàng đã đạt số dòng tối đa.',
      'error.cartTokenRequired': 'Yêu cầu cần mã giỏ hàng trong header X-Cart-Token.',
      'error.orderingUnavailable': 'Website chưa được cấu hình để nhận đơn hàng.',
      'error.orderRejected': 'Không thể tạo đơn bán từ giỏ hàng này.',
      'error.orderNotFound': 'Không tìm thấy đơn hàng.',
      'error.invalidOrderPolicy': 'Chính sách đơn hàng phải là quotation hoặc confirm.',
      'error.warehouseUnavailable': 'Kho hàng không tồn tại.',
      'error.uomUnavailable': 'Đơn vị tính mặc định không tồn tại.',
      'error.pricelistUnavailable': 'Bảng giá không tồn tại.',
    },
    en: {
      'app.title': 'Retail website',
      'app.summary': 'Catalogue, cart and checkout leads for retail sites.',
      'app.category': 'Website',
      'content.product': 'Website product',
      'content.products': 'Website products',
      'section.products': 'Product grid',
      'section.cart': 'Cart',
      'error.invalidSite': 'The site is not an active retail site.',
      'error.productUnavailable': 'The product is not available on this site.',
      'error.duplicateProduct': 'The product is already in this site catalog.',
      'error.invalidCurrency': 'The currency code must contain three letters.',
      'error.cartUnavailable': 'The cart is no longer available.',
      'error.invalidQuantity': 'Quantity must be positive and no greater than 10,000.',
      'error.cartConflict': 'The cart changed concurrently. Please retry.',
      'error.emptyCart': 'The cart is empty.',
      'error.invalidName': 'The customer name is invalid or too long.',
      'error.invalidEmail': 'The email address is invalid.',
      'error.invalidPhone': 'The phone number is invalid.',
      'error.noteTooLong': 'The note exceeds the allowed length.',
      'error.cartFull': 'The cart already holds the maximum number of lines.',
      'error.cartTokenRequired': 'This request needs a cart token in the X-Cart-Token header.',
      'error.orderingUnavailable': 'This site is not configured to take orders yet.',
      'error.orderRejected': 'The cart could not be turned into a sales order.',
      'error.orderNotFound': 'The order was not found.',
      'error.invalidOrderPolicy': 'The order policy must be quotation or confirm.',
      'error.warehouseUnavailable': 'The warehouse does not exist.',
      'error.uomUnavailable': 'The default unit of measure does not exist.',
      'error.pricelistUnavailable': 'The pricelist does not exist.',
    },
  },
  models,
  functions: { ...functions, ...online },
  routes: channelRoutes,
  contentTypes,
  sections,
})
