// Rebuilds emitted package artifacts while the framework is consumed through a
// local checkout. Production and published packages still use `npm run build`.

import { spawn, type ChildProcess } from 'node:child_process'
import {
  closeSync,
  existsSync,
  openSync,
  readSync,
  realpathSync,
  watch,
  writeFileSync,
  type FSWatcher,
} from 'node:fs'
import { dirname, extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const READY_FILE = '.ket-build-watch-ready'
const BUILD_ROOTS = ['packages', 'apps', 'examples', 'test', 'tools', 'bench'] as const
const ROOT_INPUTS = new Set([
  'ket.workspace.ts',
  'package.json',
  'package-lock.json',
  'tsconfig.base.json',
  'tsconfig.build.json',
  'tsconfig.types.json',
])
const BUILD_EXTENSIONS = new Set(['.ts', '.tsx', '.mts', '.cts', '.mjs', '.json', '.css', '.ktl', '.tmpl'])
const portable = (path: string) => path.replaceAll('\\', '/')

export function isGeneratedBuildOutput(header: string): boolean {
  return /^\/\/ @ts-nocheck Generated by tools\/[\w./-]+/m.test(header)
}

export function isFrameworkBuildInput(path: string, header = ''): boolean {
  const input = portable(path)
  if (ROOT_INPUTS.has(input)) return true
  if (input.includes('/dist/') || input.includes('/node_modules/')) return false
  return (
    BUILD_ROOTS.some((root) => input.startsWith(`${root}/`)) &&
    BUILD_EXTENSIONS.has(extname(input)) &&
    !isGeneratedBuildOutput(header)
  )
}

const readHeader = (path: string) => {
  let file: number | undefined
  try {
    file = openSync(path, 'r')
    const buffer = Buffer.alloc(512)
    return buffer.subarray(0, readSync(file, buffer, 0, buffer.length, 0)).toString('utf8')
  } catch {
    // A rename event can arrive between the old file disappearing and its
    // replacement landing. Treating that one event as authored can cause one
    // extra build, but cannot create a loop once the generated banner exists.
    return ''
  } finally {
    if (file !== undefined) closeSync(file)
  }
}

export type SerializedRunner = {
  trigger: () => void
  idle: () => Promise<void>
  close: () => Promise<void>
}

/** Debounces bursts and permits at most one queued rerun while a build is active. */
export function createSerializedRunner(
  run: () => Promise<void>,
  options: { debounceMs?: number; onError?: (error: unknown) => void } = {},
): SerializedRunner {
  const debounceMs = options.debounceMs ?? 120
  let timer: ReturnType<typeof setTimeout> | undefined
  let running = false
  let dirty = false
  let closed = false
  let active: Promise<void> | undefined
  const idleWaiters = new Set<() => void>()

  const settleIdle = () => {
    if (timer || running || dirty) return
    for (const resolveIdle of idleWaiters) resolveIdle()
    idleWaiters.clear()
  }

  const drain = () => {
    if (running || closed || !dirty) return
    running = true
    active = (async () => {
      while (dirty && !closed) {
        dirty = false
        try {
          await run()
        } catch (error) {
          options.onError?.(error)
        }
      }
    })().finally(() => {
      running = false
      active = undefined
      settleIdle()
    })
  }

  return {
    trigger() {
      if (closed) return
      dirty = true
      if (timer) clearTimeout(timer)
      timer = setTimeout(() => {
        timer = undefined
        drain()
      }, debounceMs)
    },
    idle() {
      if (!timer && !running && !dirty) return Promise.resolve()
      return new Promise((resolveIdle) => idleWaiters.add(resolveIdle))
    },
    async close() {
      closed = true
      dirty = false
      if (timer) clearTimeout(timer)
      timer = undefined
      if (active) await active
      settleIdle()
    },
  }
}

export const runFrameworkWatch = async (
  options: { root?: string; serveArgs?: string[]; serverEntry?: string; noInitial?: boolean } = {},
) => {
  const root = options.root ?? ROOT
  const noInitial = options.noInitial === true && !options.serveArgs
  const watchers: FSWatcher[] = []
  let build: ChildProcess | undefined
  let server: ChildProcess | undefined
  let stopping = false

  const stopServer = async () => {
    const child = server
    server = undefined
    if (!child || child.exitCode !== null || child.signalCode !== null) return
    await new Promise<void>((resolveExit) => {
      const timeout = setTimeout(() => child.kill('SIGKILL'), 5_000)
      child.once('exit', () => {
        clearTimeout(timeout)
        resolveExit()
      })
      child.kill('SIGTERM')
    })
  }

  const restartServer = async () => {
    if (!options.serveArgs || stopping) return
    await stopServer()
    if (stopping) return
    console.log('ketsuite: build succeeded; starting server')
    const child = spawn(
      process.execPath,
      [options.serverEntry ?? join(root, 'packages/ketsuite/dist/cli.js'), ...options.serveArgs],
      {
        cwd: process.env.KET_WATCH_SERVE_CWD ?? root,
        stdio: 'inherit',
        env: { ...process.env, KET_DEV: '1' },
      },
    )
    server = child
    child.once('error', (error) => {
      if (server === child) server = undefined
      console.error(error.message)
    })
    child.once('exit', (code) => {
      if (server !== child) return
      server = undefined
      if (!stopping) console.error(`ketsuite: server exited (${code}); waiting for source changes`)
    })
  }

  const buildOnce = () =>
    new Promise<void>((resolveBuild, rejectBuild) => {
      build = spawn(process.execPath, [join(root, 'tools/build.mjs')], {
        cwd: root,
        stdio: 'inherit',
      })
      build.once('error', rejectBuild)
      build.once('exit', (code, signal) => {
        build = undefined
        if (code === 0) {
          writeFileSync(join(root, READY_FILE), `${Date.now()}\n`)
          resolveBuild()
        } else {
          rejectBuild(new Error(`KetJS build exited with ${signal ?? code ?? 'an unknown status'}`))
        }
      })
    })

  const runner = createSerializedRunner(
    async () => {
      await buildOnce()
      await restartServer()
    },
    {
      onError: (error) => console.error(error instanceof Error ? error.message : error),
    },
  )
  const changed = (path: string) => {
    if (!isFrameworkBuildInput(path, readHeader(join(root, path)))) return
    console.log(`ketjs: ${portable(path)} changed`)
    runner.trigger()
  }

  for (const inputRoot of BUILD_ROOTS) {
    const directory = join(root, inputRoot)
    if (!existsSync(directory)) continue
    watchers.push(
      watch(directory, { recursive: true }, (_event, filename) => {
        if (filename) changed(join(inputRoot, filename.toString()))
      }),
    )
  }
  watchers.push(
    watch(root, (_event, filename) => {
      if (filename && ROOT_INPUTS.has(filename.toString())) changed(filename.toString())
    }),
  )

  if (!noInitial) runner.trigger()
  console.log('ketjs: watching framework build inputs')

  const stop = async (signal: NodeJS.Signals) => {
    if (stopping) return
    stopping = true
    for (const watcher of watchers) watcher.close()
    build?.kill(signal)
    await runner.close()
    await stopServer()
    process.exit(0)
  }
  process.once('SIGINT', () => void stop('SIGINT'))
  process.once('SIGTERM', () => void stop('SIGTERM'))
  await new Promise<void>(() => {})
}

// Compare real paths: deployments run this file through their .ketjs symlink farm.
if (process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  const args = process.argv.slice(2)
  const serveIndex = args.indexOf('--serve-ketsuite')
  await runFrameworkWatch({
    noInitial: args.includes('--no-initial'),
    serveArgs: serveIndex < 0 ? undefined : args.slice(serveIndex + 1),
  })
}
