import type { ModelDef } from '@ketvietlab/ketjs'

/** Website merchandising never owns a second product identity. */
export const models: Record<string, ModelDef> = {
  Template: {
    scope: 'company',
    timestamps: true,
    fields: {
      id: 'id',
      siteId: 'ref:website.Site',
      title: 'text',
      productType: 'text',
      layout: 'json',
      bindings: 'json',
      revisionId: 'text',
    },
    indexes: { site_type: { fields: ['companyId', 'siteId', 'productType'], unique: true } },
  },
  Binding: {
    scope: 'company',
    timestamps: true,
    fields: {
      id: 'id',
      siteId: 'ref:website.Site',
      productId: 'ref:product.Template',
      variantId: 'ref:product.Product?',
      templateId: 'ref:website_catalog.Template',
      path: 'text',
      visible: 'bool',
      position: 'int',
      action: 'text',
      contentLayout: 'json?',
      searchText: 'text?',
      overrides: 'json?',
      seoTitle: 'text?',
      seoDescription: 'text?',
      primaryCategoryId: 'ref:website_catalog.Category?',
      revisionId: 'text',
    },
    indexes: {
      site_product: { fields: ['companyId', 'siteId', 'productId'], unique: true },
      site_path: { fields: ['companyId', 'siteId', 'path'], unique: true },
      site_visibility: { fields: ['companyId', 'siteId', 'visible', 'position'] },
    },
  },
  Category: {
    scope: 'company',
    timestamps: true,
    fields: {
      id: 'id',
      siteId: 'ref:website.Site',
      kind: 'text',
      title: 'text',
      slug: 'text',
      path: 'text',
      parentId: 'ref:website_catalog.Category?',
      position: 'int',
      visible: 'bool',
      archived: 'bool',
      includeChildren: 'bool',
      mode: 'text',
      ruleGroup: 'text?',
      ruleType: 'text?',
      primarySort: 'text',
      layout: 'json?',
      description: 'text?',
      descriptionDoc: 'text?',
      thumbnail: 'text?',
      thumbnailAlt: 'text?',
      cover: 'text?',
      coverAlt: 'text?',
      seoTitle: 'text?',
      seoDescription: 'text?',
      canonical: 'text?',
      indexing: 'text',
      revisionId: 'text',
    },
    indexes: {
      site_path: { fields: ['companyId', 'siteId', 'path'], unique: true },
      site_parent: { fields: ['companyId', 'siteId', 'kind', 'parentId', 'position'] },
    },
  },
  Membership: {
    scope: 'company',
    fields: {
      id: 'id',
      siteId: 'ref:website.Site',
      categoryId: 'ref:website_catalog.Category',
      productId: 'ref:product.Template',
      excluded: 'bool',
      position: 'int',
    },
    indexes: {
      category_product: { fields: ['companyId', 'siteId', 'categoryId', 'productId'], unique: true },
      category_order: { fields: ['companyId', 'siteId', 'categoryId', 'excluded', 'position'] },
      product_categories: { fields: ['companyId', 'siteId', 'productId'] },
    },
  },
  Upload: {
    scope: 'company',
    fields: {
      id: 'id',
      siteId: 'ref:website.Site',
      resModel: 'text',
      ownerId: 'text',
      actorId: 'text',
      ready: 'bool',
      claimed: 'bool',
      deleting: 'bool?',
      expiresAt: 'datetime',
      storeKey: 'text',
    },
    indexes: { expiry: { fields: ['companyId', 'claimed', 'expiresAt'] } },
  },
  Redirect: {
    scope: 'company',
    fields: {
      id: 'id',
      siteId: 'ref:website.Site',
      path: 'text',
      targetPath: 'text',
      bindingId: 'ref:website_catalog.Binding?',
      categoryId: 'ref:website_catalog.Category?',
    },
    indexes: { site_path: { fields: ['companyId', 'siteId', 'path'], unique: true } },
  },
}
