import type { ModelDef } from '@ketvietlab/ketjs'

export const models: Record<string, ModelDef> = {
  Sequence: { scope: 'company', fields: { id: 'id', nextNumber: 'int' } },
  SessionLock: { scope: 'company', fields: { id: 'id', sessionId: 'text' } },
  Config: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      warehouseId: 'ref:stock.Warehouse',
      pricelistId: 'ref:pricing.Pricelist?',
      salesJournalId: 'ref:account.Journal',
      revenueAccountId: 'ref:account.Account',
      receivableAccountId: 'ref:account.Account',
      taxAccountId: 'ref:account.Account?',
      cashOverShortAccountId: 'ref:account.Account?',
      cashRoundingIncrement: 'decimal',
      maximumDifference: 'decimal',
      active: 'bool',
    },
  },
  PaymentMethod: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      journalId: 'ref:account.Journal',
      settlementKind: 'text?',
      isCash: 'bool',
      active: 'bool',
    },
  },
  ConfigPaymentMethod: {
    scope: 'company',
    fields: { id: 'id', configId: 'ref:pos.Config', paymentMethodId: 'ref:pos.PaymentMethod' },
    indexes: { config_method: { fields: ['companyId', 'configId', 'paymentMethodId'], unique: true } },
  },
  ProviderPaymentLock: {
    scope: 'company',
    fields: {
      id: 'id',
      orderId: 'ref:pos.Order',
      paymentMethodId: 'ref:pos.PaymentMethod',
      amount: 'decimal',
      currency: 'text',
      state: 'text',
      settledPaymentId: 'ref:pos.Payment?',
      reversalPaymentId: 'ref:pos.Payment?',
      createdAt: 'datetime',
      updatedAt: 'datetime',
    },
    indexes: { order_state: { fields: ['companyId', 'orderId', 'state'] } },
  },
  ReceiptDocument: {
    scope: 'company',
    fields: {
      id: 'id',
      orderId: 'ref:pos.Order',
      version: 'int',
      templateVersion: 'text',
      contentHash: 'text',
      document: 'json',
      issuedAt: 'datetime',
    },
    indexes: { order: { fields: ['companyId', 'orderId'], unique: true } },
  },
  Session: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      configId: 'ref:pos.Config',
      userId: 'ref:user.User',
      deviceId: 'text?',
      state: 'text',
      startAt: 'datetime?',
      stopAt: 'datetime?',
      openingNotes: 'text?',
      closingNotes: 'text?',
      cashRegisterBalanceStart: 'decimal',
      cashRegisterBalanceEnd: 'decimal',
      cashRegisterBalanceEndReal: 'decimal',
      cashRegisterDifference: 'decimal',
      varianceStatus: 'text',
      varianceReason: 'text?',
      varianceNote: 'text?',
      varianceApprovedBy: 'text?',
      varianceApprovedAt: 'datetime?',
      cashAdjustmentId: 'ref:pos.CashAdjustment?',
      revision: 'int?',
    },
    indexes: { config_state: { fields: ['companyId', 'configId', 'state'] } },
  },
  Exchange: {
    scope: 'company',
    fields: {
      id: 'id',
      uuid: 'text',
      originalOrderId: 'ref:pos.Order',
      returnOrderId: 'ref:pos.Order',
      replacementOrderId: 'ref:pos.Order',
      originalRevision: 'int',
      reason: 'text?',
      createdAt: 'datetime',
    },
    indexes: {
      company_uuid: { fields: ['companyId', 'uuid'], unique: true },
      return_order: { fields: ['companyId', 'returnOrderId'], unique: true },
      replacement_order: { fields: ['companyId', 'replacementOrderId'], unique: true },
    },
  },
  Order: {
    scope: 'company',
    fields: {
      id: 'id',
      uuid: 'text',
      name: 'text',
      posReference: 'text',
      sequenceNumber: 'int',
      sessionId: 'ref:pos.Session',
      configId: 'ref:pos.Config',
      partnerId: 'ref:partner.Partner?',
      state: 'text',
      invoiceStatus: 'text',
      isRefund: 'bool',
      refundedOrderId: 'ref:pos.Order?',
      returnPortion: 'decimal?',
      returnComplete: 'bool?',
      exchangeId: 'ref:pos.Exchange?',
      exchangeRole: 'text?',
      paymentLockId: 'text?',
      paymentLockMethodId: 'ref:pos.PaymentMethod?',
      paymentLockAmount: 'decimal?',
      dateOrder: 'datetime',
      finalizedAt: 'datetime?',
      currency: 'text',
      amountUntaxed: 'decimal',
      amountTax: 'decimal',
      amountExact: 'decimal',
      amountRounding: 'decimal',
      amountTotal: 'decimal',
      amountPaid: 'decimal',
      amountReturn: 'decimal',
      toInvoice: 'bool',
      accountMoveId: 'ref:account.Move?',
      pickingId: 'ref:stock.Picking?',
      receiptId: 'ref:pos.ReceiptDocument?',
      note: 'text?',
      revision: 'int?',
      operatorId: 'text?',
      deviceId: 'text?',
      priceBookRevision: 'text?',
      /** Optional integration state owned by the composed Loyalty authority. */
      loyaltyState: 'text?',
      loyaltyPointsEarned: 'decimal?',
      loyaltyPointsSpent: 'decimal?',
    },
    indexes: {
      company_uuid: { fields: ['companyId', 'uuid'], unique: true },
      company_order_date: { fields: ['companyId', 'dateOrder'] },
      config_order_date: { fields: ['companyId', 'configId', 'dateOrder'] },
      company_finalized: { fields: ['companyId', 'finalizedAt'] },
      config_finalized: { fields: ['companyId', 'configId', 'finalizedAt'] },
      session_sequence: { fields: ['companyId', 'sessionId', 'sequenceNumber'], unique: true },
      exchange_role: { fields: ['companyId', 'exchangeId', 'exchangeRole'], unique: true },
      payment_lock: { fields: ['companyId', 'paymentLockId'], unique: true },
    },
  },
  OrderLine: {
    scope: 'company',
    fields: {
      id: 'id',
      orderId: 'ref:pos.Order',
      productId: 'ref:product.Product',
      productUomId: 'ref:uom.Unit',
      name: 'text',
      qty: 'decimal',
      priceUnit: 'decimal',
      discount: 'decimal',
      taxId: 'ref:account.Tax?',
      taxIds: 'json?',
      taxEvidence: 'json?',
      quoteRevision: 'text?',
      tracking: 'text?',
      lotSelections: 'json?',
      affectsStock: 'bool?',
      overrideReason: 'text?',
      overrideBy: 'text?',
      priceSubtotal: 'decimal',
      priceSubtotalIncl: 'decimal',
      refundedOrderlineId: 'ref:pos.OrderLine?',
      sequence: 'int',
      /** Core POS can carry reward lines without requiring a particular channel adapter. */
      lineKind: 'text?',
      loyaltyApplicationId: 'text?',
      loyaltyRewardId: 'text?',
      loyaltyPointsCost: 'decimal?',
    },
  },
  Payment: {
    scope: 'company',
    fields: {
      id: 'id',
      orderId: 'ref:pos.Order',
      configId: 'ref:pos.Config?',
      sessionId: 'ref:pos.Session?',
      paymentMethodId: 'ref:pos.PaymentMethod',
      currency: 'text?',
      amount: 'decimal',
      tenderedAmount: 'decimal',
      appliedAmount: 'decimal',
      state: 'text',
      kind: 'text',
      reference: 'text?',
      providerAttemptId: 'text?',
      reversalOfId: 'ref:pos.Payment?',
      operatorId: 'text?',
      deviceId: 'text?',
      paymentDate: 'datetime',
    },
    indexes: {
      company_time: { fields: ['companyId', 'paymentDate'] },
      config_time: { fields: ['companyId', 'configId', 'paymentDate'] },
      provider_attempt: { fields: ['companyId', 'providerAttemptId'], unique: true },
      provider_reversal: { fields: ['companyId', 'reversalOfId'], unique: true },
    },
  },
  CashAdjustment: {
    scope: 'company',
    fields: {
      id: 'id',
      sessionId: 'ref:pos.Session',
      amount: 'decimal',
      reason: 'text',
      note: 'text?',
      approvedBy: 'text',
      approvedAt: 'datetime',
      accountMoveId: 'ref:account.Move',
    },
    indexes: { session: { fields: ['companyId', 'sessionId'], unique: true } },
  },
  CashMovement: {
    scope: 'company',
    fields: {
      id: 'id',
      sessionId: 'ref:pos.Session',
      configId: 'ref:pos.Config?',
      direction: 'text',
      amount: 'decimal',
      reason: 'text',
      note: 'text?',
      actorId: 'text',
      deviceId: 'text?',
      occurredAt: 'datetime',
      reversalOfId: 'ref:pos.CashMovement?',
    },
    indexes: {
      company_time: { fields: ['companyId', 'occurredAt'] },
      session_time: { fields: ['companyId', 'sessionId', 'occurredAt'] },
      config_time: { fields: ['companyId', 'configId', 'occurredAt'] },
    },
  },
  /** Append-only operational timeline for sensitive POS commands. */
  AuditEvent: {
    scope: 'company',
    append: true,
    fields: {
      id: 'id',
      subjectType: 'text',
      subjectId: 'text',
      configId: 'ref:pos.Config?',
      sessionId: 'ref:pos.Session?',
      action: 'text',
      actorId: 'text?',
      deviceId: 'text?',
      reason: 'text?',
      relatedId: 'text?',
      details: 'json',
      correlationHash: 'text?',
      actorHash: 'text?',
      subjectHash: 'text?',
      relatedHash: 'text?',
      sessionHash: 'text?',
      deviceHash: 'text?',
      occurredAt: 'datetime',
    },
    indexes: {
      company_time: { fields: ['companyId', 'occurredAt'] },
      subject_time: { fields: ['companyId', 'subjectType', 'subjectId', 'occurredAt'] },
      config_time: { fields: ['companyId', 'configId', 'occurredAt'] },
      session_time: { fields: ['companyId', 'sessionId', 'occurredAt'] },
      action_time: { fields: ['companyId', 'action', 'occurredAt'] },
    },
  },
}
