import { defineModule } from '@ketvietlab/ketjs'
import { analyticsFunctions } from './analytics.ts'
import { assetCostingFunctions } from './assets-costing.ts'
import { auditFunctions } from './audit.ts'
import { bookFunctions } from './books.ts'
import { cashReceivableFunctions } from './cash-receivables.ts'
import { closeFunctions } from './close.ts'
import { functions } from './functions.ts'
import { models } from './models.ts'
import { openingFunctions } from './opening.ts'
import { openItemFunctions } from './open-items.ts'
import { periodFunctions } from './period.ts'
import { relations } from './relations.ts'
import { reportFunctions, reports } from './reports.ts'

export default defineModule({
  name: 'account',
  // 0.9.0 establishes the Wave 0 ledger contract: exact-money arithmetic,
  // immutable company-civil dates, shared draft validation and resumable writes.
  // 0.8.0 adds ledger analytics — performance, position, revenueTimeline,
  // openItemSummary and cashFlow, the aggregates an overview screen is made of.
  // 0.7.0 adds a company-scoped product-to-sales-tax mapping. Products remain
  // shared catalogue data while the tax belongs to one legal entity's chart.
  version: '0.12.0',
  depends: ['company', 'partner', 'product', 'uom'],
  title: 'Kế toán',
  summary: 'Sổ cái kép, hoá đơn, thanh toán và kiểm soát kỳ kế toán.',
  category: 'Tài chính',
  models,
  relations,
  functions: {
    ...functions,
    ...reportFunctions,
    ...analyticsFunctions,
    ...auditFunctions,
    ...periodFunctions,
    ...openingFunctions,
    ...closeFunctions,
    ...bookFunctions,
    ...openItemFunctions,
    ...cashReceivableFunctions,
    ...assetCostingFunctions,
  },
  reports,
  messages: {
    vi: {
      'app.title': 'Kế toán',
      'app.summary': 'Sổ cái kép, hoá đơn, thanh toán và kiểm soát kỳ kế toán.',
      'app.category': 'Tài chính',
      'report.customerInvoice': 'HÓA ĐƠN KHÁCH HÀNG',
      'report.vendorBill': 'HÓA ĐƠN NHÀ CUNG CẤP',
      'report.number': 'Số',
      'report.date': 'Ngày',
      'report.partner': 'Đối tác',
      'report.description': 'Mô tả',
      'report.quantity': 'Số lượng',
      'report.unitPrice': 'Đơn giá',
      'report.balance': 'Giá trị',
      'report.untaxed': 'Trước thuế',
      'report.tax': 'Thuế',
      'report.total': 'Tổng cộng',

      'error.moveMissing': 'Bút toán không tồn tại.',
      'error.moveDraftOnly': 'Chỉ bút toán ở trạng thái nháp mới ghi sổ được.',
      'error.movePostedOnly': 'Chỉ bút toán đã ghi sổ mới đảo được.',
      'error.moveNotCancellable': 'Bút toán đã ghi sổ được sửa bằng cách đảo, không huỷ trực tiếp.',
      'error.moveConcurrent': 'Bút toán vừa thay đổi; hãy kiểm tra lại rồi thử lại.',
      'error.moveIdReused': 'Mã này đã thuộc về một bút toán khác.',
      'error.moveTypeUnsupported': 'Loại chứng từ không được hỗ trợ.',
      'error.linesTooFew': 'Một bút toán cần ít nhất hai dòng.',
      'error.lineSideBoth': 'Mỗi dòng chỉ ghi Nợ hoặc Có, không âm và không ghi cả hai.',
      'error.lineAmountRequired': 'Mỗi dòng bút toán phải có số tiền Nợ hoặc Có khác 0.',
      'error.lineBalanceInvalid': 'Số dư dòng phải bằng số Nợ trừ số Có.',
      'error.lineResidualInvalid': 'Số dư còn lại của dòng không khớp với tài khoản và số tiền.',
      'error.entryUnbalanced': 'Bút toán chưa cân đối: Nợ {debit}, Có {credit}.',
      'error.moveTotalInvalid': 'Tổng chứng từ không khớp với các dòng bút toán đã cân đối.',
      'error.reversalNoLines': 'Bút toán không có dòng nào để đảo.',
      'error.reversalIdReused': 'Mã này đã thuộc về một bút toán đảo khác.',
      'error.moveAlreadyReversed': 'Bút toán này đã có một bút toán đảo khác.',
      'error.lineDraftOnly': 'Chỉ thêm được dòng vào bút toán còn ở trạng thái nháp.',
      'error.lineIdTaken': 'Mã này đã thuộc về một dòng bút toán khác.',
      'error.moneyExactString':
        'Giá trị tiền phải là chuỗi số thập phân chính xác, không dùng số JavaScript hoặc ký hiệu số mũ.',
      'error.accountingDateInvalid': 'Ngày hạch toán và ngày chứng từ phải là ngày dân sự hợp lệ.',
      'error.moveCurrencyMismatch': 'Tiền tệ bút toán phải khớp với sổ cái của công ty đang chọn.',
      'error.periodLocked': 'Sổ {scope} đã khóa đến hết ngày {through}.',
      'error.periodConcurrent': 'Chính sách khóa kỳ vừa thay đổi; hãy kiểm tra rồi thử lại.',
      'error.periodScopeUnsupported': 'Phạm vi khóa kỳ không được hỗ trợ.',
      'error.periodReasonRequired': 'Mỗi thay đổi khóa kỳ phải có lý do.',
      'error.periodCommandIdReused': 'Mã lệnh này đã thuộc về một thay đổi khóa kỳ khác.',
      'error.hardLockPermanent': 'Khóa cứng chỉ được giữ nguyên hoặc tiến về sau.',
      'error.openingLinesRequired': 'Batch số dư đầu kỳ cần ít nhất hai dòng.',
      'error.openingLineInvalid': 'Dòng số dư đầu kỳ không hợp lệ.',
      'error.openingSourceKey': 'Mã dòng nguồn phải có và không được trùng.',
      'error.openingDescriptionRequired': 'Dòng số dư đầu kỳ phải có diễn giải.',
      'error.openingChecksumInvalid': 'Checksum nguồn phải là SHA-256 dạng hex.',
      'error.openingJournalType': 'Số dư đầu kỳ phải dùng sổ nhật ký chung.',
      'error.openingControlMismatch': 'Tổng Nợ/Có nguồn và control total phải cân bằng chính xác.',
      'error.openingPartnerRequired': 'Dòng công nợ đầu kỳ phải có đối tác.',
      'error.openingBatchIdReused': 'Mã batch đã thuộc về dữ liệu số dư đầu kỳ khác.',
      'error.openingBatchConflict': 'Không thể tạo batch số dư đầu kỳ do xung đột dữ liệu.',
      'error.openingBatchMissing': 'Batch số dư đầu kỳ không tồn tại.',
      'error.openingBatchState': 'Chỉ batch đã kiểm tra mới được ghi sổ.',
      'error.openingConcurrent': 'Batch số dư đầu kỳ vừa thay đổi; hãy kiểm tra rồi thử lại.',
      'error.closePeriodInvalid': 'Ngày kết thúc kỳ chốt không được trước ngày bắt đầu.',
      'error.closePeriodIdReused': 'Mã đợt chốt đã thuộc về kỳ khác.',
      'error.closePeriodMissing': 'Đợt chốt kỳ không tồn tại.',
      'error.closePermanent': 'Kỳ đã khóa cứng không thể thay đổi hoặc mở lại.',
      'error.closeModeUnsupported': 'Chế độ chốt kỳ phải là mềm hoặc cứng.',
      'error.closeConcurrent': 'Đợt chốt kỳ vừa thay đổi; hãy kiểm tra rồi thử lại.',
      'error.closeBlocked': 'Các bước bắt buộc của checklist vẫn còn bị chặn.',
      'error.closeLaterPeriod': 'Phải mở lại kỳ đóng sau trước kỳ này.',
      'error.accountBookUnsupported': 'Loại sổ kế toán không được hỗ trợ.',
      'error.accountBookPeriod': 'Ngày kết thúc sổ không được trước ngày bắt đầu.',
      'error.accountBookAccountRequired': 'Sổ này cần chọn tài khoản.',
      'error.accountBookPartnerRequired': 'Sổ đối tác cần chọn đối tác.',
      'error.openItemInputInvalid': 'Dữ liệu chứng từ/công nợ nguồn không hợp lệ.',
      'error.openItemControlMismatch': 'Control total công nợ không khớp residual có dấu.',
      'error.openItemCounterpart': 'Tài khoản đối ứng công nợ không hợp lệ.',
      'error.openItemJournal': 'Loại sổ nhật ký không khớp loại chứng từ nguồn.',
      'error.openItemBatchIdReused': 'Mã batch đã thuộc về dữ liệu công nợ khác.',
      'error.openItemConflict': 'Dữ liệu công nợ xung đột với ledger hiện có.',
      'error.bankAccountMissing': 'Tài khoản ngân hàng hoặc quỹ không tồn tại.',
      'error.bankJournalInvalid': 'Cần sổ nhật ký ngân hàng hoặc tiền mặt.',
      'error.bankCurrencyMismatch': 'Tiền tệ tài khoản ngân hàng phải khớp sổ cái công ty.',
      'error.bankLiquidityInvalid': 'Tài khoản thanh khoản phải là tiền mặt hoặc tiền gửi.',
      'error.bankControlAccountMissing': 'Tài khoản clearing và treo phải tồn tại.',
      'error.bankProfileMissing': 'Profile nhập sao kê không tồn tại.',
      'error.bankFormatInvalid': 'Định dạng sao kê phải là CSV, XLSX hoặc API.',
      'error.bankBalancePolicyInvalid': 'Policy số dư phải chặn hoặc cảnh báo.',
      'error.bankTransactionMissing': 'Giao dịch ngân hàng không tồn tại.',
      'error.bankTransactionNotPosted': 'Chỉ giao dịch đã ghi nhận mới được đối soát.',
      'error.matchRuleMissing': 'Rule matching đang hoạt động không tồn tại.',
      'error.reconcileAllocationsRequired': 'Cần ít nhất một dòng phân bổ.',
      'error.writeOffAccountRequired': 'Chênh lệch đối soát cần tài khoản xử lý.',
      'error.writeOffAmountMismatch': 'Số chênh lệch không khớp phân bổ.',
      'error.bankReconciliationMissing': 'Lần đối soát ngân hàng không tồn tại.',
      'error.bankReconciliationNotPosted': 'Chỉ đối soát đã ghi sổ mới hoàn tác được.',
      'error.agingBasisInvalid': 'Aging phải dựa trên ngày đến hạn hoặc ngày hóa đơn.',
      'error.cashDocumentKindInvalid': 'Loại chứng từ tiền không được hỗ trợ.',
      'error.cashDocumentMoveInvalid': 'Chứng từ tiền cần một bút toán đã ghi sổ.',
      'error.cashCountMissing': 'Biên bản kiểm kê quỹ không tồn tại.',
      'error.cashCountBalanced': 'Kiểm kê đã cân bằng, không cần bút toán chênh lệch.',
      'error.followUpConsentRequired': 'Chỉ gửi nhắc nợ khi có đồng ý nhận thông báo.',
      'error.followUpCaseMissing': 'Hồ sơ nhắc nợ không tồn tại.',
      'error.followUpMessageMissing': 'Thông báo nhắc nợ không tồn tại.',
      'error.followUpStateInvalid': 'Trạng thái gửi không được hỗ trợ.',
      'error.assetCategoryMissing': 'Danh mục tài sản đang hoạt động không tồn tại.',
      'error.assetKindInvalid': 'Loại danh mục phải là tài sản cố định hoặc công cụ dụng cụ.',
      'error.assetMethodInvalid': 'Wave đầu tiên chỉ hỗ trợ phương pháp đường thẳng.',
      'error.assetLifeInvalid': 'Thời gian sử dụng phải lớn hơn 0.',
      'error.assetAccountMissing': 'Danh mục tài sản thiếu tài khoản bắt buộc.',
      'error.assetJournalInvalid': 'Danh mục tài sản cần sổ nhật ký chung.',
      'error.assetMissing': 'Tài sản hoặc công cụ dụng cụ không tồn tại.',
      'error.assetSourceInvalid': 'Nguồn ghi tăng tài sản không được hỗ trợ.',
      'error.assetBasisInvalid': 'Nguyên giá, hao mòn hoặc giá trị thu hồi không hợp lệ.',
      'error.assetConcurrent': 'Tài sản vừa thay đổi; hãy tải lại trước khi thao tác.',
      'error.assetTransitionInvalid': 'Chuyển trạng thái tài sản không hợp lệ.',
      'error.assetBatchLocked': 'Một batch tài sản khác đang xử lý cùng ngày chốt.',
      'error.assetScheduleMissing': 'Dòng lịch khấu hao nháp không tồn tại.',
      'error.assetChangeInvalid': 'Đề xuất thay đổi tài sản không hợp lệ.',
      'error.assetChangeMissing': 'Đề xuất thay đổi tài sản không tồn tại.',
      'error.assetScheduleConflict': 'Tài sản còn bút toán khấu hao nháp cần xử lý.',
      'error.costMethodInvalid': 'Phương pháp giá thành không được hỗ trợ.',
      'error.costPolicyMissing': 'Chính sách giá thành đang hoạt động không tồn tại.',
      'error.costInputsRequired': 'Đợt tính giá thành cần snapshot đầu vào.',
      'error.costInputInvalid': 'Nguồn đầu vào giá thành không hợp lệ.',
      'error.costRunLocked': 'Một đợt tính giá thành khác đang giữ kỳ này.',
      'error.costRunMissing': 'Đợt tính giá thành không tồn tại.',
      'error.costRunStateInvalid': 'Trạng thái đợt tính giá thành không hợp lệ.',
      'error.costAdjustmentInvalid': 'Giá trị điều chỉnh phải lớn hơn 0.',
      'error.costAdjustmentMissing': 'Đề xuất điều chỉnh không tồn tại.',
      'error.fxGateInvalid': 'Gate ngoại tệ phải tắt hoặc đã phê duyệt.',
      'error.fxApprovalRequired': 'Ngoại tệ cần nguồn tỷ giá, owner và bằng chứng phê duyệt.',

      'error.accountMissing': 'Tài khoản không tồn tại.',
      'error.accountInactive': 'Không thể ghi dòng bút toán mới vào tài khoản đã ngưng sử dụng.',
      'error.accountTypeUnsupported': 'Loại tài khoản không được hỗ trợ.',
      'error.accountCodeFormat': 'Mã tài khoản chỉ gồm chữ, số và dấu chấm.',
      'error.offBalanceReconcile': 'Tài khoản ngoài bảng không đối soát được.',
      'error.defaultAccountMissing': 'Tài khoản mặc định không tồn tại.',

      'error.journalMissing': 'Sổ nhật ký không tồn tại.',
      'error.journalInactive': 'Không thể ghi bút toán mới vào sổ nhật ký đã ngưng sử dụng.',
      'error.journalTypeUnsupported': 'Loại sổ nhật ký không được hỗ trợ.',
      'error.journalCodeFormat': 'Mã sổ nhật ký chỉ gồm chữ và số.',
      'error.journalMustBeSale': 'Chứng từ khách hàng phải ghi vào sổ bán hàng.',
      'error.journalMustBePurchase': 'Chứng từ nhà cung cấp phải ghi vào sổ mua hàng.',
      'error.journalLiquidityMissing': 'Sổ nhật ký thanh toán cần một tài khoản tiền mặc định.',
      'error.journalNotLiquidity': 'Thanh toán phải dùng sổ ngân hàng hoặc tiền mặt.',
      'error.journalNotStoredValue': 'Thanh toán giá trị trả trước phải dùng sổ nhật ký chung.',
      'error.journalStoredValueAccount': 'Thanh toán giá trị trả trước cần tài khoản nợ phải trả mặc định.',

      'error.taxMissing': 'Sắc thuế không tồn tại.',
      'error.taxUseUnsupported': 'Phạm vi sử dụng thuế không được hỗ trợ.',
      'error.taxComputationUnsupported': 'Cách tính thuế không được hỗ trợ.',
      'error.taxScopeUnsupported': 'Phạm vi hàng hoá phải là dịch vụ hoặc hàng hoá.',
      'error.taxAccountMissing': 'Tài khoản thuế không tồn tại.',
      'error.taxDirectionMismatch': 'Thuế “{name}” không khớp chiều của chứng từ.',
      'error.taxPostingAccountMissing': 'Thuế “{name}” cần một tài khoản hạch toán hợp lệ.',
      'error.taxMixedPriceInclude':
        'Một dòng không thể vừa có thuế đã gồm trong giá vừa có thuế chưa gồm trong giá.',
      'error.taxManyPriceInclude': 'Mỗi dòng chỉ chịu tối đa một sắc thuế đã gồm trong giá.',
      'error.taxDivisionFull': 'Thuế tính ngược từ 100% trở lên không có cơ sở tính hữu hạn.',
      'error.productMissing': 'Mẫu sản phẩm không tồn tại.',

      'error.partnerMissing': 'Đối tác không tồn tại.',
      'error.paymentTermMissing': 'Điều khoản thanh toán không tồn tại.',
      'error.termValueUnsupported': 'Kiểu giá trị phải là phần trăm hoặc số tiền cố định.',
      'error.termDelayUnsupported': 'Cách tính hạn không được hỗ trợ.',
      'error.termPercentRange': 'Phần trăm phải nằm trong khoảng 0 đến 100.',

      'error.invoiceTypeRequired':
        'Chức năng này cần loại chứng từ là hoá đơn, hoá đơn trả lại hoặc biên lai.',
      'error.invoiceIdReused': 'Mã này đã thuộc về một hoá đơn khác.',
      'error.invoiceAccountsMissing': 'Tài khoản trên hoá đơn không tồn tại.',
      'error.lineAccountUndecided':
        'Chưa chọn tài khoản doanh thu/chi phí, mà nhóm sản phẩm lẫn công ty đều chưa đặt mặc định.',
      'error.counterpartAccountUndecided':
        'Chưa chọn tài khoản phải thu/phải trả, mà đối tác lẫn công ty đều chưa đặt mặc định.',
      'error.categoryMissing': 'Nhóm sản phẩm không tồn tại.',
      'error.defaultAccountType': 'Loại tài khoản này không dùng làm mặc định cho mục đích đó được.',
      'error.counterpartMustBeReceivable': 'Tài khoản đối ứng phải là tài khoản phải thu.',
      'error.counterpartMustBePayable': 'Tài khoản đối ứng phải là tài khoản phải trả.',

      'error.paymentTypeUnsupported': 'Loại thanh toán phải là nhận tiền hoặc gửi tiền.',
      'error.partnerTypeUnsupported': 'Loại đối tác phải là khách hàng hoặc nhà cung cấp.',
      'error.paymentSettlementKindUnsupported':
        'Nguồn thanh toán phải là thanh khoản hoặc giá trị trả trước.',
      'error.storedValueOperationUnsupported': 'Nghiệp vụ số dư trả trước phải là phát hành hoặc hết hạn.',
      'error.storedValueCounterpart':
        'Phát hành cần tài khoản tài sản đối ứng; hết hạn cần tài khoản thu nhập đối ứng.',
      'error.amountPositive': 'Số tiền thanh toán phải lớn hơn 0.',
      'error.destinationMissing': 'Tài khoản đối ứng không tồn tại.',
      'error.destinationMustBeReceivable': 'Thu tiền khách hàng phải tất toán một tài khoản phải thu.',
      'error.destinationMustBePayable': 'Chi trả nhà cung cấp phải tất toán một tài khoản phải trả.',
      'error.openItemMissing': 'Khoản công nợ đang mở không tồn tại.',
      'error.openItemAccountMismatch': 'Khoản công nợ này thuộc một tài khoản đối ứng khác.',
      'error.openItemDirection': 'Khoản công nợ này ngược chiều Nợ/Có với thanh toán.',
      'error.amountExceedsOpenItem': 'Số tiền thanh toán vượt quá khoản công nợ đã chọn.',

      'error.reconcileAmountPositive': 'Số tiền đối soát phải lớn hơn 0.',
      'error.reconcileSides': 'Đối soát cần một dòng Nợ và một dòng Có.',
      'error.reconcileAccountMismatch': 'Hai dòng đối soát phải cùng một tài khoản.',
      'error.reconcilePostedOnly': 'Chỉ đối soát được các dòng đã ghi sổ.',
      'error.reconcileNotAllowed': 'Tài khoản này không cho phép đối soát.',
      'error.reconcileAmountExceeds': 'Số tiền vượt quá số dư còn lại.',
      'error.reconcileConcurrent': 'Số dư còn lại vừa thay đổi; hãy đối soát lại.',
    },
    en: {
      'app.title': 'Accounting',
      'app.summary': 'Double-entry ledger, invoices, payments, and accounting-period controls.',
      'app.category': 'Finance',
      'report.customerInvoice': 'CUSTOMER INVOICE',
      'report.vendorBill': 'VENDOR BILL',
      'report.number': 'Number',
      'report.date': 'Date',
      'report.partner': 'Partner',
      'report.description': 'Description',
      'report.quantity': 'Quantity',
      'report.unitPrice': 'Unit price',
      'report.balance': 'Amount',
      'report.untaxed': 'Untaxed',
      'report.tax': 'Tax',
      'report.total': 'Total',

      'error.moveMissing': 'The journal entry does not exist.',
      'error.moveDraftOnly': 'Only a draft entry can be posted.',
      'error.movePostedOnly': 'Only a posted entry can be reversed.',
      'error.moveNotCancellable': 'A posted entry is corrected by reversing it, not by cancelling it.',
      'error.moveConcurrent': 'The journal entry changed; review it and try again.',
      'error.moveIdReused': 'A different journal entry already uses this id.',
      'error.moveTypeUnsupported': 'That document type is not supported.',
      'error.linesTooFew': 'A journal entry needs at least two lines.',
      'error.lineSideBoth': 'Each line takes a debit or a credit, never both, and never a negative amount.',
      'error.lineAmountRequired': 'Each journal item needs a non-zero debit or credit.',
      'error.lineBalanceInvalid': 'A journal item balance must equal debit minus credit.',
      'error.lineResidualInvalid': 'A journal item residual does not match its account and balance.',
      'error.entryUnbalanced': 'The entry is not balanced: debit {debit}, credit {credit}.',
      'error.moveTotalInvalid': 'The document totals do not match its balanced journal items.',
      'error.reversalNoLines': 'The entry has no journal items to reverse.',
      'error.reversalIdReused': 'A different reversal already uses this id.',
      'error.moveAlreadyReversed': 'This entry already has a different reversal.',
      'error.lineDraftOnly': 'Lines can only be added to an entry that is still a draft.',
      'error.lineIdTaken': 'A different journal item already uses this id.',
      'error.moneyExactString':
        'A money value must be an exact decimal string, not a JavaScript number or exponent notation.',
      'error.accountingDateInvalid': 'Accounting and document dates must be valid civil dates.',
      'error.moveCurrencyMismatch': 'The journal entry currency must match the active company ledger.',
      'error.periodLocked': 'The {scope} books are locked through {through}.',
      'error.periodConcurrent': 'The period policy changed; review it and try again.',
      'error.periodScopeUnsupported': 'That period-lock scope is not supported.',
      'error.periodReasonRequired': 'Every period-lock change requires a reason.',
      'error.periodCommandIdReused': 'That command id belongs to another period-lock change.',
      'error.hardLockPermanent': 'A hard lock can only stay in place or move forward.',
      'error.openingLinesRequired': 'An opening batch needs at least two lines.',
      'error.openingLineInvalid': 'That opening-balance line is invalid.',
      'error.openingSourceKey': 'Source line keys are required and must be unique.',
      'error.openingDescriptionRequired': 'An opening line requires a description.',
      'error.openingChecksumInvalid': 'The source checksum must be SHA-256 hex.',
      'error.openingJournalType': 'Opening balances require a general journal.',
      'error.openingControlMismatch': 'Source debit, credit, and control totals must balance exactly.',
      'error.openingPartnerRequired': 'An opening receivable or payable requires a partner.',
      'error.openingBatchIdReused': 'That batch id belongs to different opening data.',
      'error.openingBatchConflict': 'The opening batch conflicts with existing data.',
      'error.openingBatchMissing': 'The opening batch does not exist.',
      'error.openingBatchState': 'Only a validated opening batch can be posted.',
      'error.openingConcurrent': 'The opening batch changed; review it and try again.',
      'error.closePeriodInvalid': 'A close period cannot end before it starts.',
      'error.closePeriodIdReused': 'That close id belongs to a different period.',
      'error.closePeriodMissing': 'The close period does not exist.',
      'error.closePermanent': 'A hard-closed period cannot change or reopen.',
      'error.closeModeUnsupported': 'A close must be soft or hard.',
      'error.closeConcurrent': 'The close period changed; review it and try again.',
      'error.closeBlocked': 'Required close-checklist steps remain blocked.',
      'error.closeLaterPeriod': 'A later closed period must be reopened first.',
      'error.accountBookUnsupported': 'That accounting book is not supported.',
      'error.accountBookPeriod': 'The book period cannot end before it starts.',
      'error.accountBookAccountRequired': 'This book requires an account.',
      'error.accountBookPartnerRequired': 'The partner book requires a partner.',
      'error.openItemInputInvalid': 'The source open-item rows are invalid.',
      'error.openItemControlMismatch': 'Open-item controls do not match signed residuals.',
      'error.openItemCounterpart': 'The open-item counterpart account is invalid.',
      'error.openItemJournal': 'The journal type does not match the source document.',
      'error.openItemBatchIdReused': 'That batch id belongs to different open-item data.',
      'error.openItemConflict': 'The open-item source conflicts with the existing ledger.',
      'error.bankAccountMissing': 'The bank or cash account does not exist.',
      'error.bankJournalInvalid': 'A bank or cash account requires a bank or cash journal.',
      'error.bankCurrencyMismatch': 'Bank account currency must match the company ledger.',
      'error.bankLiquidityInvalid': 'The liquidity account must be cash or bank.',
      'error.bankControlAccountMissing': 'Clearing and suspense accounts must exist.',
      'error.bankProfileMissing': 'The statement import profile does not exist.',
      'error.bankFormatInvalid': 'Statement format must be CSV, XLSX, or API.',
      'error.bankBalancePolicyInvalid': 'Balance policy must block or warn.',
      'error.bankTransactionMissing': 'The bank transaction does not exist.',
      'error.bankTransactionNotPosted': 'Only a posted bank transaction can be reconciled.',
      'error.matchRuleMissing': 'The active matching rule does not exist.',
      'error.reconcileAllocationsRequired': 'At least one allocation is required.',
      'error.writeOffAccountRequired': 'A difference requires a write-off account.',
      'error.writeOffAmountMismatch': 'The write-off does not match the allocation difference.',
      'error.bankReconciliationMissing': 'The bank reconciliation does not exist.',
      'error.bankReconciliationNotPosted': 'Only a posted reconciliation can be undone.',
      'error.agingBasisInvalid': 'Aging basis must be due date or invoice date.',
      'error.cashDocumentKindInvalid': 'That cash document type is unsupported.',
      'error.cashDocumentMoveInvalid': 'A cash document requires a posted entry.',
      'error.cashCountMissing': 'The cash count does not exist.',
      'error.cashCountBalanced': 'A balanced cash count needs no difference entry.',
      'error.followUpConsentRequired': 'A reminder requires delivery consent.',
      'error.followUpCaseMissing': 'The follow-up case does not exist.',
      'error.followUpMessageMissing': 'The follow-up message does not exist.',
      'error.followUpStateInvalid': 'That delivery state is unsupported.',
      'error.assetCategoryMissing': 'The active asset category does not exist.',
      'error.assetKindInvalid': 'Category kind must be fixed asset or long-lived tool.',
      'error.assetMethodInvalid': 'The first scope supports straight-line only.',
      'error.assetLifeInvalid': 'Useful life must be greater than zero.',
      'error.assetAccountMissing': 'The asset category is missing a required account.',
      'error.assetJournalInvalid': 'The asset category requires a general journal.',
      'error.assetMissing': 'The asset or long-lived tool does not exist.',
      'error.assetSourceInvalid': 'The asset recognition source is unsupported.',
      'error.assetBasisInvalid': 'Cost, accumulated amount, or residual value is invalid.',
      'error.assetConcurrent': 'The asset changed; reload it before continuing.',
      'error.assetTransitionInvalid': 'That asset transition is not allowed.',
      'error.assetBatchLocked': 'Another asset batch owns this cutoff.',
      'error.assetScheduleMissing': 'The draft depreciation schedule line does not exist.',
      'error.assetChangeInvalid': 'The asset change proposal is invalid.',
      'error.assetChangeMissing': 'The asset change proposal does not exist.',
      'error.assetScheduleConflict': 'The asset has a draft schedule entry to resolve.',
      'error.costMethodInvalid': 'The costing method is unsupported.',
      'error.costPolicyMissing': 'The active cost policy does not exist.',
      'error.costInputsRequired': 'The cost run requires frozen inputs.',
      'error.costInputInvalid': 'A cost input source is invalid.',
      'error.costRunLocked': 'Another cost run owns this period.',
      'error.costRunMissing': 'The cost run does not exist.',
      'error.costRunStateInvalid': 'The cost run state is invalid.',
      'error.costAdjustmentInvalid': 'The adjustment amount must be positive.',
      'error.costAdjustmentMissing': 'The adjustment proposal does not exist.',
      'error.fxGateInvalid': 'The FX gate must be disabled or approved.',
      'error.fxApprovalRequired': 'FX requires a rate source, owner, and approval evidence.',

      'error.accountMissing': 'The account does not exist.',
      'error.accountInactive': 'An inactive account cannot receive a new journal item.',
      'error.accountTypeUnsupported': 'That account type is not supported.',
      'error.accountCodeFormat': 'An account code may contain only letters, numbers, and dots.',
      'error.offBalanceReconcile': 'An off-balance account cannot be reconciled.',
      'error.defaultAccountMissing': 'The default account does not exist.',

      'error.journalMissing': 'The journal does not exist.',
      'error.journalInactive': 'An inactive journal cannot post a new entry.',
      'error.journalTypeUnsupported': 'That journal type is not supported.',
      'error.journalCodeFormat': 'A journal code must be alphanumeric.',
      'error.journalMustBeSale': 'A customer document belongs in a sale journal.',
      'error.journalMustBePurchase': 'A vendor document belongs in a purchase journal.',
      'error.journalLiquidityMissing': 'A payment journal needs a default liquidity account.',
      'error.journalNotLiquidity': 'Payments require a bank or cash journal.',
      'error.journalNotStoredValue': 'Stored value settlements require a general journal.',
      'error.journalStoredValueAccount': 'Stored value settlements require a default liability account.',

      'error.taxMissing': 'The tax does not exist.',
      'error.taxUseUnsupported': 'That tax use is not supported.',
      'error.taxComputationUnsupported': 'That tax computation is not supported.',
      'error.taxScopeUnsupported': 'A tax scope must be service or goods.',
      'error.taxAccountMissing': 'The tax account does not exist.',
      'error.taxDirectionMismatch': 'Tax “{name}” does not match the direction of this document.',
      'error.taxPostingAccountMissing': 'Tax “{name}” needs a valid posting account.',
      'error.taxMixedPriceInclude': 'A line cannot mix price-included and price-excluded taxes.',
      'error.taxManyPriceInclude': 'A line carries at most one price-included tax.',
      'error.taxDivisionFull': 'A division tax of 100% or more has no finite base.',
      'error.productMissing': 'The product template does not exist.',

      'error.partnerMissing': 'The partner does not exist.',
      'error.paymentTermMissing': 'The payment term does not exist.',
      'error.termValueUnsupported': 'A value type must be a percentage or a fixed amount.',
      'error.termDelayUnsupported': 'That due-date rule is not supported.',
      'error.termPercentRange': 'A percentage must be between 0 and 100.',

      'error.invoiceTypeRequired': 'This needs an invoice, refund, or receipt document type.',
      'error.invoiceIdReused': 'A different invoice already uses this id.',
      'error.invoiceAccountsMissing': 'The accounts on this invoice do not exist.',
      'error.lineAccountUndecided':
        'No revenue or expense account was given, and neither the product category nor the company has a default.',
      'error.counterpartAccountUndecided':
        'No receivable or payable account was given, and neither the partner nor the company has a default.',
      'error.categoryMissing': 'The product category does not exist.',
      'error.defaultAccountType': 'That account type cannot serve as this default.',
      'error.counterpartMustBeReceivable': 'The counterpart account must be a receivable account.',
      'error.counterpartMustBePayable': 'The counterpart account must be a payable account.',

      'error.paymentTypeUnsupported': 'A payment must be inbound or outbound.',
      'error.partnerTypeUnsupported': 'A partner type must be customer or supplier.',
      'error.paymentSettlementKindUnsupported': 'A settlement must use liquidity or stored value.',
      'error.storedValueOperationUnsupported': 'A stored value balance operation must issue or expire value.',
      'error.storedValueCounterpart':
        'Issuance needs an asset counterpart; expiry needs an income counterpart.',
      'error.amountPositive': 'The payment amount must be greater than zero.',
      'error.destinationMissing': 'The destination account does not exist.',
      'error.destinationMustBeReceivable': 'Money received from a customer settles a receivable account.',
      'error.destinationMustBePayable': 'Money paid to a supplier settles a payable account.',
      'error.openItemMissing': 'The open item does not exist.',
      'error.openItemAccountMismatch': 'That open item belongs to another destination account.',
      'error.openItemDirection': 'That open item runs the opposite way to this payment.',
      'error.amountExceedsOpenItem': 'The payment amount exceeds the open item it was matched to.',

      'error.reconcileAmountPositive': 'A reconciliation amount must be greater than zero.',
      'error.reconcileSides': 'Reconciliation needs one debit line and one credit line.',
      'error.reconcileAccountMismatch': 'Reconciled lines must use the same account.',
      'error.reconcilePostedOnly': 'Only posted journal items can be reconciled.',
      'error.reconcileNotAllowed': 'This account does not allow reconciliation.',
      'error.reconcileAmountExceeds': 'The amount exceeds a residual balance.',
      'error.reconcileConcurrent': 'The residual balance changed just now; reconcile again.',
    },
  },
})

export {
  ACCOUNT_TYPES,
  JOURNAL_TYPES,
  MOVE_TYPES,
  MOVE_STATES,
  PAYMENT_STATES,
  PAYMENT_TYPES,
  PAYMENT_SETTLEMENT_KINDS,
  PARTNER_TYPES,
  PAYMENT_TERM_VALUES,
  PAYMENT_TERM_DELAY_TYPES,
  TAX_USES,
  TAX_AMOUNT_TYPES,
} from './functions.ts'
